/*
 * Copyright (C) 2020 eccentric_nz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package me.eccentric_nz.TARDIS.enumeration;

/**
 * @author eccentric_nz
 */
public enum STORAGE {

    AREA("Area Storage", "areas", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHBwcHBz\n"
                                + "cQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\n"
                                + "cQB+AA4AAAi2cQB+ACJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiWgXBwcHBwcHBwcHBwcHBwcHBwcHBw\n"
                                + "cHBwcHBwcHBwcHA=\n"),

    BIOME_1("Biome Storage 1", "biomes_one", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHBwcHBz\n"
                                + "cQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\n"
                                + "cQB+AA4AAAi2cQB+ADpzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACEJpb21lcyAxc3EAfgAOAJiWgXBwcHNxAH4AAHNxAH4AA3Vx\n"
                                + "AH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAACLZ0AARC\n"
                                + "T1dMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEAfgAGAAAABHEA\n"
                                + "fgAZcQB+ABp0AAlOZXh0IFBhZ2VzcQB+AA4AAABWcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw\n"),

    BIOME_2("Biome Storage 2", "biomes_two", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHNxAH4A\n"
                                + "AHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4A\n"
                                + "DgAACLZ0AARCT1dMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEA\n"
                                + "fgAGAAAABHEAfgAZcQB+ABp0AA1QcmV2aW91cyBQYWdlc3EAfgAOAAAAV3BwcHNxAH4AAHNxAH4A\n"
                                + "A3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAACLZx\n"
                                + "AH4AOnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARx\n"
                                + "AH4AGXEAfgAadAAIQmlvbWVzIDJzcQB+AA4AmJaBcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw\n"
                                + "cHBwcA==\n"),

    CIRCUIT("Circuit Storage", "circuits", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHBwcHBz\n"
                                + "cQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\n"
                                + "cQB+AA4AAAi2cQB+AFJzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHBwcHBw\n"
                                + "cHBwcHBwcHBwcHBwcHA=\n"),

    PLAYER("Player Storage", "players", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHBwcHBz\n"
                                + "cQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\n"
                                + "cQB+AA4AAAi2cQB+AC5zcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBcHBwcHBwcHBwcHBwcHBwcHBw\n"
                                + "cHBwcHBwcHBwcHBwcA==\n"),

    PRESET_1("Preset Storage 1", "presets_one", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHBwcHBz\n"
                                + "cQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\n"
                                + "cQB+AA4AAAi2cQB+AEZzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACVByZXNldHMgMXNxAH4ADgCYloFwcHBzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAE\n"
                                + "Qk9XTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARx\n"
                                + "AH4AGXEAfgAadAAJTmV4dCBQYWdlc3EAfgAOAAAAVnBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw\n"
                                + "cA==\n"),

    PRESET_2("Preset Storage 2", "presets_two", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHNxAH4A\n"
                                + "AHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4A\n"
                                + "DgAACLZ0AARCT1dMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEA\n"
                                + "fgAGAAAABHEAfgAZcQB+ABp0AA1QcmV2aW91cyBQYWdlc3EAfgAOAAAAV3BwcHNxAH4AAHNxAH4A\n"
                                + "A3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAACLZx\n"
                                + "AH4ARnNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARx\n"
                                + "AH4AGXEAfgAadAAJUHJlc2V0cyAyc3EAfgAOAJiWgXBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw\n"
                                + "cHBwcHA=\n"),

    SAVE_1("Save Storage 1", "saves_one", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHBwcHBz\n"
                                + "cQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1z\n"
                                + "cQB+AA4AAAi2cQB+ABFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1NhdmVzIDFzcQB+AA4AmJaBcHBwc3EAfgAAc3EAfgADdXEA\n"
                                + "fgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAItnQABEJP\n"
                                + "V0xzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+\n"
                                + "ABlxAH4AGnQACU5leHQgUGFnZXNxAH4ADgAAAFZwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHA=\n"),

    SAVE_2("Save Storage 2", "saves_two", "rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\n"
                                + "dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\n"
                                + "bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\n"
                                + "Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\n"
                                + "AAR0AAI9PXQAAXZ0AAR0eXBldAAEbWV0YXVxAH4ABgAAAAR0AB5vcmcuYnVra2l0LmludmVudG9y\n"
                                + "eS5JdGVtU3RhY2tzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVleHIAEGph\n"
                                + "dmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAItnQAEE1VU0lDX0RJU0NfQ0hJUlBzcQB+AABz\n"
                                + "cQB+AAN1cQB+AAYAAAAEcQB+AAh0AAltZXRhLXR5cGV0AAxkaXNwbGF5LW5hbWV0ABFjdXN0b20t\n"
                                + "bW9kZWwtZGF0YXVxAH4ABgAAAAR0AAhJdGVtTWV0YXQAClVOU1BFQ0lGSUN0AAVTYXZlc3NxAH4A\n"
                                + "DgCYloFzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAE\n"
                                + "cQB+AA1zcQB+AA4AAAi2dAARTVVTSUNfRElTQ19CTE9DS1NzcQB+AABzcQB+AAN1cQB+AAYAAAAE\n"
                                + "cQB+AAhxAH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQABUFyZWFzc3EAfgAOAJiW\n"
                                + "gXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4A\n"
                                + "DXNxAH4ADgAACLZ0AA9NVVNJQ19ESVNDX1dBSVRzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhx\n"
                                + "AH4AFXEAfgAWcQB+ABd1cQB+AAYAAAAEcQB+ABlxAH4AGnQAB1BsYXllcnNzcQB+AA4AmJaBc3EA\n"
                                + "fgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EA\n"
                                + "fgAOAAAItnQADk1VU0lDX0RJU0NfQ0FUc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVx\n"
                                + "AH4AFnEAfgAXdXEAfgAGAAAABHEAfgAZcQB+ABp0AAZCaW9tZXNzcQB+AA4AmJaBc3EAfgAAc3EA\n"
                                + "fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANc3EAfgAOAAAI\n"
                                + "tnQAD01VU0lDX0RJU0NfTUFMTHNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZx\n"
                                + "AH4AF3VxAH4ABgAAAARxAH4AGXEAfgAadAAHUHJlc2V0c3NxAH4ADgCYloFzcQB+AABzcQB+AAN1\n"
                                + "cQB+AAYAAAAEcQB+AAhxAH4ACXEAfgAKcQB+AAt1cQB+AAYAAAAEcQB+AA1zcQB+AA4AAAi2dAAO\n"
                                + "R0xPV1NUT05FX0RVU1RzcQB+AABzcQB+AAN1cQB+AAYAAAAEcQB+AAhxAH4AFXEAfgAWcQB+ABd1\n"
                                + "cQB+AAYAAAAEcQB+ABlxAH4AGnQACENpcmN1aXRzc3EAfgAOAJieQXBwcHBwcHBwcHBwcHNxAH4A\n"
                                + "AHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4A\n"
                                + "DgAACLZ0AARCT1dMc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+ABVxAH4AFnEAfgAXdXEA\n"
                                + "fgAGAAAABHEAfgAZcQB+ABp0AA1QcmV2aW91cyBQYWdlc3EAfgAOAAAAV3BwcHNxAH4AAHNxAH4A\n"
                                + "A3VxAH4ABgAAAARxAH4ACHEAfgAJcQB+AApxAH4AC3VxAH4ABgAAAARxAH4ADXNxAH4ADgAACLZx\n"
                                + "AH4AEXNxAH4AAHNxAH4AA3VxAH4ABgAAAARxAH4ACHEAfgAVcQB+ABZxAH4AF3VxAH4ABgAAAARx\n"
                                + "AH4AGXEAfgAadAAHU2F2ZXMgMnNxAH4ADgCYloFwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw\n"
                                + "cHBw\n");

    final String title;
    final String table;
    final String empty;

    STORAGE(String title, String table, String empty) {
        this.title = title;
        this.table = table;
        this.empty = empty;
    }

    public String getTitle() {
        return title;
    }

    public String getTable() {
        return table;
    }

    public String getEmpty() {
        return empty;
    }
}
