/*
 * Copyright (C) 2021 eccentric_nz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package me.eccentric_nz.tardis.enumeration;

import org.bukkit.block.Biome;

import java.util.HashMap;

/**
 * @author eccentric_nz
 */
public class TardisOldBiomeLookup {

    public static final HashMap<String, Biome> OLD_BIOME_LOOKUP = new HashMap<>();

    static {
        OLD_BIOME_LOOKUP.put("BEACHES", Biome.BEACH);
        OLD_BIOME_LOOKUP.put("BIRCH_FOREST_HILLS_MOUNTAINS", Biome.BIRCH_FOREST_HILLS);
        OLD_BIOME_LOOKUP.put("BIRCH_FOREST_MOUNTAINS", Biome.TALL_BIRCH_HILLS);
        OLD_BIOME_LOOKUP.put("COLD_BEACH", Biome.SNOWY_BEACH);
        OLD_BIOME_LOOKUP.put("COLD_DEEP_OCEAN", Biome.DEEP_COLD_OCEAN);
        OLD_BIOME_LOOKUP.put("COLD_TAIGA_HILLS", Biome.SNOWY_TAIGA_HILLS);
        OLD_BIOME_LOOKUP.put("COLD_TAIGA_MOUNTAINS", Biome.SNOWY_TAIGA_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("COLD_TAIGA", Biome.SNOWY_TAIGA);
        OLD_BIOME_LOOKUP.put("DESERT_MOUNTAINS", Biome.DESERT_HILLS);
        OLD_BIOME_LOOKUP.put("EXTREME_HILLS_MOUNTAINS", Biome.MOUNTAINS);
        OLD_BIOME_LOOKUP.put("EXTREME_HILLS_PLUS_MOUNTAINS", Biome.MODIFIED_GRAVELLY_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("EXTREME_HILLS_PLUS", Biome.GRAVELLY_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("EXTREME_HILLS_WITH_TREES", Biome.WOODED_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("EXTREME_HILLS", Biome.MOUNTAINS);
        OLD_BIOME_LOOKUP.put("FLOWER_FOREST", Biome.FLOWER_FOREST);
        OLD_BIOME_LOOKUP.put("FOREST_HILLS", Biome.WOODED_HILLS);
        OLD_BIOME_LOOKUP.put("FROZEN_DEEP_OCEAN", Biome.DEEP_FROZEN_OCEAN);
        OLD_BIOME_LOOKUP.put("HELL", Biome.NETHER_WASTES);
        OLD_BIOME_LOOKUP.put("ICE_FLATS", Biome.SNOWY_TUNDRA);
        OLD_BIOME_LOOKUP.put("ICE_MOUNTAINS", Biome.SNOWY_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("ICE_PLAINS_SPIKES", Biome.ICE_SPIKES);
        OLD_BIOME_LOOKUP.put("ICE_PLAINS", Biome.SNOWY_TUNDRA);
        OLD_BIOME_LOOKUP.put("JUNGLE_EDGE_MOUNTAINS", Biome.MODIFIED_JUNGLE_EDGE);
        OLD_BIOME_LOOKUP.put("JUNGLE_MOUNTAINS", Biome.JUNGLE_HILLS);
        OLD_BIOME_LOOKUP.put("LUKEWARM_DEEP_OCEAN", Biome.DEEP_LUKEWARM_OCEAN);
        OLD_BIOME_LOOKUP.put("MEGA_SPRUCE_TAIGA_HILLS", Biome.GIANT_SPRUCE_TAIGA_HILLS);
        OLD_BIOME_LOOKUP.put("MEGA_SPRUCE_TAIGA", Biome.GIANT_SPRUCE_TAIGA);
        OLD_BIOME_LOOKUP.put("MEGA_TAIGA_HILLS", Biome.GIANT_TREE_TAIGA_HILLS);
        OLD_BIOME_LOOKUP.put("MEGA_TAIGA", Biome.GIANT_TREE_TAIGA);
        OLD_BIOME_LOOKUP.put("MESA_BRYCE", Biome.ERODED_BADLANDS);
        OLD_BIOME_LOOKUP.put("MESA_CLEAR_ROCK", Biome.BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MESA_PLATEAU_FOREST_MOUNTAINS", Biome.MODIFIED_WOODED_BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MESA_PLATEAU_FOREST", Biome.WOODED_BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MESA_PLATEAU_MOUNTAINS", Biome.MODIFIED_BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MESA_PLATEAU", Biome.BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MESA_ROCK", Biome.WOODED_BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MESA", Biome.BADLANDS);
        OLD_BIOME_LOOKUP.put("MUSHROOM_ISLAND_SHORE", Biome.MUSHROOM_FIELD_SHORE);
        OLD_BIOME_LOOKUP.put("MUSHROOM_ISLAND", Biome.MUSHROOM_FIELDS);
        OLD_BIOME_LOOKUP.put("MUSHROOM_SHORE", Biome.MUSHROOM_FIELD_SHORE);
        OLD_BIOME_LOOKUP.put("MUTATED_BIRCH_FOREST_HILLS", Biome.TALL_BIRCH_HILLS);
        OLD_BIOME_LOOKUP.put("MUTATED_BIRCH_FOREST", Biome.TALL_BIRCH_FOREST);
        OLD_BIOME_LOOKUP.put("MUTATED_DESERT", Biome.DESERT_LAKES);
        OLD_BIOME_LOOKUP.put("MUTATED_EXTREME_HILLS_WITH_TREES", Biome.MODIFIED_GRAVELLY_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("MUTATED_EXTREME_HILLS", Biome.GRAVELLY_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("MUTATED_FOREST", Biome.FLOWER_FOREST);
        OLD_BIOME_LOOKUP.put("MUTATED_ICE_FLATS", Biome.ICE_SPIKES);
        OLD_BIOME_LOOKUP.put("MUTATED_JUNGLE_EDGE", Biome.MODIFIED_JUNGLE_EDGE);
        OLD_BIOME_LOOKUP.put("MUTATED_JUNGLE", Biome.MODIFIED_JUNGLE);
        OLD_BIOME_LOOKUP.put("MUTATED_MESA_CLEAR_ROCK", Biome.MODIFIED_BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MUTATED_MESA_ROCK", Biome.MODIFIED_WOODED_BADLANDS_PLATEAU);
        OLD_BIOME_LOOKUP.put("MUTATED_MESA", Biome.ERODED_BADLANDS);
        OLD_BIOME_LOOKUP.put("MUTATED_PLAINS", Biome.SUNFLOWER_PLAINS);
        OLD_BIOME_LOOKUP.put("MUTATED_REDWOOD_TAIGA_HILLS", Biome.GIANT_SPRUCE_TAIGA_HILLS);
        OLD_BIOME_LOOKUP.put("MUTATED_REDWOOD_TAIGA", Biome.GIANT_SPRUCE_TAIGA);
        OLD_BIOME_LOOKUP.put("MUTATED_ROOFED_FOREST", Biome.DARK_FOREST_HILLS);
        OLD_BIOME_LOOKUP.put("MUTATED_SAVANNA_ROCK", Biome.SHATTERED_SAVANNA_PLATEAU);
        OLD_BIOME_LOOKUP.put("MUTATED_SAVANNA", Biome.SHATTERED_SAVANNA);
        OLD_BIOME_LOOKUP.put("MUTATED_SWAMPLAND", Biome.SWAMP_HILLS);
        OLD_BIOME_LOOKUP.put("MUTATED_TAIGA_COLD", Biome.SNOWY_TAIGA_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("MUTATED_TAIGA", Biome.TAIGA_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("REDWOOD_TAIGA_HILLS", Biome.GIANT_TREE_TAIGA_HILLS);
        OLD_BIOME_LOOKUP.put("REDWOOD_TAIGA", Biome.GIANT_TREE_TAIGA);
        OLD_BIOME_LOOKUP.put("ROOFED_FOREST_MOUNTAINS", Biome.DARK_FOREST_HILLS);
        OLD_BIOME_LOOKUP.put("ROOFED_FOREST", Biome.DARK_FOREST);
        OLD_BIOME_LOOKUP.put("SAVANNA_MOUNTAINS", Biome.SHATTERED_SAVANNA);
        OLD_BIOME_LOOKUP.put("SAVANNA_PLATEAU_MOUNTAINS", Biome.SHATTERED_SAVANNA_PLATEAU);
        OLD_BIOME_LOOKUP.put("SAVANNA_PLATEAU", Biome.SAVANNA_PLATEAU);
        OLD_BIOME_LOOKUP.put("SAVANNA_ROCK", Biome.SAVANNA_PLATEAU);
        OLD_BIOME_LOOKUP.put("SKY_ISLAND_BARREN", Biome.END_BARRENS);
        OLD_BIOME_LOOKUP.put("SKY_ISLAND_HIGH", Biome.END_HIGHLANDS);
        OLD_BIOME_LOOKUP.put("SKY_ISLAND_LOW", Biome.SMALL_END_ISLANDS);
        OLD_BIOME_LOOKUP.put("SKY_ISLAND_MEDIUM", Biome.END_MIDLANDS);
        OLD_BIOME_LOOKUP.put("SKY", Biome.THE_END);
        OLD_BIOME_LOOKUP.put("SMALL_MOUNTAINS", Biome.MOUNTAIN_EDGE);
        OLD_BIOME_LOOKUP.put("SMALLER_EXTREME_HILLS", Biome.MOUNTAIN_EDGE);
        OLD_BIOME_LOOKUP.put("STONE_BEACH", Biome.STONE_SHORE);
        OLD_BIOME_LOOKUP.put("SUNFLOWER_PLAINS", Biome.SUNFLOWER_PLAINS);
        OLD_BIOME_LOOKUP.put("SWAMPLAND_MOUNTAINS", Biome.SWAMP_HILLS);
        OLD_BIOME_LOOKUP.put("SWAMPLAND", Biome.SWAMP);
        OLD_BIOME_LOOKUP.put("TAIGA_COLD_HILLS", Biome.SNOWY_TAIGA_HILLS);
        OLD_BIOME_LOOKUP.put("TAIGA_COLD", Biome.SNOWY_TAIGA);
        OLD_BIOME_LOOKUP.put("TAIGA_MOUNTAINS", Biome.TAIGA_MOUNTAINS);
        OLD_BIOME_LOOKUP.put("VOID", Biome.THE_VOID);
        OLD_BIOME_LOOKUP.put("WARM_DEEP_OCEAN", Biome.DEEP_WARM_OCEAN);
    }
}
