/*
 * Copyright (C) 2020 eccentric_nz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package me.eccentric_nz.TARDIS.artron;

import me.eccentric_nz.TARDIS.TARDIS;

import java.util.HashMap;
import java.util.Set;

/**
 * A TARDIS has fifteen Power Rooms that contain all of the machinery that powers and operates the ship. They are
 * located deep in a TARDIS's interior and serve as the "nerve centre" of the capsule.
 *
 * @author eccentric_nz
 */
public class TARDISCondensables {

    private final TARDIS plugin;
    private HashMap<String, Integer> condensables;

    public TARDISCondensables(TARDIS plugin) {
        this.plugin = plugin;
    }

    public void makeCondensables() {
        condensables = new HashMap<>();
        if (plugin.getConfig().getBoolean("preferences.use_default_condensables")) {
            condensables.put("ACACIA_BOAT", 3);
            condensables.put("ACACIA_BUTTON", 1);
            condensables.put("ACACIA_DOOR", 3);
            condensables.put("ACACIA_FENCE", 1);
            condensables.put("ACACIA_FENCE_GATE", 5);
            condensables.put("ACACIA_LEAVES", 1);
            condensables.put("ACACIA_LOG", 2);
            condensables.put("ACACIA_PLANKS", 2);
            condensables.put("ACACIA_PRESSURE_PLATE", 1);
            condensables.put("ACACIA_SAPLING", 2);
            condensables.put("ACACIA_SIGN", 2);
            condensables.put("ACACIA_SLAB", 2);
            condensables.put("ACACIA_STAIRS", 1);
            condensables.put("ACACIA_TRAPDOOR", 6);
            condensables.put("ACACIA_WALL_SIGN", 2);
            condensables.put("ACACIA_WOOD", 2);
            condensables.put("ACTIVATOR_RAIL", 650);
            condensables.put("ALLIUM", 2);
            condensables.put("ANDESITE", 1);
            condensables.put("ANDESITE_SLAB", 2);
            condensables.put("ANDESITE_STAIRS", 2);
            condensables.put("ANDESITE_WALL", 2);
            condensables.put("ANVIL", 200);
            condensables.put("APPLE", 10);
            condensables.put("ARMOR_STAND", 8);
            condensables.put("ARROW", 4);
            condensables.put("AZURE_BLUET", 2);
            condensables.put("BAKED_POTATO", 14);
            condensables.put("BAMBOO", 2);
            condensables.put("BARREL", 16);
            condensables.put("BEACON", 700);
            condensables.put("BEDROCK", 100);
            condensables.put("BEEF", 3);
            condensables.put("BEETROOT", 9);
            condensables.put("BEETROOT_SEEDS", 2);
            condensables.put("BEETROOT_SOUP", 5);
            condensables.put("BELL", 100);
            condensables.put("BIRCH_BOAT", 3);
            condensables.put("BIRCH_BUTTON", 1);
            condensables.put("BIRCH_DOOR", 3);
            condensables.put("BIRCH_FENCE", 1);
            condensables.put("BIRCH_FENCE_GATE", 5);
            condensables.put("BIRCH_LEAVES", 1);
            condensables.put("BIRCH_LOG", 2);
            condensables.put("BIRCH_PLANKS", 2);
            condensables.put("BIRCH_PRESSURE_PLATE", 1);
            condensables.put("BIRCH_SAPLING", 2);
            condensables.put("BIRCH_SIGN", 2);
            condensables.put("BIRCH_SLAB", 2);
            condensables.put("BIRCH_STAIRS", 1);
            condensables.put("BIRCH_TRAPDOOR", 6);
            condensables.put("BIRCH_WALL_SIGN", 2);
            condensables.put("BIRCH_WOOD", 2);
            condensables.put("BLACK_BANNER", 120);
            condensables.put("BLACK_BED", 68);
            condensables.put("BLACK_CARPET", 13);
            condensables.put("BLACK_CONCRETE", 2);
            condensables.put("BLACK_CONCRETE_POWDER", 2);
            condensables.put("BLACK_DYE", 10);
            condensables.put("BLACK_GLAZED_TERRACOTTA", 20);
            condensables.put("BLACK_SHULKER_BOX", 120);
            condensables.put("BLACK_STAINED_GLASS", 32);
            condensables.put("BLACK_STAINED_GLASS_PANE", 6);
            condensables.put("BLACK_TERRACOTTA", 15);
            condensables.put("BLACK_WALL_BANNER", 120);
            condensables.put("BLACK_WOOL", 20);
            condensables.put("BLAST_FURNACE", 110);
            condensables.put("BLAZE_POWDER", 100);
            condensables.put("BLAZE_ROD", 200);
            condensables.put("BLUE_BANNER", 120);
            condensables.put("BLUE_BED", 68);
            condensables.put("BLUE_CARPET", 13);
            condensables.put("BLUE_CONCRETE", 2);
            condensables.put("BLUE_CONCRETE_POWDER", 2);
            condensables.put("BLUE_DYE", 10);
            condensables.put("BLUE_GLAZED_TERRACOTTA", 20);
            condensables.put("BLUE_ORCHID", 2);
            condensables.put("BLUE_SHULKER_BOX", 120);
            condensables.put("BLUE_STAINED_GLASS", 32);
            condensables.put("BLUE_STAINED_GLASS_PANE", 6);
            condensables.put("BLUE_TERRACOTTA", 15);
            condensables.put("BLUE_WALL_BANNER", 120);
            condensables.put("BLUE_WOOL", 20);
            condensables.put("BONE", 2);
            condensables.put("BONE_BLOCK", 90);
            condensables.put("BONE_MEAL", 10);
            condensables.put("BOOK", 45);
            condensables.put("BOOKSHELF", 140);
            condensables.put("BOW", 15);
            condensables.put("BOWL", 1);
            condensables.put("BRAIN_CORAL", 2);
            condensables.put("BRAIN_CORAL_BLOCK", 2);
            condensables.put("BRAIN_CORAL_FAN", 2);
            condensables.put("BREAD", 30);
            condensables.put("BREWING_STAND", 200);
            condensables.put("BRICK", 5);
            condensables.put("BRICK_SLAB", 2);
            condensables.put("BRICK_STAIRS", 121);
            condensables.put("BRICK_WALL", 2);
            condensables.put("BRICKS", 21);
            condensables.put("BROWN_BANNER", 120);
            condensables.put("BROWN_BED", 68);
            condensables.put("BROWN_CARPET", 13);
            condensables.put("BROWN_CONCRETE", 2);
            condensables.put("BROWN_CONCRETE_POWDER", 2);
            condensables.put("BROWN_GLAZED_TERRACOTTA", 20);
            condensables.put("BROWN_MUSHROOM", 2);
            condensables.put("BROWN_SHULKER_BOX", 120);
            condensables.put("BROWN_STAINED_GLASS", 32);
            condensables.put("BROWN_STAINED_GLASS_PANE", 6);
            condensables.put("BROWN_TERRACOTTA", 15);
            condensables.put("BROWN_WALL_BANNER", 120);
            condensables.put("BROWN_WOOL", 20);
            condensables.put("BUBBLE_CORAL", 2);
            condensables.put("BUBBLE_CORAL_BLOCK", 2);
            condensables.put("BUBBLE_CORAL_FAN", 2);
            condensables.put("BUCKET", 22);
            condensables.put("CACTUS", 10);
            condensables.put("CAKE", 180);
            condensables.put("CAMPFIRE", 24);
            condensables.put("CARROT", 9);
            condensables.put("CARROT_ON_A_STICK", 19);
            condensables.put("CARROTS", 9);
            condensables.put("CARTOGRAPHY_TABLE", 28);
            condensables.put("CARVED_PUMPKIN", 50);
            condensables.put("CAULDRON", 154);
            condensables.put("CHARCOAL", 15);
            condensables.put("CHEST", 4);
            condensables.put("CHEST_MINECART", 30);
            condensables.put("CHICKEN", 5);
            condensables.put("CHIPPED_ANVIL", 180);
            condensables.put("CHISELED_QUARTZ_BLOCK", 60);
            condensables.put("CHISELED_RED_SANDSTONE", 3);
            condensables.put("CHISELED_SANDSTONE", 3);
            condensables.put("CHISELED_STONE_BRICKS", 4);
            condensables.put("CHORUS_FLOWER", 12);
            condensables.put("CHORUS_FRUIT", 4);
            condensables.put("CHORUS_PLANT", 4);
            condensables.put("CLAY", 12);
            condensables.put("CLAY_BALL", 3);
            condensables.put("CLOCK", 6);
            condensables.put("COAL", 15);
            condensables.put("COAL_BLOCK", 135);
            condensables.put("COAL_ORE", 15);
            condensables.put("COARSE_DIRT", 1);
            condensables.put("COBBLESTONE", 1);
            condensables.put("COBBLESTONE_SLAB", 2);
            condensables.put("COBBLESTONE_STAIRS", 12);
            condensables.put("COBBLESTONE_WALL", 2);
            condensables.put("COBWEB", 4);
            condensables.put("COCOA_BEANS", 1);
            condensables.put("COD", 5);
            condensables.put("COMPARATOR", 110);
            condensables.put("COMPASS", 22);
            condensables.put("COMPOSTER", 10);
            condensables.put("CONDUIT", 1000);
            condensables.put("COOKED_BEEF", 7);
            condensables.put("COOKED_CHICKEN", 7);
            condensables.put("COOKED_COD", 7);
            condensables.put("COOKED_MUTTON", 7);
            condensables.put("COOKED_PORKCHOP", 7);
            condensables.put("COOKED_RABBIT", 7);
            condensables.put("COOKED_SALMON", 7);
            condensables.put("COOKIE", 3);
            condensables.put("CORNFLOWER", 2);
            condensables.put("CRACKED_STONE_BRICKS", 4);
            condensables.put("CRAFTING_TABLE", 3);
            condensables.put("CREEPER_HEAD", 200);
            condensables.put("CROSSBOW", 60);
            condensables.put("CUT_RED_SANDSTONE", 3);
            condensables.put("CUT_RED_SANDSTONE_SLAB", 3);
            condensables.put("CUT_SANDSTONE", 3);
            condensables.put("CUT_SANDSTONE_SLAB", 3);
            condensables.put("CYAN_BANNER", 120);
            condensables.put("CYAN_BED", 68);
            condensables.put("CYAN_CARPET", 13);
            condensables.put("CYAN_CONCRETE", 2);
            condensables.put("CYAN_CONCRETE_POWDER", 2);
            condensables.put("CYAN_DYE", 10);
            condensables.put("CYAN_GLAZED_TERRACOTTA", 20);
            condensables.put("CYAN_SHULKER_BOX", 120);
            condensables.put("CYAN_STAINED_GLASS", 32);
            condensables.put("CYAN_STAINED_GLASS_PANE", 6);
            condensables.put("CYAN_TERRACOTTA", 15);
            condensables.put("CYAN_WALL_BANNER", 120);
            condensables.put("CYAN_WOOL", 20);
            condensables.put("DAMAGED_ANVIL", 160);
            condensables.put("DANDELION", 2);
            condensables.put("DARK_OAK_BOAT", 3);
            condensables.put("DARK_OAK_BUTTON", 1);
            condensables.put("DARK_OAK_DOOR", 3);
            condensables.put("DARK_OAK_FENCE", 1);
            condensables.put("DARK_OAK_FENCE_GATE", 5);
            condensables.put("DARK_OAK_LEAVES", 1);
            condensables.put("DARK_OAK_LOG", 2);
            condensables.put("DARK_OAK_PLANKS", 2);
            condensables.put("DARK_OAK_PRESSURE_PLATE", 1);
            condensables.put("DARK_OAK_SAPLING", 2);
            condensables.put("DARK_OAK_SIGN", 2);
            condensables.put("DARK_OAK_SLAB", 2);
            condensables.put("DARK_OAK_STAIRS", 1);
            condensables.put("DARK_OAK_TRAPDOOR", 6);
            condensables.put("DARK_OAK_WALL_SIGN", 2);
            condensables.put("DARK_OAK_WOOD", 2);
            condensables.put("DARK_PRISMARINE", 32);
            condensables.put("DAYLIGHT_DETECTOR", 130);
            condensables.put("DEAD_BRAIN_CORAL_BLOCK", 1);
            condensables.put("DEAD_BUBBLE_CORAL_BLOCK", 1);
            condensables.put("DEAD_BUSH", 2);
            condensables.put("DEAD_FIRE_CORAL_BLOCK", 1);
            condensables.put("DEAD_HORN_CORAL_BLOCK", 1);
            condensables.put("DEAD_TUBE_CORAL_BLOCK", 1);
            condensables.put("DETECTOR_RAIL", 650);
            condensables.put("DIAMOND", 200);
            condensables.put("DIAMOND_AXE", 650);
            condensables.put("DIAMOND_BLOCK", 2000);
            condensables.put("DIAMOND_BOOTS", 850);
            condensables.put("DIAMOND_CHESTPLATE", 1750);
            condensables.put("DIAMOND_HELMET", 1000);
            condensables.put("DIAMOND_HOE", 400);
            condensables.put("DIAMOND_HORSE_ARMOR", 1400);
            condensables.put("DIAMOND_LEGGINGS", 1500);
            condensables.put("DIAMOND_ORE", 200);
            condensables.put("DIAMOND_PICKAXE", 650);
            condensables.put("DIAMOND_SHOVEL", 210);
            condensables.put("DIAMOND_SWORD", 420);
            condensables.put("DIORITE", 1);
            condensables.put("DIORITE_SLAB", 2);
            condensables.put("DIORITE_STAIRS", 2);
            condensables.put("DIORITE_WALL", 2);
            condensables.put("DIRT", 1);
            condensables.put("DISPENSER", 58);
            condensables.put("DRAGON_BREATH", 50);
            condensables.put("DRAGON_EGG", 200);
            condensables.put("DRAGON_HEAD", 200);
            condensables.put("DRIED_KELP", 5);
            condensables.put("DRIED_KELP_BLOCK", 45);
            condensables.put("DROPPER", 58);
            condensables.put("EGG", 1);
            condensables.put("ELYTRA", 200);
            condensables.put("EMERALD", 200);
            condensables.put("EMERALD_BLOCK", 2000);
            condensables.put("EMERALD_ORE", 200);
            condensables.put("ENCHANTED_BOOK", 50);
            condensables.put("ENCHANTED_GOLDEN_APPLE", 3610);
            condensables.put("ENCHANTING_TABLE", 1365);
            condensables.put("END_CRYSTAL", 500);
            condensables.put("END_PORTAL_FRAME", 1000);
            condensables.put("END_ROD", 200);
            condensables.put("END_STONE", 2);
            condensables.put("END_STONE_BRICK_SLAB", 21);
            condensables.put("END_STONE_BRICK_WALL", 21);
            condensables.put("END_STONE_BRICKS", 21);
            condensables.put("ENDER_CHEST", 330);
            condensables.put("ENDER_EYE", 200);
            condensables.put("ENDER_PEARL", 50);
            condensables.put("EXPERIENCE_BOTTLE", 800);
            condensables.put("FEATHER", 3);
            condensables.put("FERMENTED_SPIDER_EYE", 22);
            condensables.put("FERN", 2);
            condensables.put("FIRE_CHARGE", 45);
            condensables.put("FIRE_CORAL", 2);
            condensables.put("FIRE_CORAL_BLOCK", 2);
            condensables.put("FIRE_CORAL_FAN", 2);
            condensables.put("FIREWORK_ROCKET", 20);
            condensables.put("FIREWORK_STAR", 30);
            condensables.put("FISHING_ROD", 10);
            condensables.put("FLETCHING_TABLE", 12);
            condensables.put("FLINT", 2);
            condensables.put("FLINT_AND_STEEL", 24);
            condensables.put("FLOWER_POT", 15);
            condensables.put("FROSTED_ICE", 4);
            condensables.put("FURNACE", 9);
            condensables.put("FURNACE_MINECART", 32);
            condensables.put("GHAST_TEAR", 90);
            condensables.put("GLASS", 30);
            condensables.put("GLASS_BOTTLE", 30);
            condensables.put("GLASS_PANE", 5);
            condensables.put("GLISTERING_MELON_SLICE", 22);
            condensables.put("GLOWSTONE", 40);
            condensables.put("GLOWSTONE_DUST", 10);
            condensables.put("GOLD_BLOCK", 450);
            condensables.put("GOLD_INGOT", 105);
            condensables.put("GOLD_NUGGET", 12);
            condensables.put("GOLD_ORE", 105);
            condensables.put("GOLDEN_APPLE", 100);
            condensables.put("GOLDEN_AXE", 16);
            condensables.put("GOLDEN_BOOTS", 16);
            condensables.put("GOLDEN_CARROT", 100);
            condensables.put("GOLDEN_CHESTPLATE", 17);
            condensables.put("GOLDEN_HELMET", 16);
            condensables.put("GOLDEN_HOE", 16);
            condensables.put("GOLDEN_HORSE_ARMOR", 735);
            condensables.put("GOLDEN_LEGGINGS", 16);
            condensables.put("GOLDEN_PICKAXE", 16);
            condensables.put("GOLDEN_SHOVEL", 16);
            condensables.put("GOLDEN_SWORD", 16);
            condensables.put("GRANITE", 1);
            condensables.put("GRANITE_SLAB", 2);
            condensables.put("GRANITE_STAIRS", 2);
            condensables.put("GRANITE_WALL", 2);
            condensables.put("GRASS", 1);
            condensables.put("GRASS_BLOCK", 1);
            condensables.put("GRAVEL", 1);
            condensables.put("GRAY_BANNER", 120);
            condensables.put("GRAY_BED", 68);
            condensables.put("GRAY_CARPET", 13);
            condensables.put("GRAY_CONCRETE", 2);
            condensables.put("GRAY_CONCRETE_POWDER", 2);
            condensables.put("GRAY_DYE", 10);
            condensables.put("GRAY_GLAZED_TERRACOTTA", 20);
            condensables.put("GRAY_SHULKER_BOX", 120);
            condensables.put("GRAY_STAINED_GLASS", 32);
            condensables.put("GRAY_STAINED_GLASS_PANE", 6);
            condensables.put("GRAY_TERRACOTTA", 15);
            condensables.put("GRAY_WALL_BANNER", 120);
            condensables.put("GRAY_WOOL", 20);
            condensables.put("GREEN_BANNER", 120);
            condensables.put("GREEN_BED", 68);
            condensables.put("GREEN_CARPET", 13);
            condensables.put("GREEN_CONCRETE", 2);
            condensables.put("GREEN_CONCRETE_POWDER", 2);
            condensables.put("GREEN_DYE", 10);
            condensables.put("GREEN_GLAZED_TERRACOTTA", 20);
            condensables.put("GREEN_SHULKER_BOX", 120);
            condensables.put("GREEN_STAINED_GLASS", 32);
            condensables.put("GREEN_STAINED_GLASS_PANE", 6);
            condensables.put("GREEN_TERRACOTTA", 15);
            condensables.put("GREEN_WALL_BANNER", 120);
            condensables.put("GREEN_WOOL", 20);
            condensables.put("GRINDSTONE", 30);
            condensables.put("GUNPOWDER", 20);
            condensables.put("HAY_BLOCK", 81);
            condensables.put("HEART_OF_THE_SEA", 200);
            condensables.put("HEAVY_WEIGHTED_PRESSURE_PLATE", 144);
            condensables.put("HOPPER", 110);
            condensables.put("HOPPER_MINECART", 133);
            condensables.put("HORN_CORAL", 2);
            condensables.put("HORN_CORAL_BLOCK", 2);
            condensables.put("HORN_CORAL_FAN", 2);
            condensables.put("ICE", 4);
            condensables.put("INFESTED_CHISELED_STONE_BRICKS", 1);
            condensables.put("INFESTED_COBBLESTONE", 1);
            condensables.put("INFESTED_CRACKED_STONE_BRICKS", 1);
            condensables.put("INFESTED_MOSSY_STONE_BRICKS", 1);
            condensables.put("INFESTED_STONE", 1);
            condensables.put("INFESTED_STONE_BRICKS", 1);
            condensables.put("INK_SAC", 10);
            condensables.put("IRON_AXE", 22);
            condensables.put("IRON_BARS", 8);
            condensables.put("IRON_BLOCK", 190);
            condensables.put("IRON_BOOTS", 44);
            condensables.put("IRON_CHESTPLATE", 44);
            condensables.put("IRON_DOOR", 132);
            condensables.put("IRON_HELMET", 44);
            condensables.put("IRON_HOE", 22);
            condensables.put("IRON_HORSE_ARMOR", 154);
            condensables.put("IRON_INGOT", 22);
            condensables.put("IRON_LEGGINGS", 44);
            condensables.put("IRON_NUGGET", 3);
            condensables.put("IRON_ORE", 22);
            condensables.put("IRON_PICKAXE", 26);
            condensables.put("IRON_SHOVEL", 26);
            condensables.put("IRON_SWORD", 24);
            condensables.put("IRON_TRAPDOOR", 688);
            condensables.put("ITEM_FRAME", 18);
            condensables.put("JACK_O_LANTERN", 56);
            condensables.put("JUKEBOX", 208);
            condensables.put("JUNGLE_BOAT", 3);
            condensables.put("JUNGLE_BUTTON", 1);
            condensables.put("JUNGLE_DOOR", 3);
            condensables.put("JUNGLE_FENCE", 1);
            condensables.put("JUNGLE_FENCE_GATE", 5);
            condensables.put("JUNGLE_LEAVES", 1);
            condensables.put("JUNGLE_LOG", 2);
            condensables.put("JUNGLE_PLANKS", 2);
            condensables.put("JUNGLE_PRESSURE_PLATE", 1);
            condensables.put("JUNGLE_SAPLING", 2);
            condensables.put("JUNGLE_SIGN", 2);
            condensables.put("JUNGLE_SLAB", 2);
            condensables.put("JUNGLE_STAIRS", 1);
            condensables.put("JUNGLE_TRAPDOOR", 6);
            condensables.put("JUNGLE_WALL_SIGN", 2);
            condensables.put("JUNGLE_WOOD", 2);
            condensables.put("KELP", 2);
            condensables.put("LADDER", 1);
            condensables.put("LANTERN", 28);
            condensables.put("LAPIS_BLOCK", 950);
            condensables.put("LAPIS_LAZULI", 10);
            condensables.put("LAPIS_ORE", 30);
            condensables.put("LARGE_FERN", 2);
            condensables.put("LAVA_BUCKET", 40);
            condensables.put("LEAD", 70);
            condensables.put("LEATHER", 10);
            condensables.put("LEATHER_BOOTS", 42);
            condensables.put("LEATHER_CHESTPLATE", 85);
            condensables.put("LEATHER_HELMET", 52);
            condensables.put("LEATHER_HORSE_ARMOR", 100);
            condensables.put("LEATHER_LEGGINGS", 75);
            condensables.put("LECTERN", 148);
            condensables.put("LEVER", 1);
            condensables.put("LIGHT_BLUE_BANNER", 120);
            condensables.put("LIGHT_BLUE_BED", 68);
            condensables.put("LIGHT_BLUE_CARPET", 13);
            condensables.put("LIGHT_BLUE_CONCRETE", 2);
            condensables.put("LIGHT_BLUE_CONCRETE_POWDER", 2);
            condensables.put("LIGHT_BLUE_DYE", 10);
            condensables.put("LIGHT_BLUE_GLAZED_TERRACOTTA", 20);
            condensables.put("LIGHT_BLUE_SHULKER_BOX", 120);
            condensables.put("LIGHT_BLUE_STAINED_GLASS", 32);
            condensables.put("LIGHT_BLUE_STAINED_GLASS_PANE", 6);
            condensables.put("LIGHT_BLUE_TERRACOTTA", 15);
            condensables.put("LIGHT_BLUE_WALL_BANNER", 120);
            condensables.put("LIGHT_BLUE_WOOL", 20);
            condensables.put("LIGHT_GRAY_BANNER", 120);
            condensables.put("LIGHT_GRAY_BED", 68);
            condensables.put("LIGHT_GRAY_CARPET", 13);
            condensables.put("LIGHT_GRAY_CONCRETE", 2);
            condensables.put("LIGHT_GRAY_CONCRETE_POWDER", 2);
            condensables.put("LIGHT_GRAY_DYE", 10);
            condensables.put("LIGHT_GRAY_GLAZED_TERRACOTTA", 20);
            condensables.put("LIGHT_GRAY_SHULKER_BOX", 120);
            condensables.put("LIGHT_GRAY_STAINED_GLASS", 32);
            condensables.put("LIGHT_GRAY_STAINED_GLASS_PANE", 6);
            condensables.put("LIGHT_GRAY_TERRACOTTA", 15);
            condensables.put("LIGHT_GRAY_WALL_BANNER", 120);
            condensables.put("LIGHT_GRAY_WOOL", 20);
            condensables.put("LIGHT_WEIGHTED_PRESSURE_PLATE", 1);
            condensables.put("LILAC", 2);
            condensables.put("LILY_OF_THE_VALLEY", 2);
            condensables.put("LILY_PAD", 1);
            condensables.put("LIME_BANNER", 120);
            condensables.put("LIME_BED", 68);
            condensables.put("LIME_CARPET", 13);
            condensables.put("LIME_CONCRETE", 2);
            condensables.put("LIME_CONCRETE_POWDER", 2);
            condensables.put("LIME_DYE", 10);
            condensables.put("LIME_GLAZED_TERRACOTTA", 20);
            condensables.put("LIME_SHULKER_BOX", 120);
            condensables.put("LIME_STAINED_GLASS", 32);
            condensables.put("LIME_STAINED_GLASS_PANE", 6);
            condensables.put("LIME_TERRACOTTA", 15);
            condensables.put("LIME_WALL_BANNER", 120);
            condensables.put("LIME_WOOL", 20);
            condensables.put("LINGERING_POTION", 50);
            condensables.put("LOOM", 14);
            condensables.put("MAGENTA_BANNER", 120);
            condensables.put("MAGENTA_BED", 68);
            condensables.put("MAGENTA_CARPET", 13);
            condensables.put("MAGENTA_CONCRETE", 2);
            condensables.put("MAGENTA_CONCRETE_POWDER", 2);
            condensables.put("MAGENTA_DYE", 10);
            condensables.put("MAGENTA_GLAZED_TERRACOTTA", 20);
            condensables.put("MAGENTA_SHULKER_BOX", 120);
            condensables.put("MAGENTA_STAINED_GLASS", 32);
            condensables.put("MAGENTA_STAINED_GLASS_PANE", 6);
            condensables.put("MAGENTA_TERRACOTTA", 15);
            condensables.put("MAGENTA_WALL_BANNER", 120);
            condensables.put("MAGENTA_WOOL", 20);
            condensables.put("MAGMA_BLOCK", 600);
            condensables.put("MAGMA_CREAM", 150);
            condensables.put("MELON", 10);
            condensables.put("MELON_BLOCK", 90);
            condensables.put("MELON_SEEDS", 2);
            condensables.put("MILK_BUCKET", 40);
            condensables.put("MINECART", 23);
            condensables.put("MOSSY_COBBLESTONE", 10);
            condensables.put("MOSSY_COBBLESTONE_SLAB", 2);
            condensables.put("MOSSY_COBBLESTONE_STAIRS", 2);
            condensables.put("MOSSY_COBBLESTONE_WALL", 2);
            condensables.put("MOSSY_STONE_BRICK_SLAB", 2);
            condensables.put("MOSSY_STONE_BRICK_STAIRS", 2);
            condensables.put("MOSSY_STONE_BRICK_WALL", 2);
            condensables.put("MOSSY_STONE_BRICKS", 2);
            condensables.put("MUSHROOM_STEW", 33);
            condensables.put("MUSIC_DISC_13", 100);
            condensables.put("MUSIC_DISC_CAT", 100);
            condensables.put("MUSIC_DISC_MELLOHI", 100);
            condensables.put("MUTTON", 3);
            condensables.put("MYCELIUM", 1);
            condensables.put("NAME_TAG", 100);
            condensables.put("NAUTILUS_SHELL", 100);
            condensables.put("NETHER_BRICK", 4);
            condensables.put("NETHER_BRICK_FENCE", 10);
            condensables.put("NETHER_BRICK_SLAB", 2);
            condensables.put("NETHER_BRICK_STAIRS", 121);
            condensables.put("NETHER_BRICK_WALL", 2);
            condensables.put("NETHER_BRICKS", 16);
            condensables.put("NETHER_QUARTZ_ORE", 15);
            condensables.put("NETHER_WART", 2);
            condensables.put("NETHER_WART_BLOCK", 19);
            condensables.put("NETHERRACK", 2);
            condensables.put("NOTE_BLOCK", 40);
            condensables.put("OAK_BOAT", 3);
            condensables.put("OAK_BUTTON", 1);
            condensables.put("OAK_DOOR", 3);
            condensables.put("OAK_FENCE", 1);
            condensables.put("OAK_FENCE_GATE", 5);
            condensables.put("OAK_LEAVES", 1);
            condensables.put("OAK_LOG", 2);
            condensables.put("OAK_PLANKS", 2);
            condensables.put("OAK_PRESSURE_PLATE", 1);
            condensables.put("OAK_SAPLING", 2);
            condensables.put("OAK_SIGN", 2);
            condensables.put("OAK_SLAB", 2);
            condensables.put("OAK_STAIRS", 1);
            condensables.put("OAK_TRAPDOOR", 6);
            condensables.put("OAK_WALL_SIGN", 2);
            condensables.put("OAK_WOOD", 2);
            condensables.put("OBSERVER", 75);
            condensables.put("OBSIDIAN", 130);
            condensables.put("ORANGE_BANNER", 120);
            condensables.put("ORANGE_BED", 68);
            condensables.put("ORANGE_CARPET", 13);
            condensables.put("ORANGE_CONCRETE", 2);
            condensables.put("ORANGE_CONCRETE_POWDER", 2);
            condensables.put("ORANGE_DYE", 10);
            condensables.put("ORANGE_GLAZED_TERRACOTTA", 20);
            condensables.put("ORANGE_SHULKER_BOX", 120);
            condensables.put("ORANGE_STAINED_GLASS", 32);
            condensables.put("ORANGE_STAINED_GLASS_PANE", 6);
            condensables.put("ORANGE_TERRACOTTA", 15);
            condensables.put("ORANGE_TULIP", 2);
            condensables.put("ORANGE_WALL_BANNER", 120);
            condensables.put("ORANGE_WOOL", 20);
            condensables.put("OXEYE_DAISY", 2);
            condensables.put("PACKED_ICE", 100);
            condensables.put("PAINTING", 25);
            condensables.put("PAPER", 10);
            condensables.put("PEONY", 2);
            condensables.put("PETRIFIED_OAK_SLAB", 2);
            condensables.put("PINK_BANNER", 120);
            condensables.put("PINK_BED", 68);
            condensables.put("PINK_CARPET", 13);
            condensables.put("PINK_CONCRETE", 2);
            condensables.put("PINK_CONCRETE_POWDER", 2);
            condensables.put("PINK_DYE", 10);
            condensables.put("PINK_GLAZED_TERRACOTTA", 20);
            condensables.put("PINK_SHULKER_BOX", 120);
            condensables.put("PINK_STAINED_GLASS", 32);
            condensables.put("PINK_STAINED_GLASS_PANE", 6);
            condensables.put("PINK_TERRACOTTA", 15);
            condensables.put("PINK_TULIP", 2);
            condensables.put("PINK_WALL_BANNER", 120);
            condensables.put("PINK_WOOL", 20);
            condensables.put("PISTON", 60);
            condensables.put("PLAYER_HEAD", 200);
            condensables.put("PODZOL", 1);
            condensables.put("POISONOUS_POTATO", 1);
            condensables.put("POLISHED_ANDESITE", 1);
            condensables.put("POLISHED_ANDESITE_SLAB", 1);
            condensables.put("POLISHED_ANDESITE_STAIRS", 1);
            condensables.put("POLISHED_DIORITE", 1);
            condensables.put("POLISHED_DIORITE_SLAB", 1);
            condensables.put("POLISHED_DIORITE_STAIRS", 1);
            condensables.put("POLISHED_GRANITE", 1);
            condensables.put("POLISHED_GRANITE_SLAB", 1);
            condensables.put("POLISHED_GRANITE_STAIRS", 1);
            condensables.put("POPPED_CHORUS_FRUIT", 8);
            condensables.put("POPPY", 2);
            condensables.put("PORKCHOP", 3);
            condensables.put("POTATO", 9);
            condensables.put("POTATOES", 9);
            condensables.put("POTION", 50);
            condensables.put("POWERED_RAIL", 650);
            condensables.put("PRISMARINE", 32);
            condensables.put("PRISMARINE_BRICKS", 72);
            condensables.put("PRISMARINE_CRYSTALS", 16);
            condensables.put("PRISMARINE_SHARD", 8);
            condensables.put("PRISMARINE_STAIRS", 2);
            condensables.put("PRISMARINE_WALL", 2);
            condensables.put("PUFFERFISH", 5);
            condensables.put("PUMPKIN", 50);
            condensables.put("PUMPKIN_PIE", 60);
            condensables.put("PUMPKIN_SEEDS", 2);
            condensables.put("PURPLE_BANNER", 120);
            condensables.put("PURPLE_BED", 68);
            condensables.put("PURPLE_CARPET", 13);
            condensables.put("PURPLE_CONCRETE", 2);
            condensables.put("PURPLE_CONCRETE_POWDER", 2);
            condensables.put("PURPLE_DYE", 10);
            condensables.put("PURPLE_GLAZED_TERRACOTTA", 20);
            condensables.put("PURPLE_SHULKER_BOX", 120);
            condensables.put("PURPLE_STAINED_GLASS", 32);
            condensables.put("PURPLE_STAINED_GLASS_PANE", 6);
            condensables.put("PURPLE_TERRACOTTA", 15);
            condensables.put("PURPLE_WALL_BANNER", 120);
            condensables.put("PURPLE_WOOL", 20);
            condensables.put("PURPUR_BLOCK", 22);
            condensables.put("PURPUR_PILLAR", 22);
            condensables.put("PURPUR_SLAB", 26);
            condensables.put("PURPUR_STAIRS", 122);
            condensables.put("QUARTZ", 15);
            condensables.put("QUARTZ_BLOCK", 60);
            condensables.put("QUARTZ_PILLAR", 60);
            condensables.put("QUARTZ_SLAB", 30);
            condensables.put("QUARTZ_STAIRS", 122);
            condensables.put("RABBIT", 3);
            condensables.put("RABBIT_FOOT", 100);
            condensables.put("RABBIT_HIDE", 10);
            condensables.put("RABBIT_STEW", 33);
            condensables.put("RAIL", 22);
            condensables.put("RED_BANNER", 120);
            condensables.put("RED_BED", 68);
            condensables.put("RED_CARPET", 13);
            condensables.put("RED_CONCRETE", 2);
            condensables.put("RED_CONCRETE_POWDER", 2);
            condensables.put("RED_DYE", 10);
            condensables.put("RED_GLAZED_TERRACOTTA", 20);
            condensables.put("RED_MUSHROOM", 2);
            condensables.put("RED_NETHER_BRICK_SLAB", 12);
            condensables.put("RED_NETHER_BRICK_STAIRS", 12);
            condensables.put("RED_NETHER_BRICK_WALL", 12);
            condensables.put("RED_NETHER_BRICKS", 12);
            condensables.put("RED_SAND", 1);
            condensables.put("RED_SANDSTONE", 3);
            condensables.put("RED_SANDSTONE_SLAB", 2);
            condensables.put("RED_SANDSTONE_STAIRS", 119);
            condensables.put("RED_SANDSTONE_WALL", 2);
            condensables.put("RED_SHULKER_BOX", 120);
            condensables.put("RED_STAINED_GLASS", 32);
            condensables.put("RED_STAINED_GLASS_PANE", 6);
            condensables.put("RED_TERRACOTTA", 15);
            condensables.put("RED_TULIP", 2);
            condensables.put("RED_WALL_BANNER", 120);
            condensables.put("RED_WOOL", 20);
            condensables.put("REDSTONE", 32);
            condensables.put("REDSTONE_BLOCK", 288);
            condensables.put("REDSTONE_LAMP", 160);
            condensables.put("REDSTONE_ORE", 32);
            condensables.put("REDSTONE_TORCH", 32);
            condensables.put("REDSTONE_WIRE", 32);
            condensables.put("REPEATER", 110);
            condensables.put("ROSE_BUSH", 2);
            condensables.put("ROTTEN_FLESH", 1);
            condensables.put("SADDLE", 100);
            condensables.put("SALMON", 5);
            condensables.put("SAND", 1);
            condensables.put("SANDSTONE", 3);
            condensables.put("SANDSTONE_SLAB", 2);
            condensables.put("SANDSTONE_STAIRS", 118);
            condensables.put("SANDSTONE_WALL", 2);
            condensables.put("SCAFFOLDING", 18);
            condensables.put("SCUTE", 20);
            condensables.put("SEA_LANTERN", 160);
            condensables.put("SEA_PICKLE", 6);
            condensables.put("SEAGRASS", 2);
            condensables.put("SHEARS", 44);
            condensables.put("SHIELD", 28);
            condensables.put("SHULKER_SHELL", 50);
            condensables.put("SKELETON_SKULL", 200);
            condensables.put("SLIME_BALL", 50);
            condensables.put("SLIME_BLOCK", 450);
            condensables.put("SMITHING_TABLE", 52);
            condensables.put("SMOKER", 18);
            condensables.put("SMOOTH_QUARTZ", 60);
            condensables.put("SMOOTH_QUARTZ_SLAB", 60);
            condensables.put("SMOOTH_QUARTZ_STAIRS", 60);
            condensables.put("SMOOTH_RED_SANDSTONE", 4);
            condensables.put("SMOOTH_RED_SANDSTONE_SLAB", 4);
            condensables.put("SMOOTH_RED_SANDSTONE_STAIRS", 4);
            condensables.put("SMOOTH_SANDSTONE", 4);
            condensables.put("SMOOTH_SANDSTONE_SLAB", 4);
            condensables.put("SMOOTH_SANDSTONE_STAIRS", 4);
            condensables.put("SMOOTH_STONE", 4);
            condensables.put("SMOOTH_STONE_SLAB", 4);
            condensables.put("SNOW_BLOCK", 4);
            condensables.put("SNOWBALL", 1);
            condensables.put("SOUL_SAND", 2);
            condensables.put("SPECTRAL_ARROW", 44);
            condensables.put("SPIDER_EYE", 10);
            condensables.put("SPLASH_POTION", 50);
            condensables.put("SPONGE", 80);
            condensables.put("SPRUCE_BARK", 2);
            condensables.put("SPRUCE_BOAT", 3);
            condensables.put("SPRUCE_BUTTON", 1);
            condensables.put("SPRUCE_DOOR", 3);
            condensables.put("SPRUCE_FENCE", 1);
            condensables.put("SPRUCE_FENCE_GATE", 5);
            condensables.put("SPRUCE_LEAVES", 1);
            condensables.put("SPRUCE_LOG", 2);
            condensables.put("SPRUCE_PLANKS", 2);
            condensables.put("SPRUCE_PRESSURE_PLATE", 1);
            condensables.put("SPRUCE_SAPLING", 2);
            condensables.put("SPRUCE_SIGN", 2);
            condensables.put("SPRUCE_SLAB", 2);
            condensables.put("SPRUCE_STAIRS", 1);
            condensables.put("SPRUCE_TRAPDOOR", 6);
            condensables.put("SPRUCE_WALL_SIGN", 2);
            condensables.put("STICK", 1);
            condensables.put("STICKY_PISTON", 110);
            condensables.put("STONE", 30);
            condensables.put("STONE_AXE", 3);
            condensables.put("STONE_BRICK_SLAB", 2);
            condensables.put("STONE_BRICK_STAIRS", 124);
            condensables.put("STONE_BRICK_WALL", 2);
            condensables.put("STONE_BRICKS", 4);
            condensables.put("STONE_BUTTON", 16);
            condensables.put("STONE_HOE", 3);
            condensables.put("STONE_PICKAXE", 4);
            condensables.put("STONE_PRESSURE_PLATE", 6);
            condensables.put("STONE_SHOVEL", 2);
            condensables.put("STONE_SLAB", 23);
            condensables.put("STONE_STAIRS", 23);
            condensables.put("STONE_SWORD", 3);
            condensables.put("STONECUTTER", 112);
            condensables.put("STRING", 5);
            condensables.put("STRIPPED_ACACIA_LOG", 2);
            condensables.put("STRIPPED_ACACIA_WOOD", 2);
            condensables.put("STRIPPED_BIRCH_LOG", 2);
            condensables.put("STRIPPED_BIRCH_WOOD", 2);
            condensables.put("STRIPPED_DARK_OAK_LOG", 2);
            condensables.put("STRIPPED_DARK_OAK_WOOD", 2);
            condensables.put("STRIPPED_JUNGLE_LOG", 2);
            condensables.put("STRIPPED_JUNGLE_WOOD", 2);
            condensables.put("STRIPPED_OAK_LOG", 2);
            condensables.put("STRIPPED_OAK_WOOD", 2);
            condensables.put("STRIPPED_SPRUCE_LOG", 2);
            condensables.put("STRIPPED_SPRUCE_WOOD", 2);
            condensables.put("SUGAR", 10);
            condensables.put("SUGAR_CANE", 10);
            condensables.put("SUNFLOWER", 2);
            condensables.put("SUSPICIOUS_STEW", 8);
            condensables.put("SWEET_BERRIES", 10);
            condensables.put("TALL_GRASS", 2);
            condensables.put("TERRACOTTA", 12);
            condensables.put("TIPPED_ARROW", 10);
            condensables.put("TNT", 100);
            condensables.put("TNT_MINECART", 123);
            condensables.put("TORCH", 4);
            condensables.put("TOTEM_OF_UNDYING", 10000);
            condensables.put("TRAPPED_CHEST", 30);
            condensables.put("TRIPWIRE", 2);
            condensables.put("TRIPWIRE_HOOK", 25);
            condensables.put("TROPICAL_FISH", 5);
            condensables.put("TUBE_CORAL", 2);
            condensables.put("TUBE_CORAL_BLOCK", 2);
            condensables.put("TUBE_CORAL_FAN", 2);
            condensables.put("TURTLE_HELMET", 100);
            condensables.put("VINE", 1);
            condensables.put("WATER_BUCKET", 40);
            condensables.put("WET_SPONGE", 80);
            condensables.put("WHEAT", 9);
            condensables.put("WHEAT_SEEDS", 2);
            condensables.put("WHITE_BANNER", 120);
            condensables.put("WHITE_BED", 68);
            condensables.put("WHITE_CARPET", 13);
            condensables.put("WHITE_CONCRETE", 2);
            condensables.put("WHITE_CONCRETE_POWDER", 2);
            condensables.put("WHITE_DYE", 10);
            condensables.put("WHITE_GLAZED_TERRACOTTA", 20);
            condensables.put("WHITE_SHULKER_BOX", 120);
            condensables.put("WHITE_STAINED_GLASS", 32);
            condensables.put("WHITE_STAINED_GLASS_PANE", 6);
            condensables.put("WHITE_TERRACOTTA", 15);
            condensables.put("WHITE_TULIP", 2);
            condensables.put("WHITE_WALL_BANNER", 120);
            condensables.put("WHITE_WOOL", 20);
            condensables.put("WITHER_ROSE", 2);
            condensables.put("WITHER_SKELETON_SKULL", 200);
            condensables.put("WOODEN_AXE", 2);
            condensables.put("WOODEN_HOE", 2);
            condensables.put("WOODEN_PICKAXE", 2);
            condensables.put("WOODEN_SHOVEL", 1);
            condensables.put("WOODEN_SWORD", 1);
            condensables.put("WRITABLE_BOOK", 45);
            condensables.put("WRITTEN_BOOK", 45);
            condensables.put("YELLOW_BANNER", 120);
            condensables.put("YELLOW_BED", 68);
            condensables.put("YELLOW_CARPET", 13);
            condensables.put("YELLOW_CONCRETE", 2);
            condensables.put("YELLOW_CONCRETE_POWDER", 2);
            condensables.put("YELLOW_DYE", 10);
            condensables.put("YELLOW_GLAZED_TERRACOTTA", 20);
            condensables.put("YELLOW_SHULKER_BOX", 120);
            condensables.put("YELLOW_STAINED_GLASS", 32);
            condensables.put("YELLOW_STAINED_GLASS_PANE", 6);
            condensables.put("YELLOW_TERRACOTTA", 15);
            condensables.put("YELLOW_WALL_BANNER", 120);
            condensables.put("YELLOW_WOOL", 20);
            condensables.put("ZOMBIE_HEAD", 200);
            // TODO set 1.16 values correctly
//            condensables.put("ANCIENT_DEBRIS", 50);
//            condensables.put("BASALT", 1);
//            condensables.put("BLACKSTONE", 1);
//            condensables.put("BLACKSTONE_SLAB", 1);
//            condensables.put("BLACKSTONE_STAIRS", 1);
//            condensables.put("BLACKSTONE_WALL", 1);
//            condensables.put("CHAIN", 1);
//            condensables.put("CHISELED_NETHER_BRICKS", 1);
//            condensables.put("CHISELED_POLISHED_BLACKSTONE", 1);
//            condensables.put("CRACKED_NETHER_BRICKS", 1);
//            condensables.put("CRACKED_POLISHED_BLACKSTONE_BRICKS", 2);
//            condensables.put("CRIMSON_BUTTON", 3);
//            condensables.put("CRIMSON_DOOR", 3);
//            condensables.put("CRIMSON_FENCE", 3);
//            condensables.put("CRIMSON_FENCE_GATE", 3);
//            condensables.put("CRIMSON_FUNGI", 1);
//            condensables.put("CRIMSON_HYPHAE", 1);
//            condensables.put("CRIMSON_NYLIUM", 1);
//            condensables.put("CRIMSON_PLANKS", 1);
//            condensables.put("CRIMSON_PRESSURE_PLATE", 3);
//            condensables.put("CRIMSON_ROOT", 1);
//            condensables.put("CRIMSON_SIGN", 3);
//            condensables.put("CRIMSON_SLAB", 3);
//            condensables.put("CRIMSON_STAIRS", 3);
//            condensables.put("CRIMSON_STEM", 1);
//            condensables.put("CRIMSON_TRAPDOOR", 3);
//            condensables.put("CRYING_OBSIDIAN", 150);
//            condensables.put("GILDED_BLACKSTONE", 1);
//            condensables.put("LODESTONE", 200);
//            condensables.put("MUSIC_DISC_PIGSTEP", 100);
//            condensables.put("NETHER_GOLD_ORE", 1);
//            condensables.put("NETHER_SPROUTS", 1);
//            condensables.put("NETHERITE_AXE", 1870);
//            condensables.put("NETHERITE_BLOCK", 10980);
//            condensables.put("NETHERITE_BOOTS", 2070);
//            condensables.put("NETHERITE_CHESTPLATE", 2970);
//            condensables.put("NETHERITE_HELMET", 2220);
//            condensables.put("NETHERITE_HOE", 1620);
//            condensables.put("NETHERITE_INGOT", 1220);
//            condensables.put("NETHERITE_LEGGINGS", 2720);
//            condensables.put("NETHERITE_PICKAXE", 1870);
//            condensables.put("NETHERITE_SCRAP", 200);
//            condensables.put("NETHERITE_SHOVEL", 1430);
//            condensables.put("NETHERITE_SWORD", 1640);
//            condensables.put("POLISHED_BLACKSTONE", 2);
//            condensables.put("POLISHED_BLACKSTONE_BRICK_SLAB", 2);
//            condensables.put("POLISHED_BLACKSTONE_BRICK_STAIRS", 2);
//            condensables.put("POLISHED_BLACKSTONE_BRICK_WALL", 2);
//            condensables.put("POLISHED_BLACKSTONE_BRICKS", 2);
//            condensables.put("POLISHED_BLACKSTONE_SLAB", 2);
//            condensables.put("POLISHED_BLACKSTONE_STAIRS", 2);
//            condensables.put("POLISHED_BLACKSTONE_WALL", 2);
//            condensables.put("QUARTZ_BRICKS", 1);
//            condensables.put("RESPAWN_ANCHOR", 1);
//            condensables.put("SHROOM_LIGHT", 1);
//            condensables.put("SOUL_CAMPFIRE", 24);
//            condensables.put("SOUL_LANTERN", 24);
//            condensables.put("SOUL_SOIL", 1);
//            condensables.put("SOUL_TORCH", 24);
//            condensables.put("STRIPPED_CRIMSON_HYPHAE", 4);
//            condensables.put("STRIPPED_CRIMSON_STEM", 4);
//            condensables.put("STRIPPED_WARPED_HYPHAE", 4);
//            condensables.put("STRIPPED_WARPED_STEM", 4);
//            condensables.put("TARGET", 24);
//            condensables.put("TWISTING_VINES", 24);
//            condensables.put("WARPED_BUTTON", 3);
//            condensables.put("WARPED_DOOR", 3);
//            condensables.put("WARPED_FENCE", 3);
//            condensables.put("WARPED_FENCE_GATE", 3);
//            condensables.put("WARPED_FUNGI", 1);
//            condensables.put("WARPED_FUNGUS_ON_A_STICK", 24);
//            condensables.put("WARPED_HYPHAE", 1);
//            condensables.put("WARPED_NYLIUM", 1);
//            condensables.put("WARPED_PLANKS", 1);
//            condensables.put("WARPED_PRESSURE_PLATE", 3);
//            condensables.put("WARPED_ROOTS", 1);
//            condensables.put("WARPED_SIGN", 1);
//            condensables.put("WARPED_SLAB", 3);
//            condensables.put("WARPED_STAIRS", 3);
//            condensables.put("WARPED_STEM", 1);
//            condensables.put("WARPED_TRAPDOOR", 3);
//            condensables.put("WARPED_WART_BLOCK", 24);
//            condensables.put("WEEPING_VINES", 24);
        } else {
            Set<String> items = plugin.getCondensablesConfig().getKeys(false);
            items.forEach((item) -> condensables.put(item, plugin.getCondensablesConfig().getInt(item)));
        }
    }

    public HashMap<String, Integer> getCondensables() {
        return condensables;
    }
}
