package me.eccentric_nz.TARDIS.rooms.debug;

import org.bukkit.Material;

import java.util.List;

public class DebugHandles {

    public static final List<GuiPreview> ICONS = List.of(
            new GuiPreview(Material.ARROW, 9, "handles_operator_addition"),
            new GuiPreview(Material.ARROW, 10, "handles_operator_subtraction"),
            new GuiPreview(Material.BIRCH_BUTTON, 10000001, "handles_off"),
            new GuiPreview(Material.BIRCH_BUTTON, 10000002, "handles_on"),
            new GuiPreview(Material.BIRCH_BUTTON, 10000040, "communicator"),
            new GuiPreview(Material.LEATHER_HELMET, 10000040, "communicator"),
            new GuiPreview(Material.PAPER, 1, "handles_command_comehere"),
            new GuiPreview(Material.PAPER, 2, "handles_command_hide"),
            new GuiPreview(Material.PAPER, 3, "handles_command_rebuild"),
            new GuiPreview(Material.PAPER, 4, "handles_command_scan"),
            new GuiPreview(Material.PAPER, 5, "handles_command_take_off"),
            new GuiPreview(Material.PAPER, 6, "handles_command_travel"),
            new GuiPreview(Material.PAPER, 7, "handles_command_land"),
            new GuiPreview(Material.PAPER, 8, "handles_control_for"),
            new GuiPreview(Material.PAPER, 9, "handles_control_to"),
            new GuiPreview(Material.PAPER, 10, "handles_control_do"),
            new GuiPreview(Material.PAPER, 11, "handles_control_end"),
            new GuiPreview(Material.PAPER, 12, "handles_control_if"),
            new GuiPreview(Material.PAPER, 13, "handles_control_else"),
            new GuiPreview(Material.PAPER, 14, "handles_control_else_if"),
            new GuiPreview(Material.PAPER, 15, "handles_control_break"),
            new GuiPreview(Material.PAPER, 16, "handles_event_materialise"),
            new GuiPreview(Material.PAPER, 17, "handles_event_dematerialise"),
            new GuiPreview(Material.PAPER, 18, "handles_event_artron"),
            new GuiPreview(Material.PAPER, 19, "handles_event_death"),
            new GuiPreview(Material.PAPER, 20, "handles_event_enter"),
            new GuiPreview(Material.PAPER, 21, "handles_event_exit"),
            new GuiPreview(Material.PAPER, 22, "handles_event_hads"),
            new GuiPreview(Material.PAPER, 23, "handles_event_siege_on"),
            new GuiPreview(Material.PAPER, 24, "handles_event_siege_off"),
            new GuiPreview(Material.PAPER, 25, "handles_event_log_out"),
            new GuiPreview(Material.PAPER, 26, "handles_number_zero"),
            new GuiPreview(Material.PAPER, 27, "handles_number_one"),
            new GuiPreview(Material.PAPER, 28, "handles_number_two"),
            new GuiPreview(Material.PAPER, 29, "handles_number_three"),
            new GuiPreview(Material.PAPER, 30, "handles_number_four"),
            new GuiPreview(Material.PAPER, 31, "handles_number_five"),
            new GuiPreview(Material.PAPER, 32, "handles_number_six"),
            new GuiPreview(Material.PAPER, 33, "handles_number_seven"),
            new GuiPreview(Material.PAPER, 34, "handles_number_eight"),
            new GuiPreview(Material.PAPER, 35, "handles_number_nine"),
            new GuiPreview(Material.PAPER, 36, "handles_number_coin"),
            new GuiPreview(Material.PAPER, 37, "handles_number_random"),
            new GuiPreview(Material.PAPER, 38, "handles_operator_assignment"),
            new GuiPreview(Material.PAPER, 39, "handles_operator_addition"),
            new GuiPreview(Material.PAPER, 40, "handles_operator_subtraction"),
            new GuiPreview(Material.PAPER, 41, "handles_operator_multiplication"),
            new GuiPreview(Material.PAPER, 42, "handles_operator_division"),
            new GuiPreview(Material.PAPER, 43, "handles_operator_and"),
            new GuiPreview(Material.PAPER, 44, "handles_operator_or"),
            new GuiPreview(Material.PAPER, 45, "handles_operator_equals"),
            new GuiPreview(Material.PAPER, 46, "handles_operator_not_equal"),
            new GuiPreview(Material.PAPER, 47, "handles_operator_less_than"),
            new GuiPreview(Material.PAPER, 48, "handles_operator_less_than_equal"),
            new GuiPreview(Material.PAPER, 49, "handles_operator_greater_than"),
            new GuiPreview(Material.PAPER, 50, "handles_operator_greater_than_equal"),
            new GuiPreview(Material.PAPER, 51, "handles_operator_modulo"),
            new GuiPreview(Material.PAPER, 52, "handles_selector_time_lord"),
            new GuiPreview(Material.PAPER, 53, "handles_selector_companions"),
            new GuiPreview(Material.PAPER, 54, "handles_selector_tardis"),
            new GuiPreview(Material.PAPER, 55, "handles_selector_door"),
            new GuiPreview(Material.PAPER, 56, "handles_selector_lights"),
            new GuiPreview(Material.PAPER, 57, "handles_selector_power"),
            new GuiPreview(Material.PAPER, 58, "handles_selector_siege"),
            new GuiPreview(Material.PAPER, 59, "handles_variable_variable"),
            new GuiPreview(Material.PAPER, 60, "handles_variable_x"),
            new GuiPreview(Material.PAPER, 61, "handles_variable_y"),
            new GuiPreview(Material.PAPER, 62, "handles_variable_z"),
            new GuiPreview(Material.PAPER, 63, "handles_variable_open"),
            new GuiPreview(Material.PAPER, 64, "handles_variable_close"),
            new GuiPreview(Material.PAPER, 65, "handles_variable_lock"),
            new GuiPreview(Material.PAPER, 66, "handles_variable_unlock"),
            new GuiPreview(Material.PAPER, 67, "handles_variable_on"),
            new GuiPreview(Material.PAPER, 68, "handles_variable_off"),
            new GuiPreview(Material.PAPER, 69, "handles_variable_show"),
            new GuiPreview(Material.PAPER, 70, "handles_variable_redstone"),
            new GuiPreview(Material.PAPER, 71, "handles_variable_home"),
            new GuiPreview(Material.PAPER, 72, "handles_variable_recharger")
    );
}
