name: TARDIS
version: '7.0.0'
main: me.eccentric_nz.TARDIS.TARDIS
description: A plugin for all Doctor Who fans - create and use a TARDIS! Teleport to random destinations - it's bigger on the inside!
api-version: '1.21.11'
bootstrapper: me.eccentric_nz.TARDIS.Bootstrap
#loader: io.papermc.testplugin.TestPluginLoader