authors: [eccentric_nz]
description: A plugin for all Doctor Who fans - create and use a TARDIS! Teleport to random destinations - it's bigger on the inside!
main: me.eccentric_nz.TARDIS.TARDIS
name: TARDIS
startup: postworld
softdepend: [Multiverse-Core,Multiverse-Adventure,Multiverse-Inventories,MultiWorld,My Worlds,WorldGuard,WorldBorder,Towny,Citizens]
website: http://dev.bukkit.org/bukkit-plugins/tardis/
dev-url: http://dev.bukkit.org/bukkit-plugins/tardis/
url: http://eccentricdevotion.github.io/TARDIS/
version: maven-version-number
permissions:
  tardis.admin:
    description: Allow players access to the TARDIS admin commands.
    default: op
  tardis.delete:
    description: Allow players to delete any TARDIS.
    default: false
  tardis.skeletonkey:
    description: Allow players to enter any TARDIS.
    default: false
  tardis.use:
    description: Allow players to create & delete a TARDIS, and teleport to destinations.
    children:
      tardis.create: true
      tardis.exterminate: true
      tardis.timetravel: true
      tardis.list: true
      tardis.save: true
      tardis.enter: true
      tardis.find: true
      tardis.add: true
      tardis.help: true
      tardis.update: true
      tardis.rebuild: true
      tardis.book: true
      tardis.gravity: true
      tardis.texture: true
      tardis.temporal: true
    default: op
  tardis.exile:
    description: Disallow players from travelling anywhere but to areas they have a permission node for.
    default: false
  tardis.create:
    description: Allow players to create a TARDIS.
    default: op
  tardis.create_world:
    description: Allow players to create a TARDIS in it's own world. This is only used in conjuction with the create_worlds_with_perms config option.
    default: op
  tardis.exterminate:
    description: Allow players to delete their own TARDIS.
    default: op
  tardis.timetravel:
    description: Allow players to teleport to random locations and saved destinations.
    default: op
  tardis.timetravel.player:
    description: Allow players to teleport to player locations.
    default: op
  tardis.timetravel.location:
    description: Allow players to teleport to coordinates.
    default: op
  tardis.timetravel.biome:
    description: Allow players to teleport to coordinates.
    default: op
  tardis.list:
    description: Allow players to list saved time travel destinations.
    default: op
  tardis.save:
    description: Allow players to save time travel destinations.
    default: op
  tardis.home:
    description: Allow players to save a time travel destination as their home.
    default: op
  tardis.enter:
    description: Allow players to enter a TARDIS.
    default: op
  tardis.find:
    description: Allow players to find their TARDIS.
    default: op
  tardis.add:
    description: Allow players to add/remove companions to their TARDIS.
    default: op
  tardis.help:
    description: Allow players to view TARDIS help pages.
    default: true
  tardis.update:
    description: Allow players to modify the TARDIS interior.
    default: true
  tardis.rebuild:
    description: Allow players to rebuild the TARDIS.
    default: true
  tardis.bigger:
    description: Allow players to build the 'bigger' TARDIS.
    default: op
  tardis.deluxe:
    description: Allow players to build the 'deluxe' TARDIS.
    default: op
  tardis.eleventh:
    description: Allow players to build the 'eleventh' TARDIS.
    default: op
  tardis.redstone:
    description: Allow players to build the 'redstone' TARDIS.
    default: op
  tardis.steampunk:
    description: Allow players to build the 'steampunk' TARDIS.
    default: op
  tardis.ars:
    description: Allow players to build the 'Architectural Reconfiguration System' TARDIS.
    default: op
  tardis.plank:
    description: Allow players to build the 'wood' TARDIS.
    default: op
  tardis.tom:
    description: Allow players to build the '4th Doctor's' TARDIS.
    default: op
  tardis.custom:
    description: Allow players to build the server's 'custom' TARDIS.
    default: op
  tardis.end:
    description: Allow players to time travel to the END.
    default: op
  tardis.nether:
    description: Allow players to time travel to the NETHER.
    default: op
  tardis.room:
    description: Allow players to grow extra rooms.
    children:
      tardis.room.antigravity: true
      tardis.room.arboretum: true
      tardis.room.baker: true
      tardis.room.bedroom: true
      tardis.room.cross: true
      tardis.room.empty: true
      tardis.room.farm: true
      tardis.room.gravity: true
      tardis.room.greenhouse: true
      tardis.room.harmony: true
      tardis.room.kitchen: true
      tardis.room.library: true
      tardis.room.long: true
      tardis.room.mushroom: true
      tardis.room.passage: true
      tardis.room.pool: true
      tardis.room.rail: true
      tardis.room.stable: true
      tardis.room.trenzalore: true
      tardis.room.vault: true
      tardis.room.village: true
      tardis.room.wood: true
      tardis.room.workshop: true
    default: op
  tardis.gravity:
    description: Allow players to use the /tardisgravity command.
    default: op
  tardis.farm:
    description: Allow players to farm mobs.
    default: op
  tardis.autonomous:
    description: Allow players to use the TARDIS autonomous homing function.
    default: op
  tardis.book:
    description: Allow players to use TARDIS books and gain achievements.
    default: op
  tardis.backdoor:
    description: Allow players to add a TARDIS back door.
    default: op
  tardis.texture:
    description: Allow players to switch texture packs.
    default: op
  tardis.temporal:
    description: Allow players to set their player time (Temporal Location).
    default: op
  tardis.prune.bypass:
    description: Ignore /tardisadmin prune [days] command to remove unused TARDISes.
    default: op
commands:
  tardis:
    aliases: [tt,ttardis,/tardis,timelord]
    description: Manipulate TARDISs (TARDII?) with various arguments (list, save, find, help, etc). Type /TARDIS help - to see more.
    chameleon:
      description: Toggle the TARDIS Chameleon Circuit on and off.
      usage: /<command> chameleon [on|off|short|reset]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    list:
      description: List saved time travel locations.
      usage: /<command> list
      permission: tardis.list
      permission-message: You don't have the permission <permission> to use this command
    save:
      description: Save the current location of the TARDIS Police Box.
      usage: /<command> save [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    setdest:
      description: Save a destination determined by the block you are looking at.
      usage: /<command> setdest [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    removesave:
      description: Delete a saved destination.
      usage: /<command> removesave [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    home:
      description: Save a time travel location as home.
      usage: /<command> home
      permission: tardis.home
      permission-message: You don't have the permission <permission> to use this command
    find:
      description: Shows you the location of your TARDIS.
      usage: /<command> find
      permission: tardis.find
      permission-message: You don't have the permission <permission> to use this command
    add:
      description: Add a companion that can travel with you in your TARDIS.
      usage: /<command> add [player name]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a companion from your TARDIS.
      usage: /<command> remove [player name|all]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    update:
      description: Modify the interior of the TARDIS.
      usage: /<command> update [door|button|world-repeater|x-repeater|z-repeater|y-repeater|chameleon|save-sign|artron|handbrake|condenser|scanner|backdoor|keyboard|creeper|eps|back|terminal|ars|temporal|light|farm|stable|rail|info]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    secondary:
      description: Set secondary TARDIS controls.
      usage: /<command> secondary [button|world-repeater|x-repeater|z-repeater|y-repeater|artron|handbrake|door]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    rebuild:
      description: Rebuild the TARDIS.
      usage: /<command> rebuild
      permission: tardis.rebuild
      permission-message: You don't have the permission <permission> to use this command
    namekey:
      description: Rename the TARDIS key Item.
      usage: Hold the key in your hand, then type /<command> namekey [new name]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    help:
      description: View TARDIS help pages.
      usage: /<command> help [command]
    comehere:
      description: Make the TARDIS come to the block you are looking at.
      usage: /<command> comehere
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    direction:
      description: Change the direction the Police Box door is facing.
      usage: /<command> direction [north|west|south|east]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    exterminate:
      description: Delete your TARDIS.
      usage: /<command> exterminate
    hide:
      description: Hide the TARDIS Police Box.
      usage: /<command> hide
      permission: tardis.rebuild
      permission-message: You don't have the permission <permission> to use this command
    inside:
      description: List players inside your TARDIS.
      usage: /<command> inside
    jettison:
      description: Remove a TARDIS room.
      usage: /<command> jettison [room type]
      permission: tardis.room
      permission-message: You don't have the permission <permission> to use this command
    occupy:
      description: Toggle TARDIS occupation.
      usage: /<command> occupy
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    rescue:
      description: Rescue a player in the TARDIS.
      usage: /<command> rescue [player]
      permission: tardis.timetravel.player
      permission-message: You don't have the permission <permission> to use this command
    room:
      description: Grow a TARDIS room.
      usage: /<command> room [room type|help]
      permission: tardis.room
      permission-message: You don't have the permission <permission> to use this command
    abort:
      description: Stop growing a TARDIS room.
      usage: /<command> abort [task ID number]
      permission: tardis.room
      permission-message: You don't have the permission <permission> to use this command
    version:
      description: Display the TARDIS plugin and CraftBukkit version.
      usage: /<command> version
    lamps:
      description: Scan the main control room for new or moved lamp blocks.
      usage: /<command> lamps
  tardistravel:
    aliases: ttravel
    description: Travel to destinations in various ways.
    usage: |
      /<command> [player] or /<command> [world x y z] or /<command> dest [name] or /<command> area [name] or /<command> biome [biome]
      Example: /<command> eccentric_nz - travel to a players location
      Example: /<command> New_new_earth -117 64 273 - travel to co-ordinates in a specific world
      Example: /<command> dest mine - travel to saved destination called 'mine'
      Example: /<command> area airport - travel to the TARDIS area called 'airport'
      Example: /<command> biome DESERT - travel to the nearest DESERT biome
    permission: tardis.timetravel
    permission-message: You don't have the permission <permission> to use this command
    home:
      description: Time travel to the TARDIS 'home' location.
      usage: /<command> home
    player:
      description: Time travel to the specified player.
      usage: /<command> [player]
    coords:
      description: Time travel to the specified coordinates.
      usage: /<command> [world x y z]
    dest:
      description: Time travel to a saved destination.
      usage: /<command> dest [save name]
    area:
      description: Time travel to a server defined TARDIS area.
      usage: /<command> area [area name]
    biome:
      description: Time travel to the closest specified biome type.
      usage: /<command> biome [biome type]
  tardisadmin:
    aliases: tadmin
    description: Set TARDIS configuration options.
    usage: /<command> [config option] [value]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
  tardisgive:
    aliases: [tgive]
    description: Give TARDIS items to a player.
    usage: /<command> [player] [item] [amount]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
  tardisroom:
    aliases: troom
    description: Set TARDIS room configuration options, and add new rooms.
    usage: /<command> add [name] or /<command> [name] [boolean|integer|string] or /<command> blocks [name|save]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
    add:
      description: Add a new custom room schematic.
      usage: /<command> add [schematic name]
    seed:
      description: Set the seed block of a custom room.
      usage: /<command> [schematic name] [material]
    cost:
      description: Set the cost of a custom room.
      usage: /<command> add [schematic name]
    offset:
      description: Set the offset of a custom room.
      usage: /<command> [schematic name] [negative amount]
    enabled:
      description: Set the custom room as active/inactive.
      usage: /<command> [schematic name] [true|false]
  tardisprefs:
    aliases: tprefs
    description: Set player preferences.
    usage: /<command> [preference] [on|off]
    permission: tardis.timetravel
    permission-message: You don't have the permission <permission> to use this command
    sfx:
      description: Toggle the TARDIS sound effects on and off.
      usage: /<command> sfx [on|off]
    quotes:
      description: Toggle the TARDIS quotes on and off.
      usage: /<command> quotes [on|off]
    platform:
      description: Toggle the TARDIS platform on and off.
      usage: /<command> platform [on|off]
    key:
      description: Set the TARDIS key item.
      usage: /<command> key [material]
    wall:
      description: Set the TARDIS room growing wall material.
      usage: /<command> wall [material]
    floor:
      description: Set the TARDIS room growing floor material.
      usage: /<command> floor [material]
    auto:
      description: Toggle the TARDIS Autonomous Homing feature on and off.
      usage: /<command> auto [on|off]
    eps:
      description: Toggle Emergency Program One on and off.
      usage: /<command> eps [on|off]
    message:
      description: Set the Emergency Program One message.
      usage: /<command> eps_message [message]
    hads:
      description: Toggle HADS on and off.
      usage: /<command> hads [on|off]
    isomorphic:
      description: Toggle isomorphic controls on and off.
      usage: /<command> isomorphic [on|off]
    lamp:
      description: Set the Police Box lamp block type.
      usage: /<command> lamp [block id]
    plain:
      description: Toggle the plain TARDIS on and off (no sign or lamp).
      usage: /<command> plain [on|off]
    submarine:
      description: Toggle submarine landings on and off.
      usage: /<command> submarine [on|off]
  tardisarea:
    aliases: tarea
    description: Set up predefined TARDIS travel areas.
    usage: /<command> [start|end|show|remove] [name]
    start:
      description: Start defining a TARDIS area.
      usage: /<command> start [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    end:
      description: Finish defining a TARDIS area.
      usage: /<command> end
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    show:
      description: Show the corners of a TARDIS area.
      usage: /<command> show [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a TARDIS area.
      usage: /<command> remove [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
  tardisbind:
    aliases: tbind
    description: Bind TARDIS commands to buttons and other controls
    permission: tardis.update
    permission-message: You don't have the permission <permission> to use this command
    save:
      description: Bind a saved location to a button.
      usage: /<command> save [save name]
    cmd:
      description: Bind the 'home', 'hide' or 'rebuild' commands to a button.
      usage: /<command> cmd [home|hide|rebuild]
    player:
      description: Bind a player location to a button.
      usage: /<command> player [player]
    area:
      description: Bind a TARDIS area to a button.
      usage: /<command> area [area name]
    biome:
      description: Bind a biome to a button.
      usage: /<command> biome [biome]
    remove:
      description: Remove a 'bound' saved location, command, player or area from a button.
      usage: /<command> remove [save name|cmd|player|area]
  tardisgravity:
    aliases: tgravity
    description: Add or remove gravity well blocks.
    usage: /<command> [up|down|north|west|south|east|remove] [distance] [velocity]
    permission: tardis.gravity
    permission-message: You don't have the permission <permission> to use this command
  tardisbook:
    aliases: tbook
    description: Get and read TARDIS books and start TARDIS achievements.
    usage: /<command> [list|get|start] [book name]
    permission: tardis.book
    permission-message: You don't have the permission <permission> to use this command
  tardistexture:
    aliases: [ttexture,ttext,ttp]
    description: Set texure pack preferences.
    usage: /<command> [on|off|in|out] [url]
    permission: tardis.texture
    permission-message: You don't have the permission <permission> to use this command
    'on':
      description: Turns texture pack switching on.
      usage: /<command> on
    'off':
      description: Turns texture pack switching off.
      usage: /<command> off
    in:
      description: Set texure pack that is switched to inside the TARDIS.
      usage: /<command> in [url]
    out:
      description: Set texure pack that is switched to in the outside world.
      usage: /<command> out [url]
  tardisrecipe:
    aliases: [trecipe, trep]
    description: View TARDIS item recipes.
    usage: /<command> [remote|locator|l-circuit|m-circuit|s-circuit|key|sonic-q|sonic-r|sonic-d|sonic-e|sonic-a]
    permission: tardis.use
    permission-message: You don't have the permission <permission> to use this command