authors: [eccentric_nz, ewized]
description: A plugin for all Doctor Who fans - create and use a TARDIS! Teleport to random destinations - it's bigger on the inside!
main: me.eccentric_nz.TARDIS.TARDIS
name: TARDIS
startup: postworld
softdepend: [Multiverse-Core,MultiWorld,WorldGuard,WorldBorder,Towny]
website: http://dev.bukkit.org/server-mods/TARDIS/
dev-url: http://dev.bukkit.org/server-mods/TARDIS/
url: http://www.thenosefairy.co.nz/
version: '2.0-beta-2'
permissions:
  tardis.admin:
    description: Allow players access to the TARDIS admin commands.
    default: op
  tardis.delete:
    description: Allow players to delete any TARDIS.
    default: false
  tardis.skeletonkey:
    description: Allow players to enter any TARDIS.
    default: false
  tardis.use:
    description: Allow players to create & delete a TARDIS, and teleport to destinations.
    children:
      tardis.create: true
      tardis.timetravel: true
      tardis.list: true
      tardis.save: true
      tardis.enter: true
      tardis.find: true
      tardis.add: true
      tardis.help: true
      tardis.update: true
      tardis.rebuild: true
    default: op
  tardis.exile:
    description: Disallow players from travelling anywhere but to areas they have a permission node for.
    default: false
  tardis.create:
    description: Allow players to create a TARDIS.
    default: op
  tardis.delete:
    description: Allow players to delete a TARDIS.
    default: op
  tardis.timetravel:
    description: Allow players to teleport to random locations and saved destinations.
    default: op
  tardis.timetravel.player:
    description: Allow players to teleport to player locations.
    default: op
  tardis.timetravel.location:
    description: Allow players to teleport to coordinates.
    default: op
  tardis.list:
    description: Allow players to list saved time travel destinations.
    default: op
  tardis.save:
    description: Allow players to save time travel destinations.
    default: op
  tardis.home:
    description: Allow players to save a time travel destination as their home.
    default: op
  tardis.enter:
    description: Allow players to enter a TARDIS.
    default: op
  tardis.find:
    description: Allow players to find their TARDIS.
    default: op
  tardis.add:
    description: Allow players to add/remove companions to their TARDIS.
    default: op
  tardis.help:
    description: Allow players to view TARDIS help pages.
    default: true
  tardis.update:
    description: Allow players to modify the TARDIS interior.
    default: true
  tardis.rebuild:
    description: Allow players to rebuild the TARDIS.
    default: true
  tardis.bigger:
    description: Allow players to build the 'bigger' TARDIS.
    default: op
  tardis.deluxe:
    description: Allow players to build the 'deluxe' TARDIS.
    default: op
  tardis.end:
    description: Allow players to time travel to the END.
    default: op
  tardis.nether:
    description: Allow players to time travel to the NETHER.
    default: op
  tardis.room:
    description: Allow players to grow extra rooms.
    default: op
commands:
  tardis:
    description: Manipulate TARDISs (TARDII?) with various arguments (list, save, find, help, etc). Type /TARDIS help - to see more.
    chameleon:
      description: Toggle the TARDIS Chameleon Circuit on and off.
      usage: /<command> chameleon [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    list:
      description: List saved time travel locations.
      usage: /<command> list
      permission: tardis.list
      permission-message: You don't have the permission <permission> to use this command
    save:
      description: Save the current location of the TARDIS Police Box.
      usage: /<command> save [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    setdest:
      description: Save a destination determined by the block you are looking at.
      usage: /<command> setdest [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    removesave:
      description: Delete a saved destination.
      usage: /<command> removesave [name]
      permission: tardis.save
      permission-message: You don't have the permission <permission> to use this command
    home:
      description: Save a time travel location as home.
      usage: /<command> home
      permission: tardis.home
      permission-message: You don't have the permission <permission> to use this command
    find:
      description: Shows you the location of your TARDIS.
      usage: /<command> find
      permission: tardis.find
      permission-message: You don't have the permission <permission> to use this command
    add:
      description: Add a companion that can travel with you in your TARDIS.
      usage: /<command> add [player name]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a companion from your TARDIS.
      usage: /<command> remove [player name]
      permission: tardis.add
      permission-message: You don't have the permission <permission> to use this command
    update:
      description: Modify the interior of the TARDIS.
      usage: /<command> update [door|button|save-repeater|x-repeater|z-repeater|y-repeater]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    rebuild:
      description: Rebuild the TARDIS.
      usage: /<command> rebuild
      permission: tardis.rebuild
      permission-message: You don't have the permission <permission> to use this command
    namekey:
      description: Rename the TARDIS key Item.
      usage: Hold the key in your hand, then type /<command> namekey [new name]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    bind:
      description: Bind a saved location or the 'home', 'hide' and 'rebuild' commands to a button.
      usage: /<command> bind [save name|home|hide|rebuild]
      permission: tardis.update
      permission-message: You don't have the permission <permission> to use this command
    reload:
      description: Reloads the TARDIS configuration.
      usage: /<command> reload
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    help:
      description: View TARDIS help pages.
      usage: /<command> help [command]
  tardistravel:
    description: Travel to destinations in various ways.
    usage: |
      /<command> [player] or /<command> [world x y z] or /<command> dest [name] or /<command> area [name]
      Example: /<command> eccentric_nz - travel to a players location
      Example: /<command> New_new_earth -117 64 273 - travel to co-ordinates in a specific world
      Example: /<command> dest mine - travel to saved destination called 'mine'
      Example: /<command> area airport - travel to the TARDIS area called 'airport'
    permission: tardis.timetravel
    permission-message: You don't have the permission <permission> to use this command
  tardisadmin:
    description: Set TARDIS configuration options.
    usage: /<command> [config option] [value]
    permission: tardis.admin
    permission-message: You don't have the permission <permission> to use this command
  tardisprefs:
    description: Set player preferences.
    usage: /<command> [preference] [on|off]
    sfx:
      description: Toggle the TARDIS sound effects on and off.
      usage: /<command> sfx [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    quotes:
      description: Toggle the TARDIS quotes on and off.
      usage: /<command> quotes [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
    platform:
      description: Toggle the TARDIS platform on and off.
      usage: /<command> platform [on|off]
      permission: tardis.timetravel
      permission-message: You don't have the permission <permission> to use this command
  tardisarea:
    description: Set up predefined TARDIS travel areas.
    usage: /<command> [start|end|show|remove] [name]
    start:
      description: Start defining a TARDIS area.
      usage: /<command> start [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    end:
      description: Finish defining a TARDIS area.
      usage: /<command> end
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    show:
      description: Show the corners of a TARDIS area.
      usage: /<command> show [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
    remove:
      description: Remove a TARDIS area.
      usage: /<command> remove [name]
      permission: tardis.admin
      permission-message: You don't have the permission <permission> to use this command
