name: Feature request
description: Suggest an idea for TARDIS
body:
  - type: textarea
    attributes:
      label: Describe the feature request
      description: A clear and concise description of what you are missing, and what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: true
