package me.eccentric_nz.TARDIS.custommodels.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum ChameleonVariant {

    GLASS(new NamespacedKey(TARDIS.plugin, "chameleon_glass")),
    BLACK_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_black_closed")),
    BLACK_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_black_open")),
    BLACK_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_black_stained")),
    BLACK_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_black_camera")),
    BLUE_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_blue_closed")),
    BLUE_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_blue_open")),
    BLUE_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_blue_stained")),
    BLUE_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_blue_camera")),
    BROWN_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_brown_closed")),
    BROWN_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_brown_open")),
    BROWN_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_brown_stained")),
    BROWN_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_brown_camera")),
    CYAN_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_cyan_closed")),
    CYAN_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_cyan_open")),
    CYAN_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_cyan_stained")),
    CYAN_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_cyan_camera")),
    GRAY_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_gray_closed")),
    GRAY_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_gray_open")),
    GRAY_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_gray_stained")),
    GRAY_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_gray_camera")),
    GREEN_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_green_closed")),
    GREEN_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_green_open")),
    GREEN_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_green_stained")),
    GREEN_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_green_camera")),
    LIGHT_BLUE_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_light_blue_closed")),
    LIGHT_BLUE_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_light_blue_open")),
    LIGHT_BLUE_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_light_blue_stained")),
    LIGHT_BLUE_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_light_bluee_camera")),
    LIGHT_GRAY_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_light_gray_closed")),
    LIGHT_GRAY_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_light_gray_open")),
    LIGHT_GRAY_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_light_gray_stained")),
    LIGHT_GRAY_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_light_gray_camera")),
    LIME_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_lime_closed")),
    LIME_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_lime_open")),
    LIME_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_lime_stained")),
    LIME_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_lime_camera")),
    MAGENTA_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_magenta_closed")),
    MAGENTA_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_magenta_open")),
    MAGENTA_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_magenta_stained")),
    MAGENTA_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_magenta_camera")),
    ORANGE_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_orange_closed")),
    ORANGE_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_orange_open")),
    ORANGE_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_orange_stained")),
    ORANGE_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_orange_camera")),
    PINK_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_pink_closed")),
    PINK_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_pink_open")),
    PINK_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_pink_stained")),
    PINK_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_pink_camera")),
    PURPLE_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_purple_closed")),
    PURPLE_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_purple_open")),
    PURPLE_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_purple_stained")),
    PURPLE_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_purple_camera")),
    RED_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_red_closed")),
    RED_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_red_open")),
    RED_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_red_stained")),
    RED_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_red_camera")),
    WHITE_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_white_closed")),
    WHITE_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_white_open")),
    WHITE_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_white_stained")),
    WHITE_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_white_camera")),
    YELLOW_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_yellow_closed")),
    YELLOW_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_yellow_open")),
    YELLOW_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_yellow_stained")),
    YELLOW_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_yellow_camera")),
    TENNANT_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_tennant_closed")),
    TENNANT_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_tennant_open")),
    TENNANT_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_tennant_stained")),
    TENNANT_GLASS(new NamespacedKey(TARDIS.plugin, "chameleon_glass")),
    TENNANT_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_tennant_camera")),
    BAD_WOLF_CLOSED(new NamespacedKey(TARDIS.plugin, "chameleon_bad_wolf_closed")),
    BAD_WOLF_OPEN(new NamespacedKey(TARDIS.plugin, "chameleon_bad_wolf_open")),
    BAD_WOLF_STAINED(new NamespacedKey(TARDIS.plugin, "chameleon_blue_stained")),
    BAD_WOLF_SGLASS(new NamespacedKey(TARDIS.plugin, "chameleon_glass")),
    BAD_WOLF_CAMERA(new NamespacedKey(TARDIS.plugin, "chameleon_bad_wolf_camera")),
    TYPE_40_CLOSED(new NamespacedKey(TARDIS.plugin, "type_40_closed")),
    TYPE_40_OPEN(new NamespacedKey(TARDIS.plugin, "type_40_open")),
    TYPE_40_STAINED(new NamespacedKey(TARDIS.plugin, "type_40_stained")),
    TYPE_40_GLASS(new NamespacedKey(TARDIS.plugin, "type_40_glass")),
    TYPE_40_CAMERA(new NamespacedKey(TARDIS.plugin, "type_40_camera")),
    PANDORICA_CLOSED(new NamespacedKey(TARDIS.plugin, "pandorica_closed")),
    PANDORICA_OPEN(new NamespacedKey(TARDIS.plugin, "pandorica_open")),
    PANDORICA_STAINED(new NamespacedKey(TARDIS.plugin, "pandorica_stained")),
    PANDORICA_GLASS(new NamespacedKey(TARDIS.plugin, "pandorica_glass")),
    PANDORICA_75(new NamespacedKey(TARDIS.plugin, "pandorica_75")),
    PANDORICA_50(new NamespacedKey(TARDIS.plugin, "pandorica_50")),
    PANDORICA_25(new NamespacedKey(TARDIS.plugin, "pandorica_25")),
    PANDORICA_CAMERA(new NamespacedKey(TARDIS.plugin, "pandorica_camera")),
    WEEPING_ANGEL_CLOSED(new NamespacedKey(TARDIS.plugin, "weeping_angel_closed")),
    WEEPING_ANGEL_OPEN(new NamespacedKey(TARDIS.plugin, "weeping_angel_open")),
    WEEPING_ANGEL_STAINED(new NamespacedKey(TARDIS.plugin, "weeping_angel_stained")),
    WEEPING_ANGEL_GLASS(new NamespacedKey(TARDIS.plugin, "weeping_angel_glass"));

    private final NamespacedKey key;

    ChameleonVariant(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
