/*
 * Copyright (C) 2025 eccentric_nz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package me.eccentric_nz.tardisshop;

import me.eccentric_nz.TARDIS.custommodels.keys.*;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;

import java.util.List;

public enum ShopItem {

    ACID_BATTERY("Acid Battery", Material.NETHER_BRICK, Whoniverse.ACID_BATTERY.getKey()),
    ANCIENT_SEED("Ancient Seed", Material.SCULK, SeedBlock.ANCIENT.getKey(), ShopItemRecipe.SEED),
    APPLE_JELLY_BABY("Apple Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_GREEN.getKey()),
    ARS_SEED("ARS Seed", Material.QUARTZ_BLOCK, SeedBlock.ARS.getKey(), ShopItemRecipe.SEED),
    ARTRON_CAPACITOR("Artron Capacitor", Material.BUCKET, Whoniverse.ARTRON_CAPACITOR.getKey()),
    ARTRON_CAPACITOR_DAMAGED("Damaged Artron Capacitor", Material.BUCKET, Whoniverse.ARTRON_CAPACITOR_DAMAGED.getKey()),
    ARTRON_CAPACITOR_STORAGE("Artron Capacitor Storage", Material.GRAY_SHULKER_BOX, Whoniverse.EYE_STORAGE.getKey()),
    ARTRON_STORAGE_CELL("Artron Storage Cell", Material.BUCKET, Whoniverse.ARTRON_BATTERY.getKey()),
    AUTHORISED_CONTROL_DISK("Authorised Control Disk", Material.MUSIC_DISC_FAR, DiskVariant.CONTROL_DISK.getKey()),
    BIGGER_SEED("Bigger Seed", Material.GOLD_BLOCK, SeedBlock.BIGGER.getKey(), ShopItemRecipe.SEED),
    BIO_SCANNER_CIRCUIT("Bio-scanner Circuit", Material.GLOWSTONE_DUST, CircuitVariant.BIO.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.BIO.getFloats()),
    BIOME_STORAGE_DISK("Biome Storage Disk", Material.MUSIC_DISC_CAT, DiskVariant.BIOME_DISK.getKey(), ShopItemRecipe.SHAPELESS),
    BLACK_BOW_TIE("Black Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_BLACK.getKey()),
    BLANK_STORAGE_DISK("Blank Storage Disk", Material.MUSIC_DISC_STRAD, DiskVariant.BLANK_DISK.getKey()),
    BLUE_BOW_TIE("Blue Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_BLUE.getKey()),
    BLUEBERRY_JELLY_BABY("Blueberry Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_BLUE.getKey(), ShopItemRecipe.SHAPELESS),
    BONE_SEED("Bone Seed", Material.WAXED_OXIDIZED_CUT_COPPER, SeedBlock.BONE.getKey(), ShopItemRecipe.SEED),
    BOWL_OF_CUSTARD("Bowl of Custard", Material.MUSHROOM_STEW, Food.BOWL_OF_CUSTARD.getKey(), ShopItemRecipe.SHAPELESS),
    BROWN_BOW_TIE("Brown Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_BROWN.getKey()),
    BRUSH_CIRCUIT("Brush Circuit", Material.GLOWSTONE_DUST, CircuitVariant.BRUSH.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.BRUSH.getFloats()),
    BUBBLEGUM_JELLY_BABY("Bubblegum Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_LIGHT_BLUE.getKey(), ShopItemRecipe.SHAPELESS),
    BUDGET_SEED("Budget Seed", Material.IRON_BLOCK, SeedBlock.BUDGET.getKey(), ShopItemRecipe.SEED),
    CAPPUCCINO_JELLY_BABY("Cappuccino Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_BROWN.getKey(), ShopItemRecipe.SHAPELESS),
    CAVE_SEED("Cave Seed", Material.DRIPSTONE_BLOCK, SeedBlock.CAVE.getKey(), ShopItemRecipe.SEED),
    CONSOLE_LAMP_SWITCH("Console Lamp Switch", Material.LEVER, ModelledControl.CONSOLE_LAMP_0.getKey(), ShopItemRecipe.SHAPED),
    CONVERSION_CIRCUIT("Conversion Circuit", Material.GLOWSTONE_DUST, CircuitVariant.CONVERSION.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.CONVERSION.getFloats()),
    COPPER_SEED("Copper Seed", Material.COPPER_BLOCK, SeedBlock.COPPER.getKey(), ShopItemRecipe.SEED),
    CORAL_SEED("Coral Seed", Material.FIRE_CORAL_BLOCK, SeedBlock.CORAL.getKey(), ShopItemRecipe.SEED),
    CURSED_SEED("Cursed Seed", Material.BLACK_CONCRETE, SeedBlock.CURSED.getKey(), ShopItemRecipe.SEED),
    CUSTARD_CREAM("Custard Cream", Material.COOKIE, Food.CUSTARD_CREAM.getKey()),
    CYAN_BOW_TIE("Cyan Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_CYAN.getKey()),
    CYBERMAN_HEAD("Cyberman Head", Material.IRON_INGOT, CybermanVariant.CYBERMAN_HEAD.getKey(), ShopItemRecipe.TWA),
    DALEK_HEAD("Dalek Head", Material.SLIME_BALL, DalekVariant.DALEK_HEAD.getKey(), ShopItemRecipe.TWA),
    DALEK_SEC_HEAD("Dalek Sec Head", Material.MANGROVE_PROPAGULE, DalekSecVariant.DALEK_SEC_HEAD.getKey(), ShopItemRecipe.TWA),
    DAVROS_HEAD("Davros Head", Material.CRIMSON_BUTTON, DavrosVariant.DAVROS_HEAD.getKey(), ShopItemRecipe.TWA),
    DELTA_SEED("Delta Seed", Material.CRYING_OBSIDIAN, SeedBlock.DELTA.getKey(), ShopItemRecipe.SEED),
    DELUXE_SEED("Deluxe Seed", Material.DIAMOND_BLOCK, SeedBlock.DELUXE.getKey(), ShopItemRecipe.SEED),
    DIAMOND_DISRUPTOR_CIRCUIT("Diamond Disruptor Circuit", Material.GLOWSTONE_DUST, CircuitVariant.DIAMOND.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.DIAMOND.getFloats()),
    DIVISION_SEED("Division Seed", Material.PINK_GLAZED_TERRACOTTA, SeedBlock.DIVISION.getKey(), ShopItemRecipe.SEED),
    EARL_GREY_JELLY_BABY("Earl Grey Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_GRAY.getKey(), ShopItemRecipe.SHAPELESS),
    ELEVENTH_SEED("Eleventh Seed", Material.EMERALD_BLOCK, SeedBlock.ELEVENTH.getKey(), ShopItemRecipe.SEED),
    EMERALD_ENVIRONMENT_CIRCUIT("Emerald Environment Circuit", Material.GLOWSTONE_DUST, CircuitVariant.EMERALD.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.EMERALD.getFloats()),
    EMPTY_CHILD_HEAD("Empty Child Head", Material.SUGAR, EmptyChildVariant.EMPTY_CHILD_HEAD.getKey(), ShopItemRecipe.TWA),
    ENDER_SEED("Ender Seed", Material.PURPUR_BLOCK, SeedBlock.ENDER.getKey(), ShopItemRecipe.SEED),
    EXTERIOR_LAMP_LEVEL_SWITCH("Exterior Lamp Level Switch", Material.LEVER, ModelledControl.LAMP_0.getKey(), ShopItemRecipe.SHAPED),
    FACTORY_SEED("Factory Seed", Material.GRAY_CONCRETE, SeedBlock.FACTORY.getKey(), ShopItemRecipe.SEED),
    FIFTEENTH_SEED("Fifteenth Seed", Material.OCHRE_FROGLIGHT, SeedBlock.FIFTEENTH.getKey(), ShopItemRecipe.SEED),
    FUGITIVE_SEED("Fugitive Seed", Material.POLISHED_DEEPSLATE, SeedBlock.FUGITIVE.getKey(), ShopItemRecipe.SEED),
    FISH_FINGER("Fish Finger", Material.COOKED_COD, Food.FISH_FINGER.getKey()),
    FOB_WATCH("Fob Watch", Material.CLOCK, Whoniverse.FOB_WATCH.getKey()),
    GRAPE_JELLY_BABY("Grape Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_PURPLE.getKey(), ShopItemRecipe.SHAPELESS),
    GREEN_BOW_TIE("Green Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_GREEN.getKey()),
    GREY_BOW_TIE("Grey Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_GRAY.getKey()),
    HANDLES("Handles", Material.BIRCH_BUTTON, Whoniverse.HANDLES_OFF.getKey()),
    HATH_HEAD("Hath Head", Material.PUFFERFISH, HathVariant.HATH_HEAD.getKey(), ShopItemRecipe.TWA),
    HEADLESS_MONK_HEAD("Headless Monk Head", Material.RED_CANDLE, MonkVariant.HEADLESS_MONK_HEAD.getKey(), ShopItemRecipe.TWA),
    HEAVENLY_HOST_HEAD("Heavenly Host Head", Material.GOLD_INGOT, HeavenlyHostVariant.HEAVENLY_HOST_HEAD.getKey(), ShopItemRecipe.TWA),
    HOSPITAL_SEED("Hospital Seed", Material.WHITE_CONCRETE, SeedBlock.HOSPITAL.getKey(), ShopItemRecipe.SEED),
    ICE_WARRIOR_HEAD("Ice Warrior Head", Material.SNOWBALL, IceWarriorVariant.ICE_WARRIOR_HEAD.getKey(), ShopItemRecipe.TWA),
    IGNITE_CIRCUIT("Ignite Circuit", Material.GLOWSTONE_DUST, CircuitVariant.IGNITE.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.IGNITE.getFloats()),
    INTERIOR_LIGHT_LEVEL_SWITCH("Interior Light Level Switch", Material.LEVER, ModelledControl.LIGHT_0.getKey(), ShopItemRecipe.SHAPED),
    ISLAND_PUNCH_JELLY_BABY("Island Punch Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_CYAN.getKey(), ShopItemRecipe.SHAPELESS),
    JAMMY_DODGER("Jammy Dodger", Material.COOKIE, Food.JAMMY_DODGER.getKey()),
    JUDOON_HEAD("Judoon Head", Material.YELLOW_DYE, JudoonVariant.JUDOON_HEAD.getKey(), ShopItemRecipe.TWA),
    K9("K9", Material.BONE, K9Variant.K9.getKey(), ShopItemRecipe.TWA),
    KNOCKBACK_CIRCUIT("Knockback Circuit", Material.GLOWSTONE_DUST, CircuitVariant.KNOCKBACK.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.KNOCKBACK.getFloats()),
    LEGACY_BIGGER_SEED("Legacy Bigger Seed", Material.ORANGE_GLAZED_TERRACOTTA, SeedBlock.LEGACY_BIGGER.getKey(), ShopItemRecipe.SEED),
    LEGACY_DELUXE_SEED("Legacy Deluxe Seed", Material.LIME_GLAZED_TERRACOTTA, SeedBlock.LEGACY_DELUXE.getKey(), ShopItemRecipe.SEED),
    LEGACY_ELEVENTH_SEED("Legacy Eleventh Seed", Material.CYAN_GLAZED_TERRACOTTA, SeedBlock.LEGACY_ELEVENTH.getKey(), ShopItemRecipe.SEED),
    LEGACY_REDSTONE_SEED("Legacy Redstone Seed", Material.RED_GLAZED_TERRACOTTA, SeedBlock.LEGACY_REDSTONE.getKey(), ShopItemRecipe.SEED),
    LEMON_JELLY_BABY("Lemon Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_YELLOW.getKey(), ShopItemRecipe.SHAPELESS),
    LICORICE_JELLY_BABY("Licorice Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_BLACK.getKey(), ShopItemRecipe.SHAPELESS),
    LIGHT_BLUE_BOW_TIE("Light Blue Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_LIGHT_BLUE.getKey()),
    LIGHT_GREY_BOW_TIE("Light Grey Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_LIGHT_GRAY.getKey()),
    LIME_BOW_TIE("Lime Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_LIME.getKey()),
    LIME_JELLY_BABY("Lime Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_LIME.getKey(), ShopItemRecipe.SHAPELESS),
    MAGENTA_BOW_TIE("Magenta Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_MAGENTA.getKey()),
    MASTER_SEED("Master Seed", Material.NETHER_BRICKS, SeedBlock.MASTER.getKey(), ShopItemRecipe.SEED),
    MECHANICAL_SEED("Mechanical Seed", Material.POLISHED_ANDESITE, SeedBlock.MECHANICAL.getKey(), ShopItemRecipe.SEED),
    MIRE_HEAD("Mire Head", Material.NETHERITE_SCRAP, MireVariant.THE_MIRE_HEAD.getKey(), ShopItemRecipe.TWA),
    NIMON_HEAD("Ood Head", Material.BEEF, NimonVariant.NIMON_HEAD.getKey(), ShopItemRecipe.TWA),
    OOD_HEAD("Ood Head", Material.ROTTEN_FLESH, OodVariant.OOD_HEAD.getKey(), ShopItemRecipe.TWA),
    ORANGE_BOW_TIE("Orange Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_ORANGE.getKey()),
    ORANGE_JELLY_BABY("Orange Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_ORANGE.getKey(), ShopItemRecipe.SHAPELESS),
    ORIGINAL_SEED("Original Seed", Material.PACKED_MUD, SeedBlock.ORIGINAL.getKey(), ShopItemRecipe.SEED),
    PAINTER_CIRCUIT("Painter Circuit", Material.GLOWSTONE_DUST, CircuitVariant.PAINTER.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.PAINTER.getFloats()),
    PAPER_BAG("Paper Bag", Material.PAPER, Food.PAPER_BAG.getKey()),
    PERCEPTION_CIRCUIT("Perception Circuit", Material.GLOWSTONE_DUST, CircuitVariant.PERCEPTION.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.PERCEPTION.getFloats()),
    PERCEPTION_FILTER("Perception Filter", Material.GOLD_NUGGET, KeyVariant.PERCEPTION_FILTER.getKey(), ShopItemRecipe.SHAPED, KeyVariant.PERCEPTION_FILTER.getFloats()),
    PICKUP_ARROWS_CIRCUIT("Pickup Arrows Circuit", Material.GLOWSTONE_DUST, CircuitVariant.PICKUP.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.PICKUP.getFloats()),
    PINK_BOW_TIE("Pink Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_PINK.getKey()),
    PLANK_SEED("Plank Seed", Material.OAK_PLANKS, SeedBlock.PLANK.getKey(), ShopItemRecipe.SEED),
    PLAYER_STORAGE_DISK("Player Storage Disk", Material.MUSIC_DISC_WAIT, DiskVariant.PLAYER_DISK.getKey(), ShopItemRecipe.SHAPELESS),
    PRESET_STORAGE_DISK("Preset Storage Disk", Material.MUSIC_DISC_MALL, DiskVariant.PRESET_DISK.getKey(), ShopItemRecipe.SHAPELESS),
    PURPLE_BOW_TIE("Purple Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_PURPLE.getKey()),
    PYRAMID_SEED("Pyramid Seed", Material.SANDSTONE, SeedBlock.PYRAMID.getKey(), ShopItemRecipe.SEED),
    RACNOSS_HEAD("Racnoss Head", Material.SPIDER_EYE, RacnossVariant.RACNOSS_HEAD.getKey(), ShopItemRecipe.TWA),
    RASPBERRY_JELLY_BABY("Raspberry Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_RED.getKey(), ShopItemRecipe.SHAPELESS),
    RED_BOW_TIE("Red Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_RED.getKey()),
    REDSTONE_ACTIVATOR_CIRCUIT("Redstone Activator Circuit", Material.GLOWSTONE_DUST, CircuitVariant.REDSTONE.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.REDSTONE.getFloats()),
    REDSTONE_SEED("Redstone Seed", Material.REDSTONE_BLOCK, SeedBlock.REDSTONE.getKey(), ShopItemRecipe.SEED),
    RIFT_CIRCUIT("Rift Circuit", Material.GLOWSTONE_DUST, CircuitVariant.RIFT.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.RIFT.getFloats()),
    RIFT_MANIPULATOR("Rift Manipulator", Material.BEACON, null),
    ROTOR_SEED("Rotor Seed", Material.HONEYCOMB_BLOCK, SeedBlock.ROTOR.getKey(), ShopItemRecipe.SEED),
    RUSTIC_SEED("Rustic Seed", Material.COPPER_BULB, SeedBlock.RUSTIC.getKey(), ShopItemRecipe.SEED),
    RUST_PLAGUE_SWORD("Rust Plague Sword", Material.IRON_SWORD, Whoniverse.RUST_PLAGUE_SWORD.getKey()),
    SAVE_STORAGE_DISK("Save Storage Disk", Material.MUSIC_DISC_CHIRP, DiskVariant.SAVE_DISK.getKey(), ShopItemRecipe.SHAPELESS),
    SERVER_ADMIN_CIRCUIT("Server Admin Circuit", Material.GLOWSTONE_DUST, CircuitVariant.ADMIN.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.ADMIN.getFloats()),
    SEA_DEVIL_HEAD("Sea Devil Head", Material.KELP, SeaDevilVariant.SEA_DEVIL_HEAD.getKey(), ShopItemRecipe.TWA),
    SIDRAT_SEED("SIDRAT Seed", Material.GREEN_CONCRETE, SeedBlock.SIDRAT.getKey(), ShopItemRecipe.SEED),
    SILENT_HEAD("Silent Head", Material.END_STONE, SilentVariant.SILENT_HEAD.getKey(), ShopItemRecipe.TWA),
    SILURIAN_HEAD("Silurian Head", Material.FEATHER, SilurianVariant.SILURIAN_HEAD.getKey(), ShopItemRecipe.TWA),
    SLITHEEN_HEAD("Slitheen Head", Material.TURTLE_EGG, SlitheenVariant.SLITHEEN_HEAD.getKey(), ShopItemRecipe.TWA),
    SONIC_GENERATOR("Sonic Generator", Material.FLOWER_POT, SonicItem.SONIC_GENERATOR.getKey()),
    SONIC_OSCILLATOR("Sonic Oscillator", Material.GLOWSTONE_DUST, CircuitVariant.SONIC.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.SONIC.getFloats()),
    SONIC_SCREWDRIVER("Sonic Screwdriver", Material.BLAZE_ROD, SonicVariant.ELEVENTH.getKey(), ShopItemRecipe.SHAPED, SonicVariant.ELEVENTH.getFloats()),
    SONTARAN_HEAD("Sontaran Head", Material.POTATO, SontaranVariant.SONTARAN_HEAD.getKey(), ShopItemRecipe.TWA),
    STATTENHEIM_REMOTE("Stattenheim Remote", Material.FLINT, Whoniverse.STATTENHEIM_REMOTE.getKey()),
    STEAMPUNK_SEED("Steampunk Seed", Material.COAL_BLOCK, SeedBlock.STEAMPUNK.getKey(), ShopItemRecipe.SEED),
    STRAWBERRY_JELLY_BABY("Strawberry Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_PINK.getKey(), ShopItemRecipe.SHAPELESS),
    STRAX_HEAD("Strax Head", Material.POTATO, StraxVariant.STRAX_HEAD.getKey(), ShopItemRecipe.TWA),
    TARDIS_ARS_CIRCUIT("TARDIS ARS Circuit", Material.GLOWSTONE_DUST, CircuitVariant.ARS.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.ARS.getFloats()),
    TARDIS_ARTRON_FURNACE("TARDIS Artron Furnace", Material.FURNACE, Whoniverse.ARTRON_FURNACE.getKey()),
    TARDIS_BIOME_READER("TARDIS Biome Reader", Material.BRICK, Whoniverse.BIOME_READER.getKey()),
    TARDIS_CHAMELEON_CIRCUIT("TARDIS Chameleon Circuit", Material.GLOWSTONE_DUST, CircuitVariant.CHAMELEON.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.CHAMELEON.getFloats()),
    TARDIS_COMMUNICATOR("TARDIS Communicator", Material.BIRCH_BUTTON, Whoniverse.COMMUNICATOR.getKey()),
    TARDIS_INPUT_CIRCUIT("TARDIS Input Circuit", Material.GLOWSTONE_DUST, CircuitVariant.INPUT.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.INPUT.getFloats()),
    TARDIS_INVISIBILITY_CIRCUIT("TARDIS Invisibility Circuit", Material.GLOWSTONE_DUST, CircuitVariant.INVISIBILITY.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.INVISIBILITY.getFloats()),
    TARDIS_KEY("TARDIS Key", Material.GOLD_NUGGET, KeyVariant.BRASS_YALE.getKey(), ShopItemRecipe.SHAPED, KeyVariant.BRASS_YALE.getFloats()),
    TARDIS_KEYBOARD_EDITOR("TARDIS Keyboard Editor", Material.OAK_SIGN, null),
    TARDIS_LOCATOR("TARDIS Locator", Material.COMPASS, Whoniverse.LOCATOR.getKey()),
    TARDIS_LOCATOR_CIRCUIT("TARDIS Locator Circuit", Material.GLOWSTONE_DUST, CircuitVariant.LOCATOR.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.LOCATOR.getFloats()),
    TARDIS_MATERIALISATION_CIRCUIT("TARDIS Materialisation Circuit", Material.GLOWSTONE_DUST, CircuitVariant.MATERIALISATION.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.MATERIALISATION.getFloats()),
    TARDIS_MEMORY_CIRCUIT("TARDIS Memory Circuit", Material.GLOWSTONE_DUST, CircuitVariant.MEMORY.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.MEMORY.getFloats()),
    TARDIS_RANDOMISER_CIRCUIT("TARDIS Randomiser Circuit", Material.GLOWSTONE_DUST, CircuitVariant.RANDOM.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.RANDOM.getFloats()),
    TARDIS_REMOTE_KEY("TARDIS Remote Key", Material.GOLD_NUGGET, KeyVariant.REMOTE.getKey(), ShopItemRecipe.SHAPED, KeyVariant.REMOTE.getFloats()),
    TARDIS_SCANNER_CIRCUIT("TARDIS Scanner Circuit", Material.GLOWSTONE_DUST, CircuitVariant.SCANNER.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.SCANNER.getFloats()),
    TARDIS_SPACE_HELMET("TARDIS Space Helmet", Material.GLASS, Whoniverse.HELMET.getKey()),
    TARDIS_STATTENHEIM_CIRCUIT("TARDIS Stattenheim Circuit", Material.GLOWSTONE_DUST, CircuitVariant.STATTENHEIM.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.STATTENHEIM.getFloats()),
    TARDIS_TELEPATHIC_CIRCUIT("TARDIS Telepathic Circuit", Material.GLOWSTONE_DUST, CircuitVariant.TELEPATHIC.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.TELEPATHIC.getFloats()),
    TARDIS_TELEVISION("TARDIS Television", Material.GLASS, Whoniverse.TV.getKey()),
    TARDIS_TEMPORAL_CIRCUIT("TARDIS Temporal Circuit", Material.GLOWSTONE_DUST, CircuitVariant.TEMPORAL.getKey(), ShopItemRecipe.SHAPED, CircuitVariant.TEMPORAL.getFloats()),
    THIRTEENTH_SEED("Thirteenth Seed", Material.HORN_CORAL_BLOCK, SeedBlock.THIRTEENTH.getKey(), ShopItemRecipe.SEED),
    THREE_D_GLASSES("3-D Glasses", Material.LEATHER_HELMET, Whoniverse.THREE_D_GLASSES.getKey()),
    TIME_ROTOR_DELTA("Time Rotor Delta", Material.LIGHT_GRAY_DYE, RotorVariant.TIME_ROTOR_DELTA_OFF.getKey(), ShopItemRecipe.MODELLED),
    TIME_ROTOR_EARLY("Time Rotor Early", Material.LIGHT_GRAY_DYE, RotorVariant.TIME_ROTOR_EARLY_OFF.getKey(), ShopItemRecipe.MODELLED),
    TIME_ROTOR_ELEVENTH("Time Rotor Eleventh", Material.LIGHT_GRAY_DYE, RotorVariant.TIME_ROTOR_ELEVENTH_OFF.getKey(), ShopItemRecipe.MODELLED),
    TIME_ROTOR_ENGINE("Time Rotor Engine", Material.LIGHT_GRAY_DYE, RotorVariant.ENGINE_ROTOR_OFF.getKey(), ShopItemRecipe.MODELLED),
    TIME_ROTOR_HOSPITAL("Time Rotor Hospital", Material.LIGHT_GRAY_DYE, RotorVariant.HOSPITAL_OFF.getKey(), ShopItemRecipe.MODELLED),
    TIME_ROTOR_TENTH("Time Rotor Tenth", Material.LIGHT_GRAY_DYE, RotorVariant.TIME_ROTOR_TENNANT_OFF.getKey(), ShopItemRecipe.MODELLED),
    TIME_ROTOR_TWELFTH("Time Rotor Twelfth", Material.LIGHT_GRAY_DYE, RotorVariant.TIME_ROTOR_TWELFTH_OFF.getKey(), ShopItemRecipe.MODELLED),
    TOM_SEED("Tom Seed", Material.LAPIS_BLOCK, SeedBlock.TOM.getKey(), ShopItemRecipe.SEED),
    TWELFTH_SEED("Twelfth Seed", Material.PRISMARINE, SeedBlock.TWELFTH.getKey(), ShopItemRecipe.SEED),
    VANILLA_JELLY_BABY("Vanilla Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_WHITE.getKey(), ShopItemRecipe.SHAPELESS),
    VASHTA_NERADA_HEAD("Vashta Nerada Head", Material.BOOK, VashtaNeradaVariant.VASHTA_NERADA_HEAD.getKey(), ShopItemRecipe.TWA),
    VODKA_JELLY_BABY("Vodka Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_LIGHT_GRAY.getKey(), ShopItemRecipe.SHAPELESS),
    WAR_SEED("War Seed", Material.WHITE_TERRACOTTA, SeedBlock.WAR.getKey(), ShopItemRecipe.SEED),
    WEATHERED_SEED("Weathered Seed", Material.WEATHERED_COPPER, SeedBlock.WEATHERED.getKey(), ShopItemRecipe.SEED),
    WATERMELON_JELLY_BABY("Watermelon Jelly Baby", Material.MELON_SLICE, JellyBabyVariant.JELLY_BABY_MAGENTA.getKey(), ShopItemRecipe.SHAPELESS),
    WEEPING_ANGEL_HEAD("Weeping Angel Head", Material.BRICK, WeepingAngelVariant.WEEPING_ANGEL_HEAD.getKey(), ShopItemRecipe.TWA),
    WHITE_BOW_TIE("White Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_WHITE.getKey()),
    YELLOW_BOW_TIE("Yellow Bow Tie", Material.LEATHER_HELMET, BowTieVariant.BOWTIE_YELLOW.getKey()),
    ZYGON_HEAD("Zygon Head", Material.PAINTING, ZygonVariant.ZYGON_HEAD.getKey(), ShopItemRecipe.TWA),
    // blueprints
    BLUEPRINT_BASE_ADD("Blueprint Add", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_BOOK("Blueprint Book", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_DELETE("Blueprint Delete", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_ENTER("Blueprint Enter", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_EXTERMINATE("Blueprint Exterminate", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_FIND("Blueprint Find", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_HOME("Blueprint Home", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_LIST("Blueprint List", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_REBUILD("Blueprint Rebuild", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_SAVE("Blueprint Save", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_TAG("Blueprint Tag", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_TIMETRAVEL("Blueprint Timetravel", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_UPDATE("Blueprint Update", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_BASE_USE("Blueprint Use", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_ANCIENT("Blueprint Ancient", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_ARS("Blueprint Ars", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_BIGGER("Blueprint Bigger", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_BONE("Blueprint Bone", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_CAVE("Blueprint Cave", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_COPPER("Blueprint Copper", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_CORAL("Blueprint Coral", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_CURSED("Blueprint Cursed", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_CUSTOM("Blueprint Custom", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_DELTA("Blueprint Delta", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_DELUXE("Blueprint Deluxe", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_DIVISION("Blueprint Division", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_ELEVENTH("Blueprint Eleventh", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_ENDER("Blueprint Ender", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_FACTORY("Blueprint Factory", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_FIFTEENTH("Blueprint Fifteenth", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_FUGITIVE("Blueprint Fugutive", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_HOSPITAL("Blueprint Hospital", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_LEGACY_BIGGER("Blueprint Legacy Bigger", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_LEGACY_DELUXE("Blueprint Legacy Deluxe", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_LEGACY_ELEVENTH("Blueprint Legacy Eleventh", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_LEGACY_REDSTONE("Blueprint Legacy Redstone", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_MASTER("Blueprint Master", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_MECHANICAL("Blueprint Mechanical", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_ORIGINAL("Blueprint Original", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_PLANK("Blueprint Plank", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_PYRAMID("Blueprint Pyramid", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_REDSTONE("Blueprint Redstone", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_ROTOR("Blueprint Rotor", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_SIDRAT("Blueprint SIDRAT", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_STEAMPUNK("Blueprint Steampunk", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_TOM("Blueprint Tom", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_THIRTEENTH("Blueprint Thirteenth", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_TWELFTH("Blueprint Twelfth", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_WAR("Blueprint War", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_CONSOLE_WEATHERED("Blueprint Weathered", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_ABANDON("Blueprint Abandon", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_ACID_BYPASS("Blueprint Acid Bypass", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_ADVANCED("Blueprint Advanced", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_ARCHITECTURAL("Blueprint Architectural", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_ARCHIVE("Blueprint Archive", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_ATMOSPHERIC("Blueprint Atmospheric", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_AUTONOMOUS("Blueprint Autonomous", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_BACKDOOR("Blueprint Backdoor", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_CHAMELEON_ARCH("Blueprint Chameleon Arch", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_CHEMISTRY_BREW("Blueprint Chemistry Brew", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_CHEMISTRY_COMMAND("Blueprint Chemistry Command", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_CHEMISTRY_CREATIVE("Blueprint Chemistry Creative", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_CHEMISTRY_CURE("Blueprint Chemistry Cure", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_CHEMISTRY_GLUE("Blueprint Chemistry Glue", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_COMPOUND_CREATE("Blueprint Compound Create", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_CONSTRUCT_BUILD("Blueprint Construct Build", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_DIFFICULTY("Blueprint Difficulty", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_EJECT("Blueprint Eject", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_FARM("Blueprint Farm", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_FILTER("Blueprint Filter", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_FORCEFIELD("Blueprint Forcefield", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_FORMULA_SHOW("Blueprint Formula Show", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_FURNACE("Blueprint Furnace", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_GRAVITY("Blueprint Gravity", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_HANDLES("Blueprint Handles", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_LAB_COMBINE("Blueprint Lab Combine", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_LAZARUS("Blueprint Lazarus", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_PAPER_BAG("Blueprint Paper Bag", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_REDUCER_USE("Blueprint Reducer Use", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_REMOTE("Blueprint Remote", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_REPAIR("Blueprint Repair", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_RIFT("Blueprint Rift", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_SCANNER_MAP("Blueprint Scanner Map", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_STORAGE("Blueprint Storage", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_STORE("Blueprint Store", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_TEMPORAL("Blueprint Temporal", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_TRANSLATE("Blueprint Translate", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_TRANSMAT("Blueprint Transmat", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_TWELFTH("Blueprint Twelfth", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_UPDATE("Blueprint Update", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_UPGRADE("Blueprint Upgrade", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_VAULT("Blueprint Vault", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_WEATHER_CLEAR("Blueprint Weather Clear", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_WEATHER_RAIN("Blueprint Weather Rain", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_WEATHER_THUNDER("Blueprint Weather Thunder", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_FEATURE_NONE("Blueprint None", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_ANDESITE("Blueprint Andesite", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_ANGEL("Blueprint Angel", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_APPERTURE("Blueprint Apperture", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_CAKE("Blueprint Cake", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_CANDY("Blueprint Candy", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_CHALICE("Blueprint Chalice", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_CHORUS("Blueprint Chorus", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_CREEPY("Blueprint Creepy", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_COLOURED("Blueprint Police Box Any Colour", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_CUSTOM("Blueprint Custom", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_DESERT("Blueprint Desert", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_DIORITE("Blueprint Diorite", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_DUCK("Blueprint Duck", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_FENCE("Blueprint Fence", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_FLOWER("Blueprint Flower", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_GAZEBO("Blueprint Gazebo", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_GRANITE("Blueprint Granite", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_GRAVESTONE("Blueprint Gravestone", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_HELIX("Blueprint Helix", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_JAIL("Blueprint Jail", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_JUNGLE("Blueprint Jungle", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_LAMP("Blueprint Lamp", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_LIBRARY("Blueprint Library", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_LIGHTHOUSE("Blueprint Lighthouse", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_MINESHAFT("Blueprint Mineshaft", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_NETHER("Blueprint Preset Nether", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_NEW("Blueprint New", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_OLD("Blueprint Old", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_PANDORICA("Blueprint Pandorica", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_PARTY("Blueprint Party", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_PEANUT("Blueprint Peanut", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_PINE("Blueprint Pine", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_BLACK("Blueprint Police Box Black", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_BLUE("Blueprint Police Box Blue", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_BROWN("Blueprint Police Box Brown", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_CYAN("Blueprint Police Box Cyan", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_GRAY("Blueprint Police Box Gray", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_GREEN("Blueprint Police Box Green", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_LIGHT_BLUE("Blueprint Police Box Light Blue", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_LIGHT_GRAY("Blueprint Police Box Light Gray", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_LIME("Blueprint Police Box Lime", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_MAGENTA("Blueprint Police Box Magenta", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_ORANGE("Blueprint Police Box Orange", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_PINK("Blueprint Police Box Pink", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_PURPLE("Blueprint Police Box Purple", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_RED("Blueprint Police Box Red", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_TENNANT("Blueprint Police Box Tennant", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_WHITE("Blueprint Police Box White", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_POLICE_BOX_YELLOW("Blueprint Police Box Yellow", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_PORTAL("Blueprint Portal", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_PRISMARINE("Blueprint Prismarine", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_PUNKED("Blueprint Punked", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_ROBOT("Blueprint Robot", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_SHROOM("Blueprint Shroom", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_SIDRAT("Blueprint SIDRAT", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_SNOWMAN("Blueprint Snowman", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_STONE("Blueprint Stone", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_SUBMERGED("Blueprint Submerged", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_SWAMP("Blueprint Swamp", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_TELEPHONE("Blueprint Telephone", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_TOILET("Blueprint Toilet", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_TOPSYTURVEY("Blueprint Topsyturvey", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_TORCH("Blueprint Torch", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_VILLAGE("Blueprint Village", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_WELL("Blueprint Well", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_WINDMILL("Blueprint Windmill", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_PRESET_YELLOW("Blueprint Yellow", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_ALLAY("Blueprint Allay", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_ANTIGRAVITY("Blueprint Antigravity", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_APIARY("Blueprint Apiary", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_AQUARIUM("Blueprint Aquarium", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_ARBORETUM("Blueprint Arboretum", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_ARCHITECTURAL("Blueprint Architectural", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_BAKER("Blueprint Baker", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_BAMBOO("Blueprint Bamboo", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_BEDROOM("Blueprint Bedroom", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_BIRDCAGE("Blueprint Birdcage", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_CHEMISTRY("Blueprint Chemistry", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_EMPTY("Blueprint Empty", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_EYE("Blueprint Eye", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_FARM("Blueprint Farm", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_GEODE("Blueprint Geode", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_GRAVITY("Blueprint Gravity", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_GREENHOUSE("Blueprint Greenhouse", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_HARMONY("Blueprint Harmony", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_HUTCH("Blueprint Hutch", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_IGLOO("Blueprint Igloo", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_IISTUBIL("Blueprint Iistubil", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_JETTISON("Blueprint Jettison", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_KITCHEN("Blueprint Kitchen", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_LAVA("Blueprint Lava", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_LAZARUS("Blueprint Lazarus", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_LIBRARY("Blueprint Library", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_MANGROVE("Blueprint Mangrove", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_MAZE("Blueprint Maze", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_MUSHROOM("Blueprint Mushroom", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_NETHER("Blueprint Nether", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_PASSAGE("Blueprint Passage", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_PEN("Blueprint Pen", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_POOL("Blueprint Pool", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_RAIL("Blueprint Rail", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_RENDERER("Blueprint Renderer", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_SHELL("Blueprint Shell", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_SMELTER("Blueprint Smelter", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_STABLE("Blueprint Stable", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_STALL("Blueprint Stall", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_TRENZALORE("Blueprint Trenzalore", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_VAULT("Blueprint Vault", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_VILLAGE("Blueprint Village", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_WOOD("Blueprint Wood", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_WORKSHOP("Blueprint Workshop", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_ROOM_ZERO("Blueprint Zero", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_ARROW("Blueprint Arrow", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_BIO("Blueprint Bio", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_BRUSH("Blueprint Brush", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_CONVERSION("Blueprint Conversion", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_DIAMOND("Blueprint Diamond", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_EMERALD("Blueprint Emerald", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_FREEZE("Blueprint Freeze", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_IGNITE("Blueprint Ignite", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_KNOCKBACK("Blueprint Knockback", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_PAINT("Blueprint Paint", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_PLANT("Blueprint Plant", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_REDSTONE("Blueprint Redstone", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_SILKTOUCH("Blueprint Silktouch", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_SORT("Blueprint Sort", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_SONIC_STANDARD("Blueprint Standard", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_TRAVEL_BIOME("Blueprint Biome", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_TRAVEL_CAVE("Blueprint Travel Cave", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_TRAVEL_LOCATION("Blueprint Location", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_TRAVEL_NETHER("Blueprint Travel Nether", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_TRAVEL_PLAYER("Blueprint Player", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_TRAVEL_END("Blueprint End", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT),
    BLUEPRINT_TRAVEL_VILLAGE("Blueprint Village", Material.MUSIC_DISC_MELLOHI, DiskVariant.BLUEPRINT_DISK.getKey(), ShopItemRecipe.BLUEPRINT);

    private final String displayName;
    private final Material material;
    private final NamespacedKey model;
    private final ShopItemRecipe recipeType;
    private final List<Float> floats;

    ShopItem(String displayName, Material material, NamespacedKey model, ShopItemRecipe recipeType, List<Float> floats) {
        this.displayName = displayName;
        this.material = material;
        this.model = model;
        this.recipeType = recipeType;
        this.floats = floats;
    }

    ShopItem(String displayName, Material material, NamespacedKey model) {
        this.displayName = displayName;
        this.material = material;
        this.model = model;
        this.recipeType = ShopItemRecipe.SHAPED;
        this.floats = null;
    }

    ShopItem(String displayName, Material material, NamespacedKey model, ShopItemRecipe recipeType) {
        this.displayName = displayName;
        this.material = material;
        this.model = model;
        this.recipeType = recipeType;
        this.floats = null;
    }

    public String getDisplayName() {
        return displayName;
    }

    public Material getMaterial() {
        return material;
    }

    public NamespacedKey getModel() {
        return model;
    }

    public ShopItemRecipe getRecipeType() {
        return recipeType;
    }

    public List<Float> getFloats() {
        return floats;
    }
}
