package me.eccentric_nz.TARDIS.custommodeldata.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum Feather {

    SILURIAN(new NamespacedKey(TARDIS.plugin, "item/genetic/silurian")),
    SILURIAN_ARM(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/silurian_arm")),
    SILURIAN_HEAD(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/silurian_head")),
    SILURIAN_DISGUISE(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/silurian_disguise")),
    SILURIAN_CREST(new NamespacedKey(TARDIS.plugin, "item/lazarus/silurian_crest")),
    SILURIAN_0(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_0")),
    SILURIAN_1(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_1")),
    SILURIAN_2(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_2")),
    SILURIAN_3(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_3")),
    SILURIAN_4(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_4")),
    SILURIAN_STATIC(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/silurian_static")),
    SILURIAN_ATTACKING_0(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_attacking_0")),
    SILURIAN_ATTACKING_1(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_attacking_1")),
    SILURIAN_ATTACKING_2(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_attacking_2")),
    SILURIAN_ATTACKING_3(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_attacking_3")),
    SILURIAN_ATTACKING_4(new NamespacedKey(TARDIS.plugin, "item/monster/silurian/frames/silurian_attacking_4")),
    E1(new NamespacedKey(TARDIS.plugin, "item/elements/1")),
    E2(new NamespacedKey(TARDIS.plugin, "item/elements/2")),
    E3(new NamespacedKey(TARDIS.plugin, "item/elements/3")),
    E4(new NamespacedKey(TARDIS.plugin, "item/elements/4")),
    E5(new NamespacedKey(TARDIS.plugin, "item/elements/5")),
    E6(new NamespacedKey(TARDIS.plugin, "item/elements/6")),
    E7(new NamespacedKey(TARDIS.plugin, "item/elements/7")),
    E8(new NamespacedKey(TARDIS.plugin, "item/elements/8")),
    E9(new NamespacedKey(TARDIS.plugin, "item/elements/9")),
    E10(new NamespacedKey(TARDIS.plugin, "item/elements/10")),
    E11(new NamespacedKey(TARDIS.plugin, "item/elements/11")),
    E12(new NamespacedKey(TARDIS.plugin, "item/elements/12")),
    E13(new NamespacedKey(TARDIS.plugin, "item/elements/13")),
    E14(new NamespacedKey(TARDIS.plugin, "item/elements/14")),
    E15(new NamespacedKey(TARDIS.plugin, "item/elements/15")),
    E16(new NamespacedKey(TARDIS.plugin, "item/elements/16")),
    E17(new NamespacedKey(TARDIS.plugin, "item/elements/17")),
    E18(new NamespacedKey(TARDIS.plugin, "item/elements/18")),
    E19(new NamespacedKey(TARDIS.plugin, "item/elements/19")),
    E20(new NamespacedKey(TARDIS.plugin, "item/elements/20")),
    E21(new NamespacedKey(TARDIS.plugin, "item/elements/21")),
    E22(new NamespacedKey(TARDIS.plugin, "item/elements/22")),
    E23(new NamespacedKey(TARDIS.plugin, "item/elements/23")),
    E24(new NamespacedKey(TARDIS.plugin, "item/elements/24")),
    E25(new NamespacedKey(TARDIS.plugin, "item/elements/25")),
    E26(new NamespacedKey(TARDIS.plugin, "item/elements/26")),
    E27(new NamespacedKey(TARDIS.plugin, "item/elements/27")),
    E28(new NamespacedKey(TARDIS.plugin, "item/elements/28")),
    E29(new NamespacedKey(TARDIS.plugin, "item/elements/29")),
    E30(new NamespacedKey(TARDIS.plugin, "item/elements/30")),
    E31(new NamespacedKey(TARDIS.plugin, "item/elements/31")),
    E32(new NamespacedKey(TARDIS.plugin, "item/elements/32")),
    E33(new NamespacedKey(TARDIS.plugin, "item/elements/33")),
    E34(new NamespacedKey(TARDIS.plugin, "item/elements/34")),
    E35(new NamespacedKey(TARDIS.plugin, "item/elements/35")),
    E36(new NamespacedKey(TARDIS.plugin, "item/elements/36")),
    E37(new NamespacedKey(TARDIS.plugin, "item/elements/37")),
    E38(new NamespacedKey(TARDIS.plugin, "item/elements/38")),
    E39(new NamespacedKey(TARDIS.plugin, "item/elements/39")),
    E40(new NamespacedKey(TARDIS.plugin, "item/elements/40")),
    E41(new NamespacedKey(TARDIS.plugin, "item/elements/41")),
    E42(new NamespacedKey(TARDIS.plugin, "item/elements/42")),
    E43(new NamespacedKey(TARDIS.plugin, "item/elements/43")),
    E44(new NamespacedKey(TARDIS.plugin, "item/elements/44")),
    E45(new NamespacedKey(TARDIS.plugin, "item/elements/45")),
    E46(new NamespacedKey(TARDIS.plugin, "item/elements/46")),
    E47(new NamespacedKey(TARDIS.plugin, "item/elements/47")),
    E48(new NamespacedKey(TARDIS.plugin, "item/elements/48")),
    E49(new NamespacedKey(TARDIS.plugin, "item/elements/49")),
    E50(new NamespacedKey(TARDIS.plugin, "item/elements/50")),
    E51(new NamespacedKey(TARDIS.plugin, "item/elements/51")),
    E52(new NamespacedKey(TARDIS.plugin, "item/elements/52")),
    E53(new NamespacedKey(TARDIS.plugin, "item/elements/53")),
    E54(new NamespacedKey(TARDIS.plugin, "item/elements/54")),
    E55(new NamespacedKey(TARDIS.plugin, "item/elements/55")),
    E56(new NamespacedKey(TARDIS.plugin, "item/elements/56")),
    E57(new NamespacedKey(TARDIS.plugin, "item/elements/57")),
    E58(new NamespacedKey(TARDIS.plugin, "item/elements/58")),
    E59(new NamespacedKey(TARDIS.plugin, "item/elements/59")),
    E60(new NamespacedKey(TARDIS.plugin, "item/elements/60")),
    E61(new NamespacedKey(TARDIS.plugin, "item/elements/61")),
    E62(new NamespacedKey(TARDIS.plugin, "item/elements/62")),
    E63(new NamespacedKey(TARDIS.plugin, "item/elements/63")),
    E64(new NamespacedKey(TARDIS.plugin, "item/elements/64")),
    E65(new NamespacedKey(TARDIS.plugin, "item/elements/65")),
    E66(new NamespacedKey(TARDIS.plugin, "item/elements/66")),
    E67(new NamespacedKey(TARDIS.plugin, "item/elements/67")),
    E68(new NamespacedKey(TARDIS.plugin, "item/elements/68")),
    E69(new NamespacedKey(TARDIS.plugin, "item/elements/69")),
    E70(new NamespacedKey(TARDIS.plugin, "item/elements/70")),
    E71(new NamespacedKey(TARDIS.plugin, "item/elements/71")),
    E72(new NamespacedKey(TARDIS.plugin, "item/elements/72")),
    E73(new NamespacedKey(TARDIS.plugin, "item/elements/73")),
    E74(new NamespacedKey(TARDIS.plugin, "item/elements/74")),
    E75(new NamespacedKey(TARDIS.plugin, "item/elements/75")),
    E76(new NamespacedKey(TARDIS.plugin, "item/elements/76")),
    E77(new NamespacedKey(TARDIS.plugin, "item/elements/77")),
    E78(new NamespacedKey(TARDIS.plugin, "item/elements/78")),
    E79(new NamespacedKey(TARDIS.plugin, "item/elements/79")),
    E80(new NamespacedKey(TARDIS.plugin, "item/elements/80")),
    E81(new NamespacedKey(TARDIS.plugin, "item/elements/81")),
    E82(new NamespacedKey(TARDIS.plugin, "item/elements/82")),
    E83(new NamespacedKey(TARDIS.plugin, "item/elements/83")),
    E84(new NamespacedKey(TARDIS.plugin, "item/elements/84")),
    E85(new NamespacedKey(TARDIS.plugin, "item/elements/85")),
    E86(new NamespacedKey(TARDIS.plugin, "item/elements/86")),
    E87(new NamespacedKey(TARDIS.plugin, "item/elements/87")),
    E88(new NamespacedKey(TARDIS.plugin, "item/elements/88")),
    E89(new NamespacedKey(TARDIS.plugin, "item/elements/89")),
    E90(new NamespacedKey(TARDIS.plugin, "item/elements/90")),
    E91(new NamespacedKey(TARDIS.plugin, "item/elements/91")),
    E92(new NamespacedKey(TARDIS.plugin, "item/elements/92")),
    E93(new NamespacedKey(TARDIS.plugin, "item/elements/93")),
    E94(new NamespacedKey(TARDIS.plugin, "item/elements/94")),
    E95(new NamespacedKey(TARDIS.plugin, "item/elements/95")),
    E96(new NamespacedKey(TARDIS.plugin, "item/elements/96")),
    E97(new NamespacedKey(TARDIS.plugin, "item/elements/97")),
    E98(new NamespacedKey(TARDIS.plugin, "item/elements/98")),
    E99(new NamespacedKey(TARDIS.plugin, "item/elements/99")),
    E100(new NamespacedKey(TARDIS.plugin, "item/elements/100")),
    E101(new NamespacedKey(TARDIS.plugin, "item/elements/101")),
    E102(new NamespacedKey(TARDIS.plugin, "item/elements/102")),
    E103(new NamespacedKey(TARDIS.plugin, "item/elements/103")),
    E104(new NamespacedKey(TARDIS.plugin, "item/elements/104")),
    E105(new NamespacedKey(TARDIS.plugin, "item/elements/105")),
    E106(new NamespacedKey(TARDIS.plugin, "item/elements/106")),
    E107(new NamespacedKey(TARDIS.plugin, "item/elements/107")),
    E108(new NamespacedKey(TARDIS.plugin, "item/elements/108")),
    E109(new NamespacedKey(TARDIS.plugin, "item/elements/109")),
    E110(new NamespacedKey(TARDIS.plugin, "item/elements/110")),
    E111(new NamespacedKey(TARDIS.plugin, "item/elements/111")),
    E112(new NamespacedKey(TARDIS.plugin, "item/elements/112")),
    E113(new NamespacedKey(TARDIS.plugin, "item/elements/113")),
    E114(new NamespacedKey(TARDIS.plugin, "item/elements/114")),
    E115(new NamespacedKey(TARDIS.plugin, "item/elements/115")),
    E116(new NamespacedKey(TARDIS.plugin, "item/elements/116")),
    E117(new NamespacedKey(TARDIS.plugin, "item/elements/117")),
    E118(new NamespacedKey(TARDIS.plugin, "item/elements/118")),
    UNKNOWN(new NamespacedKey(TARDIS.plugin, "item/elements/unknown"));

    private final NamespacedKey key;

    Feather(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}

