package me.eccentric_nz.TARDIS.custommodeldata.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum Feather {

    SILURIAN(new NamespacedKey(TARDIS.plugin, "genetic/silurian")),
    SILURIAN_ARM(new NamespacedKey(TARDIS.plugin, "monster/silurian/silurian_arm")),
    SILURIAN_HEAD(new NamespacedKey(TARDIS.plugin, "monster/silurian/silurian_head")),
    SILURIAN_DISGUISE(new NamespacedKey(TARDIS.plugin, "monster/silurian/silurian_disguise")),
    SILURIAN_CREST(new NamespacedKey(TARDIS.plugin, "lazarus/silurian_crest")),
    SILURIAN_0(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_0")),
    SILURIAN_1(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_1")),
    SILURIAN_2(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_2")),
    SILURIAN_3(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_3")),
    SILURIAN_4(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_4")),
    SILURIAN_STATIC(new NamespacedKey(TARDIS.plugin, "monster/silurian/silurian_static")),
    SILURIAN_ATTACKING_0(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_attacking_0")),
    SILURIAN_ATTACKING_1(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_attacking_1")),
    SILURIAN_ATTACKING_2(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_attacking_2")),
    SILURIAN_ATTACKING_3(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_attacking_3")),
    SILURIAN_ATTACKING_4(new NamespacedKey(TARDIS.plugin, "monster/silurian/frames/silurian_attacking_4")),
    E1(new NamespacedKey(TARDIS.plugin, "elements/1")),
    E2(new NamespacedKey(TARDIS.plugin, "elements/2")),
    E3(new NamespacedKey(TARDIS.plugin, "elements/3")),
    E4(new NamespacedKey(TARDIS.plugin, "elements/4")),
    E5(new NamespacedKey(TARDIS.plugin, "elements/5")),
    E6(new NamespacedKey(TARDIS.plugin, "elements/6")),
    E7(new NamespacedKey(TARDIS.plugin, "elements/7")),
    E8(new NamespacedKey(TARDIS.plugin, "elements/8")),
    E9(new NamespacedKey(TARDIS.plugin, "elements/9")),
    E10(new NamespacedKey(TARDIS.plugin, "elements/10")),
    E11(new NamespacedKey(TARDIS.plugin, "elements/11")),
    E12(new NamespacedKey(TARDIS.plugin, "elements/12")),
    E13(new NamespacedKey(TARDIS.plugin, "elements/13")),
    E14(new NamespacedKey(TARDIS.plugin, "elements/14")),
    E15(new NamespacedKey(TARDIS.plugin, "elements/15")),
    E16(new NamespacedKey(TARDIS.plugin, "elements/16")),
    E17(new NamespacedKey(TARDIS.plugin, "elements/17")),
    E18(new NamespacedKey(TARDIS.plugin, "elements/18")),
    E19(new NamespacedKey(TARDIS.plugin, "elements/19")),
    E20(new NamespacedKey(TARDIS.plugin, "elements/20")),
    E21(new NamespacedKey(TARDIS.plugin, "elements/21")),
    E22(new NamespacedKey(TARDIS.plugin, "elements/22")),
    E23(new NamespacedKey(TARDIS.plugin, "elements/23")),
    E24(new NamespacedKey(TARDIS.plugin, "elements/24")),
    E25(new NamespacedKey(TARDIS.plugin, "elements/25")),
    E26(new NamespacedKey(TARDIS.plugin, "elements/26")),
    E27(new NamespacedKey(TARDIS.plugin, "elements/27")),
    E28(new NamespacedKey(TARDIS.plugin, "elements/28")),
    E29(new NamespacedKey(TARDIS.plugin, "elements/29")),
    E30(new NamespacedKey(TARDIS.plugin, "elements/30")),
    E31(new NamespacedKey(TARDIS.plugin, "elements/31")),
    E32(new NamespacedKey(TARDIS.plugin, "elements/32")),
    E33(new NamespacedKey(TARDIS.plugin, "elements/33")),
    E34(new NamespacedKey(TARDIS.plugin, "elements/34")),
    E35(new NamespacedKey(TARDIS.plugin, "elements/35")),
    E36(new NamespacedKey(TARDIS.plugin, "elements/36")),
    E37(new NamespacedKey(TARDIS.plugin, "elements/37")),
    E38(new NamespacedKey(TARDIS.plugin, "elements/38")),
    E39(new NamespacedKey(TARDIS.plugin, "elements/39")),
    E40(new NamespacedKey(TARDIS.plugin, "elements/40")),
    E41(new NamespacedKey(TARDIS.plugin, "elements/41")),
    E42(new NamespacedKey(TARDIS.plugin, "elements/42")),
    E43(new NamespacedKey(TARDIS.plugin, "elements/43")),
    E44(new NamespacedKey(TARDIS.plugin, "elements/44")),
    E45(new NamespacedKey(TARDIS.plugin, "elements/45")),
    E46(new NamespacedKey(TARDIS.plugin, "elements/46")),
    E47(new NamespacedKey(TARDIS.plugin, "elements/47")),
    E48(new NamespacedKey(TARDIS.plugin, "elements/48")),
    E49(new NamespacedKey(TARDIS.plugin, "elements/49")),
    E50(new NamespacedKey(TARDIS.plugin, "elements/50")),
    E51(new NamespacedKey(TARDIS.plugin, "elements/51")),
    E52(new NamespacedKey(TARDIS.plugin, "elements/52")),
    E53(new NamespacedKey(TARDIS.plugin, "elements/53")),
    E54(new NamespacedKey(TARDIS.plugin, "elements/54")),
    E55(new NamespacedKey(TARDIS.plugin, "elements/55")),
    E56(new NamespacedKey(TARDIS.plugin, "elements/56")),
    E57(new NamespacedKey(TARDIS.plugin, "elements/57")),
    E58(new NamespacedKey(TARDIS.plugin, "elements/58")),
    E59(new NamespacedKey(TARDIS.plugin, "elements/59")),
    E60(new NamespacedKey(TARDIS.plugin, "elements/60")),
    E61(new NamespacedKey(TARDIS.plugin, "elements/61")),
    E62(new NamespacedKey(TARDIS.plugin, "elements/62")),
    E63(new NamespacedKey(TARDIS.plugin, "elements/63")),
    E64(new NamespacedKey(TARDIS.plugin, "elements/64")),
    E65(new NamespacedKey(TARDIS.plugin, "elements/65")),
    E66(new NamespacedKey(TARDIS.plugin, "elements/66")),
    E67(new NamespacedKey(TARDIS.plugin, "elements/67")),
    E68(new NamespacedKey(TARDIS.plugin, "elements/68")),
    E69(new NamespacedKey(TARDIS.plugin, "elements/69")),
    E70(new NamespacedKey(TARDIS.plugin, "elements/70")),
    E71(new NamespacedKey(TARDIS.plugin, "elements/71")),
    E72(new NamespacedKey(TARDIS.plugin, "elements/72")),
    E73(new NamespacedKey(TARDIS.plugin, "elements/73")),
    E74(new NamespacedKey(TARDIS.plugin, "elements/74")),
    E75(new NamespacedKey(TARDIS.plugin, "elements/75")),
    E76(new NamespacedKey(TARDIS.plugin, "elements/76")),
    E77(new NamespacedKey(TARDIS.plugin, "elements/77")),
    E78(new NamespacedKey(TARDIS.plugin, "elements/78")),
    E79(new NamespacedKey(TARDIS.plugin, "elements/79")),
    E80(new NamespacedKey(TARDIS.plugin, "elements/80")),
    E81(new NamespacedKey(TARDIS.plugin, "elements/81")),
    E82(new NamespacedKey(TARDIS.plugin, "elements/82")),
    E83(new NamespacedKey(TARDIS.plugin, "elements/83")),
    E84(new NamespacedKey(TARDIS.plugin, "elements/84")),
    E85(new NamespacedKey(TARDIS.plugin, "elements/85")),
    E86(new NamespacedKey(TARDIS.plugin, "elements/86")),
    E87(new NamespacedKey(TARDIS.plugin, "elements/87")),
    E88(new NamespacedKey(TARDIS.plugin, "elements/88")),
    E89(new NamespacedKey(TARDIS.plugin, "elements/89")),
    E90(new NamespacedKey(TARDIS.plugin, "elements/90")),
    E91(new NamespacedKey(TARDIS.plugin, "elements/91")),
    E92(new NamespacedKey(TARDIS.plugin, "elements/92")),
    E93(new NamespacedKey(TARDIS.plugin, "elements/93")),
    E94(new NamespacedKey(TARDIS.plugin, "elements/94")),
    E95(new NamespacedKey(TARDIS.plugin, "elements/95")),
    E96(new NamespacedKey(TARDIS.plugin, "elements/96")),
    E97(new NamespacedKey(TARDIS.plugin, "elements/97")),
    E98(new NamespacedKey(TARDIS.plugin, "elements/98")),
    E99(new NamespacedKey(TARDIS.plugin, "elements/99")),
    E100(new NamespacedKey(TARDIS.plugin, "elements/100")),
    E101(new NamespacedKey(TARDIS.plugin, "elements/101")),
    E102(new NamespacedKey(TARDIS.plugin, "elements/102")),
    E103(new NamespacedKey(TARDIS.plugin, "elements/103")),
    E104(new NamespacedKey(TARDIS.plugin, "elements/104")),
    E105(new NamespacedKey(TARDIS.plugin, "elements/105")),
    E106(new NamespacedKey(TARDIS.plugin, "elements/106")),
    E107(new NamespacedKey(TARDIS.plugin, "elements/107")),
    E108(new NamespacedKey(TARDIS.plugin, "elements/108")),
    E109(new NamespacedKey(TARDIS.plugin, "elements/109")),
    E110(new NamespacedKey(TARDIS.plugin, "elements/110")),
    E111(new NamespacedKey(TARDIS.plugin, "elements/111")),
    E112(new NamespacedKey(TARDIS.plugin, "elements/112")),
    E113(new NamespacedKey(TARDIS.plugin, "elements/113")),
    E114(new NamespacedKey(TARDIS.plugin, "elements/114")),
    E115(new NamespacedKey(TARDIS.plugin, "elements/115")),
    E116(new NamespacedKey(TARDIS.plugin, "elements/116")),
    E117(new NamespacedKey(TARDIS.plugin, "elements/117")),
    E118(new NamespacedKey(TARDIS.plugin, "elements/118")),
    UNKNOWN(new NamespacedKey(TARDIS.plugin, "elements/unknown"));

    private final NamespacedKey key;

    Feather(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}

