package me.eccentric_nz.TARDIS.custommodeldata.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum Repeater {

    ALLOW_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/allow_on")),
    ARCH_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/arch_on")),
    ARCHIVE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/archive_on")),
    CREATION_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/creation_on")),
    GROWTH_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/growth_on")),
    HANDLES_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/handles_on")),
    POLICE_BOX_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/police_box_on")),
    PREFERENCES_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/preferences_on")),
    ABANDON_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/abandon_on")),
    CIRCUIT_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/circuit_on")),
    DEBUG_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/debug_on")),
    THEME_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/theme_on")),
    JUNK_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/junk_on")),
    SIEGE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/siege_on")),
    TRAVEL_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/travel_on")),
    BUTTON_LIGHTS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_lights_on")),
    BUTTON_POWER_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_power_on")),
    BUTTON_SIEGE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_siege_on")),
    BUTTON_TOGGLE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_toggle_on")),
    AUTONOMOUS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/autonomous_on")),
    AUTONOMOUS_SIEGE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/autonomous_siege_on")),
    AUTO_RESCUE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/auto_rescue_on")),
    BEACON_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/beacon_on")),
    DO_NOT_DISTURB_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/do_not_disturb_on")),
    EMERGENCY_PROGRAM_ONE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/emergency_program_one_on")),
    HOSTILE_ACTION_DISPLACEMENT_SYSTEM_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/hostile_action_displacement_system_on")),
    HADS_TYPE_DISPLACEMENT(new NamespacedKey(TARDIS.plugin, "gui/repeater/hads_type_displacement")),
    WHO_QUOTES_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/who_quotes_on")),
    EXTERIOR_RENDERING_ROOM_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/exterior_rendering_room_on")),
    INTERIOR_SFX_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/interior_sfx_on")),
    SUBMARINE_MODE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/submarine_mode_on")),
    RESOURCE_PACK_SWITCHING_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/resource_pack_switching_on")),
    COMPANION_BUILD_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/companion_build_on")),
    WOOL_FOR_LIGHTS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/wool_for_lights_on")),
    CONNECTED_TEXTURES_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/connected_textures_on")),
    PRESET_SIGN_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/preset_sign_on")),
    TRAVEL_BAR_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/travel_bar_on")),
    POLICE_BOX_TEXTURES_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/police_box_textures_on")),
    MOB_FARMING_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/mob_farming_on")),
    TELEPATHIC_CIRCUIT_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/telepathic_circuit_on")),
    JUNK_TARDIS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/junk_tardis_on")),
    AUTO_POWER_UP_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/auto_power_up_on")),
    FORCE_FIELD_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/force_field_on")),
    LANTERNS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/lanterns_on")),
    MINECART_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/minecart_on")),
    EASY_DIFF_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/easy_diff_on")),
    FONT_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/font_on")),
    BLUEPRINTS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/blueprints_on")),
    LOCK_CONTAINERS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/lock_containers_on")),
    CLOSE_GUI_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/close_gui_on")),
    ANNOUNCE_REPEATERS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/announce_repeaters_on")),
    DYNAMIC_LAMPS_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/dynamic_lamps_on")),
    SONIC_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/sonic_on")),
    INFO_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/info_on")),
    DOWNLOAD_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/download_on")),
    DIFFICULTY_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/difficulty_on")),
    EYE_ON(new NamespacedKey(TARDIS.plugin, "gui/repeater/eye_on")),
    ALLOW_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/allow_off")),
    ARCH_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/arch_off")),
    ARCHIVE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/archive_off")),
    CREATION_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/creation_off")),
    GROWTH_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/growth_off")),
    HANDLES_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/handles_off")),
    POLICE_BOX_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/police_box_off")),
    PREFERENCES_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/preferences_off")),
    ABANDON_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/abandon_off")),
    CIRCUIT_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/circuit_off")),
    DEBUG_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/debug_off")),
    THEME_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/theme_off")),
    JUNK_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/junk_off")),
    SIEGE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/siege_off")),
    TRAVEL_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/travel_off")),
    BUTTON_LIGHTS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_lights_off")),
    BUTTON_POWER_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_power_off")),
    BUTTON_SIEGE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_siege_off")),
    BUTTON_TOGGLE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/button_toggle_off")),
    AUTONOMOUS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/autonomous_off")),
    AUTONOMOUS_SIEGE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/autonomous_siege_off")),
    AUTO_RESCUE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/auto_rescue_off")),
    BEACON_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/beacon_off")),
    DO_NOT_DISTURB_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/do_not_disturb_off")),
    EMERGENCY_PROGRAM_ONE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/emergency_program_one_off")),
    HOSTILE_ACTION_DISPLACEMENT_SYSTEM_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/hostile_action_displacement_system_off")),
    HADS_TYPE_DISPERSAL(new NamespacedKey(TARDIS.plugin, "gui/repeater/hads_type_dispersal")),
    WHO_QUOTES_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/who_quotes_off")),
    EXTERIOR_RENDERING_ROOM_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/exterior_rendering_room_off")),
    INTERIOR_SFX_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/interior_sfx_off")),
    SUBMARINE_MODE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/submarine_mode_off")),
    RESOURCE_PACK_SWITCHING_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/resource_pack_switching_off")),
    COMPANION_BUILD_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/companion_build_off")),
    WOOL_FOR_LIGHTS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/wool_for_lights_off")),
    CONNECTED_TEXTURES_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/connected_textures_off")),
    PRESET_SIGN_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/preset_sign_off")),
    TRAVEL_BAR_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/travel_bar_off")),
    POLICE_BOX_TEXTURES_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/police_box_textures_off")),
    MOB_FARMING_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/mob_farming_off")),
    TELEPATHIC_CIRCUIT_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/telepathic_circuit_off")),
    JUNK_TARDIS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/junk_tardis_off")),
    AUTO_POWER_UP_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/auto_power_up_off")),
    FORCE_FIELD_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/force_field_off")),
    LANTERNS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/lanterns_off")),
    MINECART_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/minecart_off")),
    EASY_DIFF_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/easy_diff_off")),
    FONT_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/font_off")),
    BLUEPRINTS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/blueprints_off")),
    LOCK_CONTAINERS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/lock_containers_off")),
    CLOSE_GUI_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/close_gui_off")),
    AUTO_TYPE(new NamespacedKey(TARDIS.plugin, "gui/repeater/auto_type")),
    AUTO_DEFAULT(new NamespacedKey(TARDIS.plugin, "gui/repeater/auto_default")),
    ANNOUNCE_REPEATERS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/announce_repeaters_off")),
    DYNAMIC_LAMPS_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/dynamic_lamps_off")),
    SONIC_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/sonic_off")),
    INFO_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/info_off")),
    DOWNLOAD_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/download_off")),
    DIFFICULTY_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/difficulty_off")),
    EYE_OFF(new NamespacedKey(TARDIS.plugin, "gui/repeater/eye_off")),
    THROTTLE_WARP(new NamespacedKey(TARDIS.plugin, "controls/throttle_warp")),
    THROTTLE_RAPID(new NamespacedKey(TARDIS.plugin, "controls/throttle_rapid")),
    THROTTLE_FASTER(new NamespacedKey(TARDIS.plugin, "controls/throttle_faster")),
    THROTTLE_NORMAL(new NamespacedKey(TARDIS.plugin, "controls/throttle_normal"));

    private final NamespacedKey key;

    Repeater(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
