package me.eccentric_nz.TARDIS.custommodeldata.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum RotorVariant {

    EARLY_0(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_0")),
    EARLY_1(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_1")),
    EARLY_2(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_2")),
    EARLY_3(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_3")),
    EARLY_4(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_4")),
    EARLY_5(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_5")),
    EARLY_6(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_6")),
    EARLY_7(new NamespacedKey(TARDIS.plugin, "time_rotor/early/early_7")),
    CLASSIC_0(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_0")),
    CLASSIC_1(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_1")),
    CLASSIC_2(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_2")),
    CLASSIC_3(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_3")),
    CLASSIC_4(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_4")),
    CLASSIC_5(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_5")),
    CLASSIC_6(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_6")),
    CLASSIC_7(new NamespacedKey(TARDIS.plugin, "time_rotor/classic/classic_7")),
    CONSOLE_0(new NamespacedKey(TARDIS.plugin, "time_rotor/console/console_0")),
    CONSOLE_1(new NamespacedKey(TARDIS.plugin, "time_rotor/console/console_1")),
    CONSOLE_2(new NamespacedKey(TARDIS.plugin, "time_rotor/console/console_2")),
    CONSOLE_3(new NamespacedKey(TARDIS.plugin, "time_rotor/console/console_3")),
    CONSOLE_4(new NamespacedKey(TARDIS.plugin, "time_rotor/console/console_4")),
    DELTA_0(new NamespacedKey(TARDIS.plugin, "time_rotor/delta/delta_0")),
    DELTA_1(new NamespacedKey(TARDIS.plugin, "time_rotor/delta/delta_1")),
    DELTA_2(new NamespacedKey(TARDIS.plugin, "time_rotor/delta/delta_2")),
    DELTA_3(new NamespacedKey(TARDIS.plugin, "time_rotor/delta/delta_3")),
    DELTA_4(new NamespacedKey(TARDIS.plugin, "time_rotor/delta/delta_4")),
    DELTA_5(new NamespacedKey(TARDIS.plugin, "time_rotor/delta/delta_5")),
    ELEVENTH_0(new NamespacedKey(TARDIS.plugin, "time_rotor/eleventh/eleventh_0")),
    ELEVENTH_1(new NamespacedKey(TARDIS.plugin, "time_rotor/eleventh/eleventh_1")),
    ELEVENTH_2(new NamespacedKey(TARDIS.plugin, "time_rotor/eleventh/eleventh_2")),
    ELEVENTH_3(new NamespacedKey(TARDIS.plugin, "time_rotor/eleventh/eleventh_3")),
    ELEVENTH_4(new NamespacedKey(TARDIS.plugin, "time_rotor/eleventh/eleventh_4")),
    ENGINE_0(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_0")),
    ENGINE_1(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_1")),
    ENGINE_2(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_2")),
    ENGINE_3(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_3")),
    ENGINE_4(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_4")),
    ENGINE_5(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_5")),
    ENGINE_6(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_6")),
    ENGINE_7(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_7")),
    ENGINE_8(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_8")),
    ENGINE_9(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_9")),
    ENGINE_10(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_10")),
    ENGINE_11(new NamespacedKey(TARDIS.plugin, "time_rotor/engine/engine_11")),
    ENGINE_ROTOR_0(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_rotor/engine_rotor_0")),
    ENGINE_ROTOR_1(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_rotor/engine_rotor_1")),
    ENGINE_ROTOR_2(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_rotor/engine_rotor_2")),
    ENGINE_ROTOR_3(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_rotor/engine_rotor_3")),
    ENGINE_ROTOR_4(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_rotor/engine_rotor_4")),
    ENGINE_ROTOR_5(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_rotor/engine_rotor_5")),
    HOSPITAL_0(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_0")),
    HOSPITAL_1(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_1")),
    HOSPITAL_2(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_2")),
    HOSPITAL_3(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_3")),
    HOSPITAL_4(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_4")),
    HOSPITAL_5(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_5")),
    HOSPITAL_6(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_6")),
    HOSPITAL_7(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_7")),
    HOSPITAL_8(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_8")),
    HOSPITAL_9(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_9")),
    HOSPITAL_10(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_10")),
    HOSPITAL_11(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital/hospital_11")),
    TIME_ROTOR_EARLY_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/time_rotor_early_off")),
    TIME_ROTOR_TENNANT_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/time_rotor_tennant_off")),
    TIME_ROTOR_ELEVENTH_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/time_rotor_eleventh_off")),
    TIME_ROTOR_TWELFTH_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/time_rotor_twelfth_off")),
    TIME_ROTOR_DELTA_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/time_rotor_delta_off")),
    ENGINE_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_off")),
    ENGINE_ROTOR_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/engine_rotor_off")),
    HOSPITAL_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/hospital_off")),
    TIME_ROTOR_CONSOLE_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/time_rotor_console_off")),
    TIME_ROTOR_RUSTIC_OFF(new NamespacedKey(TARDIS.plugin, "time_rotor/time_rotor_rustic_off")),
    RUSTIC_0(new NamespacedKey(TARDIS.plugin, "time_rotor/rustic/rustic_0")),
    RUSTIC_1(new NamespacedKey(TARDIS.plugin, "time_rotor/rustic/rustic_1")),
    RUSTIC_2(new NamespacedKey(TARDIS.plugin, "time_rotor/rustic/rustic_2")),
    RUSTIC_3(new NamespacedKey(TARDIS.plugin, "time_rotor/rustic/rustic_3")),
    RUSTIC_4(new NamespacedKey(TARDIS.plugin, "time_rotor/rustic/rustic_4")),
    TENNANT_0(new NamespacedKey(TARDIS.plugin, "time_rotor/tennant/tennant_0")),
    TENNANT_1(new NamespacedKey(TARDIS.plugin, "time_rotor/tennant/tennant_1")),
    TENNANT_2(new NamespacedKey(TARDIS.plugin, "time_rotor/tennant/tennant_2")),
    TENNANT_3(new NamespacedKey(TARDIS.plugin, "time_rotor/tennant/tennant_3")),
    TENNANT_4(new NamespacedKey(TARDIS.plugin, "time_rotor/tennant/tennant_4"));

    private final NamespacedKey key;

    RotorVariant(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
