package me.eccentric_nz.TARDIS.custommodels.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum ChameleonVariant {

    GLASS(new NamespacedKey(TARDIS.plugin, "police_box/tardis_glass")),
    BLACK(new NamespacedKey(TARDIS.plugin, "police_box/tardis_black")),
    BLACK_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_black_open")),
    BLACK_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_black_stained")),
    BLACK_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/black/black_flying")),
    BLACK_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/black/black_flying_open")),
    BLUE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue")),
    BLUE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue_open")),
    BLUE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue_stained")),
    BLUE_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/blue/blue_flying")),
    BLUE_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/blue/blue_flying_open")),
    BROWN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_brown")),
    BROWN_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_brown_open")),
    BROWN_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_brown_stained")),
    BROWN_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/brown/brown_flying")),
    BROWN_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/brown/brown_flying_open")),
    CYAN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_cyan")),
    CYAN_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_cyan_open")),
    CYAN_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_cyan_stained")),
    CYAN_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/cyan/cyan_flying")),
    CYAN_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/cyan/cyan_flying_open")),
    GRAY(new NamespacedKey(TARDIS.plugin, "police_box/tardis_gray")),
    GRAY_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_gray_open")),
    GRAY_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_gray_stained")),
    GRAY_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/gray/gray_flying")),
    GRAY_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/gray/gray_flying_open")),
    GREEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_green")),
    GREEN_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_green_open")),
    GREEN_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_green_stained")),
    GREEN_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/green/green_flying")),
    GREEN_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/green/green_flying_open")),
    LIGHT_BLUE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_blue")),
    LIGHT_BLUE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_blue_open")),
    LIGHT_BLUE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_blue_stained")),
    LIGHT_BLUE_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/light_blue/light_blue_flying")),
    LIGHT_BLUE_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/light_blue/light_blue_flying_open")),
    LIGHT_GRAY(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_gray")),
    LIGHT_GRAY_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_gray_open")),
    LIGHT_GRAY_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_gray_stained")),
    LIGHT_GRAY_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/light_gray/light_gray_flying")),
    LIGHT_GRAY_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/light_gray/light_gray_flying_open")),
    LIME(new NamespacedKey(TARDIS.plugin, "police_box/tardis_lime")),
    LIME_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_lime_open")),
    LIME_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_lime_stained")),
    LIME_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/lime/lime_flying")),
    LIME_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/lime/lime_flying_open")),
    MAGENTA(new NamespacedKey(TARDIS.plugin, "police_box/tardis_magenta")),
    MAGENTA_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_magenta_open")),
    MAGENTA_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_magenta_stained")),
    MAGENTA_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/magenta/magenta_flying")),
    MAGENTA_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/magenta/magenta_flying_open")),
    ORANGE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_orange")),
    ORANGE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_orange_open")),
    ORANGE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_orange_stained")),
    ORANGE_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/orange/orange_flying")),
    ORANGE_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/orange/orange_flying_open")),
    PINK(new NamespacedKey(TARDIS.plugin, "police_box/tardis_pink")),
    PINK_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_pink_open")),
    PINK_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_pink_stained")),
    PINK_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/pink/pink_flying")),
    PINK_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/pink/pink_flying_open")),
    PURPLE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_purple")),
    PURPLE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_purple_open")),
    PURPLE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_purple_stained")),
    PURPLE_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/purple/purple_flying")),
    PURPLE_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/purple/purple_flying_open")),
    RED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_red")),
    RED_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_red_open")),
    RED_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_red_stained")),
    RED_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/red/red_flying")),
    RED_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/red/red_flying_open")),
    WHITE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_white")),
    WHITE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_white_open")),
    WHITE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_white_stained")),
    WHITE_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/white/white_flying")),
    WHITE_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/white/white_flying_open")),
    YELLOW(new NamespacedKey(TARDIS.plugin, "police_box/tardis_yellow")),
    YELLOW_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_yellow_open")),
    YELLOW_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_yellow_stained")),
    YELLOW_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/yellow/yellow_flying")),
    YELLOW_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/yellow/yellow_flying_open")),
    TENNANT(new NamespacedKey(TARDIS.plugin, "police_box/tardis_tennant")),
    TENNANT_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_tennant_open")),
    TENNANT_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_tennant_stained")),
    TENNANT_GLASS(new NamespacedKey(TARDIS.plugin, "police_box/tardis_glass")),
    TENNANT_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/tennant/tennant_flying")),
    TENNANT_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tennant/tennant_flying_open")),
    BAD_WOLF_CLOSED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_bad_wolf_closed")),
    BAD_WOLF_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_bad_wolf_open")),
    BAD_WOLF_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue_stained")),
    BAD_WOLF_SGLASS(new NamespacedKey(TARDIS.plugin, "police_box/tardis_glass")),
    BAD_WOLF_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/bad_wolf/bad_wolf_flying")),
    BAD_WOLF_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/bad_wolf/bad_wolf_flying_open")),
    TYPE_40_CLOSED(new NamespacedKey(TARDIS.plugin, "police_box/type_40_closed")),
    TYPE_40_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/type_40_open")),
    TYPE_40_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/type_40_stained")),
    TYPE_40_GLASS(new NamespacedKey(TARDIS.plugin, "police_box/type_40_glass")),
    TYPE_40_FLYING(new NamespacedKey(TARDIS.plugin, "police_box/type_40/type_40_flying")),
    TYPE_40_FLYING_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/type_40/type_40_flying_open")),
    PANDORICA(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica")),
    PANDORICA_OPEN(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_open")),
    PANDORICA_STAINED(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_stained")),
    PANDORICA_GLASS(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_glass")),
    PANDORICA_75(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_75")),
    PANDORICA_50(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_50")),
    PANDORICA_25(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_25")),
    PANDORICA_FLYING(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_flying")),
    WEEPING_ANGEL(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel")),
    WEEPING_ANGEL_OPEN(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel_open")),
    WEEPING_ANGEL_STAINED(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel_stained")),
    WEEPING_ANGEL_GLASS(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel_glass"));

    private final NamespacedKey key;

    ChameleonVariant(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
