package me.eccentric_nz.TARDIS.custommodels.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum ChameleonVariant {

    GLASS(new NamespacedKey(TARDIS.plugin, "police_box/tardis_glass")),
    BLACK(new NamespacedKey(TARDIS.plugin, "police_box/tardis_black")),
    BLACK_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_black_open")),
    BLACK_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_black_stained")),
    BLACK_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/black/black_camera")),
    BLUE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue")),
    BLUE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue_open")),
    BLUE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue_stained")),
    BLUE_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/blue/blue_camera")),
    BROWN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_brown")),
    BROWN_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_brown_open")),
    BROWN_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_brown_stained")),
    BROWN_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/brown/brown_camera")),
    CYAN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_cyan")),
    CYAN_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_cyan_open")),
    CYAN_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_cyan_stained")),
    CYAN_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/cyan/cyan_camera")),
    GRAY(new NamespacedKey(TARDIS.plugin, "police_box/tardis_gray")),
    GRAY_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_gray_open")),
    GRAY_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_gray_stained")),
    GRAY_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/gray/gray_camera")),
    GREEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_green")),
    GREEN_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_green_open")),
    GREEN_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_green_stained")),
    GREEN_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/green/green_camera")),
    LIGHT_BLUE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_blue")),
    LIGHT_BLUE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_blue_open")),
    LIGHT_BLUE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_blue_stained")),
    LIGHT_BLUE_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/light_blue/light_blue_camera")),
    LIGHT_GRAY(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_gray")),
    LIGHT_GRAY_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_gray_open")),
    LIGHT_GRAY_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_light_gray_stained")),
    LIGHT_GRAY_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/light_gray/light_gray_camera")),
    LIME(new NamespacedKey(TARDIS.plugin, "police_box/tardis_lime")),
    LIME_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_lime_open")),
    LIME_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_lime_stained")),
    LIME_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/lime/lime_camera")),
    MAGENTA(new NamespacedKey(TARDIS.plugin, "police_box/tardis_magenta")),
    MAGENTA_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_magenta_open")),
    MAGENTA_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_magenta_stained")),
    MAGENTA_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/magenta/magenta_camera")),
    ORANGE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_orange")),
    ORANGE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_orange_open")),
    ORANGE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_orange_stained")),
    ORANGE_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/orange/orange_camera")),
    PINK(new NamespacedKey(TARDIS.plugin, "police_box/tardis_pink")),
    PINK_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_pink_open")),
    PINK_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_pink_stained")),
    PINK_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/pink/pink_camera")),
    PURPLE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_purple")),
    PURPLE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_purple_open")),
    PURPLE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_purple_stained")),
    PURPLE_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/purple/purple_camera")),
    RED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_red")),
    RED_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_red_open")),
    RED_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_red_stained")),
    RED_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/red/red_camera")),
    WHITE(new NamespacedKey(TARDIS.plugin, "police_box/tardis_white")),
    WHITE_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_white_open")),
    WHITE_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_white_stained")),
    WHITE_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/white/white_camera")),
    YELLOW(new NamespacedKey(TARDIS.plugin, "police_box/tardis_yellow")),
    YELLOW_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_yellow_open")),
    YELLOW_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_yellow_stained")),
    YELLOW_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/yellow/yellow_camera")),
    TENNANT(new NamespacedKey(TARDIS.plugin, "police_box/tardis_tennant")),
    TENNANT_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_tennant_open")),
    TENNANT_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_tennant_stained")),
    TENNANT_GLASS(new NamespacedKey(TARDIS.plugin, "police_box/tardis_glass")),
    TENNANT_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/tennant/tennant_camera")),
    BAD_WOLF(new NamespacedKey(TARDIS.plugin, "police_box/tardis_bad_wolf_closed")),
    BAD_WOLF_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/tardis_bad_wolf_open")),
    BAD_WOLF_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/tardis_blue_stained")),
    BAD_WOLF_SGLASS(new NamespacedKey(TARDIS.plugin, "police_box/tardis_glass")),
    BAD_WOLF_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/bad_wolf/bad_wolf_camera")),
    TYPE_40_CLOSED(new NamespacedKey(TARDIS.plugin, "police_box/type_40_closed")),
    TYPE_40_OPEN(new NamespacedKey(TARDIS.plugin, "police_box/type_40_open")),
    TYPE_40_STAINED(new NamespacedKey(TARDIS.plugin, "police_box/type_40_stained")),
    TYPE_40_GLASS(new NamespacedKey(TARDIS.plugin, "police_box/type_40_glass")),
    TYPE_40_CAMERA(new NamespacedKey(TARDIS.plugin, "police_box/type_40/type_40_camera")),
    PANDORICA(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica")),
    PANDORICA_OPEN(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_open")),
    PANDORICA_STAINED(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_stained")),
    PANDORICA_GLASS(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_glass")),
    PANDORICA_75(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_75")),
    PANDORICA_50(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_50")),
    PANDORICA_25(new NamespacedKey(TARDIS.plugin, "pandorica/pandorica_25")),
    WEEPING_ANGEL(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel")),
    WEEPING_ANGEL_OPEN(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel_open")),
    WEEPING_ANGEL_STAINED(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel_stained")),
    WEEPING_ANGEL_GLASS(new NamespacedKey(TARDIS.plugin, "weeping_angel/weeping_angel_glass"));

    private final NamespacedKey key;

    ChameleonVariant(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
