package me.eccentric_nz.TARDIS.custommodels.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum GuiVariant {

    ABORT(new NamespacedKey(TARDIS.plugin, "gui/bowl/abort")),
    ALIEN(new NamespacedKey(TARDIS.plugin, "gui/bowl/alien")),
    APPLY(new NamespacedKey(TARDIS.plugin, "gui/apply")),
    ARCHIVE_CONSOLES(new NamespacedKey(TARDIS.plugin, "gui/bowl/archive_consoles")),
    ARCHIVE_CURRENT_CONSOLE(new NamespacedKey(TARDIS.plugin, "gui/bowl/archive_current_console")),
    AREAS(new NamespacedKey(TARDIS.plugin, "gui/bowl/areas")),
    ARTRON_BATTERY(new NamespacedKey(TARDIS.plugin, "tardis/artron_battery")),
    ATMOSPHERE(new NamespacedKey(TARDIS.plugin, "gui/bowl/atmosphere")),
    AUTO_SAVE(new NamespacedKey(TARDIS.plugin, "gui/bowl/auto_save")),
    AUTO_SAVE_SELECTOR(new NamespacedKey(TARDIS.plugin, "gui/bowl/auto_save_selector")),
    BACK(new NamespacedKey(TARDIS.plugin, "gui/bowl/back")),
    BIO(new NamespacedKey(TARDIS.plugin, "circuit/bio")),
    BRUSH(new NamespacedKey(TARDIS.plugin, "circuit/brush")),
    CHECK(new NamespacedKey(TARDIS.plugin, "gui/bowl/check")),
    CHECK_OUT_SELECTED_PROGRAM(new NamespacedKey(TARDIS.plugin, "gui/bowl/check_out_selected_program")),
    CLEAN(new NamespacedKey(TARDIS.plugin, "gui/bowl/clean")),
    CLOSE(new NamespacedKey(TARDIS.plugin, "gui/bowl/close")),
    CLOSEST(new NamespacedKey(TARDIS.plugin, "gui/bowl/closest")),
    COMMAND(new NamespacedKey(TARDIS.plugin, "gui/bowl/command")),
    COMPANIONS_MENU(new NamespacedKey(TARDIS.plugin, "gui/bowl/companions_menu")),
    COMPUTER(new NamespacedKey(TARDIS.plugin, "gui/bowl/computer")),
    CONFIGURED(new NamespacedKey(TARDIS.plugin, "gui/bowl/configured")),
    CONTROL(new NamespacedKey(TARDIS.plugin, "gui/bowl/control")),
    CONVERSION(new NamespacedKey(TARDIS.plugin, "circuit/conversion")),
    COPPER(new NamespacedKey(TARDIS.plugin, "gui/bowl/copper")),
    CORAL(new NamespacedKey(TARDIS.plugin, "gui/bowl/coral")),
    CRAFT(new NamespacedKey(TARDIS.plugin, "gui/bowl/craft")),
    DIAMOND(new NamespacedKey(TARDIS.plugin, "circuit/diamond")),
    EIGHT(new NamespacedKey(TARDIS.plugin, "gui/bowl/eight")),
    ELECTRONS(new NamespacedKey(TARDIS.plugin, "gui/bowl/electrons")),
    EMERALD(new NamespacedKey(TARDIS.plugin, "circuit/emerald")),
    EVENT(new NamespacedKey(TARDIS.plugin, "gui/bowl/event")),
    FIVE(new NamespacedKey(TARDIS.plugin, "gui/bowl/five")),
    FLOOR(new NamespacedKey(TARDIS.plugin, "gui/bowl/floor")),
    FOUR(new NamespacedKey(TARDIS.plugin, "gui/bowl/four")),
    GALAXY(new NamespacedKey(TARDIS.plugin, "gui/bowl/galaxy")),
    GENERATE_SONIC_SCREWDRIVER(new NamespacedKey(TARDIS.plugin, "gui/bowl/generate_sonic_screwdriver")),
    HANDLES_DISK(new NamespacedKey(TARDIS.plugin, "disks/handles_disk")),
    HELP(new NamespacedKey(TARDIS.plugin, "gui/bowl/help")),
    HOME(new NamespacedKey(TARDIS.plugin, "gui/bowl/home")),
    IGNITE(new NamespacedKey(TARDIS.plugin, "circuit/ignite")),
    INFO(new NamespacedKey(TARDIS.plugin, "gui/bowl/info")),
    INTERIOR_HUM_SOUND(new NamespacedKey(TARDIS.plugin, "gui/bowl/interior_hum_sound")),
    KNOCKBACK(new NamespacedKey(TARDIS.plugin, "circuit/knockback")),
    LEARNING(new NamespacedKey(TARDIS.plugin, "gui/bowl/learning")),
    LEFT(new NamespacedKey(TARDIS.plugin, "gui/bowl/left")),
    LOAD_MAP(new NamespacedKey(TARDIS.plugin, "gui/map/load_map")),
    LOAD_SELECTED_PROGRAM_IN_EDITOR(new NamespacedKey(TARDIS.plugin, "gui/bowl/load_selected_program_in_editor")),
    MEDIUM(new NamespacedKey(TARDIS.plugin, "gui/bowl/medium")),
    MIND(new NamespacedKey(TARDIS.plugin, "gui/bowl/mind")),
    NEON(new NamespacedKey(TARDIS.plugin, "gui/bowl/neon")),
    NEUTRONS(new NamespacedKey(TARDIS.plugin, "gui/bowl/neutrons")),
    NEW(new NamespacedKey(TARDIS.plugin, "gui/bowl/new")),
    NEXT(new NamespacedKey(TARDIS.plugin, "gui/bowl/next")),
    NINE(new NamespacedKey(TARDIS.plugin, "gui/bowl/nine")),
    NUMBER(new NamespacedKey(TARDIS.plugin, "gui/bowl/number")),
    ONE(new NamespacedKey(TARDIS.plugin, "gui/bowl/one")),
    OPERATOR(new NamespacedKey(TARDIS.plugin, "gui/bowl/operator")),
    OWN_SAVES(new NamespacedKey(TARDIS.plugin, "gui/bowl/own_saves")),
    PAINTER(new NamespacedKey(TARDIS.plugin, "circuit/painter")),
    PICKUP(new NamespacedKey(TARDIS.plugin, "circuit/pickup")),
    PLAY(new NamespacedKey(TARDIS.plugin, "gui/bowl/play")),
    PREV(new NamespacedKey(TARDIS.plugin, "gui/bowl/prev")),
    PROTONS(new NamespacedKey(TARDIS.plugin, "gui/bowl/protons")),
    RANDOM(new NamespacedKey(TARDIS.plugin, "gui/bowl/random")),
    REDSTONE(new NamespacedKey(TARDIS.plugin, "circuit/redstone")),
    REDUCE(new NamespacedKey(TARDIS.plugin, "gui/bowl/reduce")),
    REPAIR_CONSOLE(new NamespacedKey(TARDIS.plugin, "gui/bowl/repair_console")),
    RIGHT(new NamespacedKey(TARDIS.plugin, "gui/bowl/right")),
    SAVE(new NamespacedKey(TARDIS.plugin, "gui/bowl/save")),
    SCAN_CONSOLE(new NamespacedKey(TARDIS.plugin, "gui/bowl/scan_console")),
    SELECTOR(new NamespacedKey(TARDIS.plugin, "gui/bowl/selector")),
    SET_SIZE(new NamespacedKey(TARDIS.plugin, "gui/bowl/set_size")),
    SEVEN(new NamespacedKey(TARDIS.plugin, "gui/bowl/seven")),
    SIX(new NamespacedKey(TARDIS.plugin, "gui/bowl/six")),
    SLEEPING(new NamespacedKey(TARDIS.plugin, "gui/bowl/sleeping")),
    SMALL(new NamespacedKey(TARDIS.plugin, "gui/bowl/small")),
    STANDARD_SONIC(new NamespacedKey(TARDIS.plugin, "gui/bowl/standard_sonic")),
    STAY(new NamespacedKey(TARDIS.plugin, "gui/bowl/stay")),
    TALL(new NamespacedKey(TARDIS.plugin, "gui/bowl/tall")),
    TARDIS_SAVES(new NamespacedKey(TARDIS.plugin, "gui/bowl/tardis_saves")),
    THREE(new NamespacedKey(TARDIS.plugin, "gui/bowl/three")),
    TRANSMAT_LOCATION(new NamespacedKey(TARDIS.plugin, "gui/map/transmat_location")),
    TWO(new NamespacedKey(TARDIS.plugin, "gui/bowl/two")),
    UPDATE_SELECTED(new NamespacedKey(TARDIS.plugin, "gui/bowl/update_selected")),
    USE_LAST_SAVED_CONSTRUCT(new NamespacedKey(TARDIS.plugin, "gui/bowl/use_last_saved_construct")),
    USE_SELECTED(new NamespacedKey(TARDIS.plugin, "gui/bowl/use_selected")),
    VAR(new NamespacedKey(TARDIS.plugin, "gui/bowl/var")),
    VIEW_TEMPLATE(new NamespacedKey(TARDIS.plugin, "gui/bowl/view_temp")),
    VOID(new NamespacedKey(TARDIS.plugin, "gui/bowl/void")),
    WALL(new NamespacedKey(TARDIS.plugin, "gui/bowl/wall")),
    WHERE_AM_I(new NamespacedKey(TARDIS.plugin, "gui/map/where_am_i"));

    private final NamespacedKey key;

    GuiVariant(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
