package me.eccentric_nz.TARDIS.custommodels.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum ModelledControl {

    LAMP_0(new NamespacedKey(TARDIS.plugin, "model_lamp_0")),
    LAMP_1(new NamespacedKey(TARDIS.plugin, "model_lamp_1")),
    LAMP_2(new NamespacedKey(TARDIS.plugin, "model_lamp_2")),
    LAMP_3(new NamespacedKey(TARDIS.plugin, "model_lamp_3")),
    LAMP_4(new NamespacedKey(TARDIS.plugin, "model_lamp_4")),
    LAMP_5(new NamespacedKey(TARDIS.plugin, "model_lamp_5")),
    LAMP_6(new NamespacedKey(TARDIS.plugin, "model_lamp_6")),
    LAMP_7(new NamespacedKey(TARDIS.plugin, "model_lamp_7")),
    LAMP_0_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_0_off")),
    LAMP_1_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_1_off")),
    LAMP_2_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_2_off")),
    LAMP_3_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_3_off")),
    LAMP_4_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_4_off")),
    LAMP_5_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_5_off")),
    LAMP_6_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_6_off")),
    LAMP_7_OFF(new NamespacedKey(TARDIS.plugin, "model_lamp_7_off")),
    LIGHT_0(new NamespacedKey(TARDIS.plugin, "model_light_0")),
    LIGHT_1(new NamespacedKey(TARDIS.plugin, "model_light_1")),
    LIGHT_2(new NamespacedKey(TARDIS.plugin, "model_light_2")),
    LIGHT_3(new NamespacedKey(TARDIS.plugin, "model_light_3")),
    LIGHT_4(new NamespacedKey(TARDIS.plugin, "model_light_4")),
    LIGHT_5(new NamespacedKey(TARDIS.plugin, "model_light_5")),
    LIGHT_6(new NamespacedKey(TARDIS.plugin, "model_light_6")),
    LIGHT_7(new NamespacedKey(TARDIS.plugin, "model_light_7")),
    LIGHT_0_OFF(new NamespacedKey(TARDIS.plugin, "model_light_0_off")),
    LIGHT_1_OFF(new NamespacedKey(TARDIS.plugin, "model_light_1_off")),
    LIGHT_2_OFF(new NamespacedKey(TARDIS.plugin, "model_light_2_off")),
    LIGHT_3_OFF(new NamespacedKey(TARDIS.plugin, "model_light_3_off")),
    LIGHT_4_OFF(new NamespacedKey(TARDIS.plugin, "model_light_4_off")),
    LIGHT_5_OFF(new NamespacedKey(TARDIS.plugin, "model_light_5_off")),
    LIGHT_6_OFF(new NamespacedKey(TARDIS.plugin, "model_light_6_off")),
    LIGHT_7_OFF(new NamespacedKey(TARDIS.plugin, "model_light_7_off")),
    CONSOLE_LAMP_0(new NamespacedKey(TARDIS.plugin, "model_console_lamp_0")),
    CONSOLE_LAMP_1(new NamespacedKey(TARDIS.plugin, "model_console_lamp_1")),
    CONSOLE_LAMP_2(new NamespacedKey(TARDIS.plugin, "model_console_lamp_2")),
    CONSOLE_LAMP_3(new NamespacedKey(TARDIS.plugin, "model_console_lamp_3")),
    CONSOLE_LAMP_4(new NamespacedKey(TARDIS.plugin, "model_console_lamp_4")),
    CONSOLE_LAMP_5(new NamespacedKey(TARDIS.plugin, "model_console_lamp_5")),
    CONSOLE_LAMP_6(new NamespacedKey(TARDIS.plugin, "model_console_lamp_6")),
    CONSOLE_LAMP_7(new NamespacedKey(TARDIS.plugin, "model_console_lamp_7")),
    CONSOLE_LAMP_0_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_0_off")),
    CONSOLE_LAMP_1_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_1_off")),
    CONSOLE_LAMP_2_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_2_off")),
    CONSOLE_LAMP_3_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_3_off")),
    CONSOLE_LAMP_4_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_4_off")),
    CONSOLE_LAMP_5_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_5_off")),
    CONSOLE_LAMP_6_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_6_off")),
    CONSOLE_LAMP_7_OFF(new NamespacedKey(TARDIS.plugin, "model_console_lamp_7_off")),
    HANDBRAKE_0(new NamespacedKey(TARDIS.plugin, "console_handbrake_0")),
    HANDBRAKE_1(new NamespacedKey(TARDIS.plugin, "console_handbrake_1")),
    RELATIVITY_DIFFERENTIATOR_0A(new NamespacedKey(TARDIS.plugin, "console_relativity_differentiator_0")),
    RELATIVITY_DIFFERENTIATOR_1A(new NamespacedKey(TARDIS.plugin, "console_relativity_differentiator_1")),
    RELATIVITY_DIFFERENTIATOR_2A(new NamespacedKey(TARDIS.plugin, "console_relativity_differentiator_2")),
    RELATIVITY_DIFFERENTIATOR_3A(new NamespacedKey(TARDIS.plugin, "console_relativity_differentiator_3")),
    MODELLED_LAMP_0(new NamespacedKey(TARDIS.plugin, "console_lamp_0")),
    MODELLED_LAMP_1(new NamespacedKey(TARDIS.plugin, "console_lamp_1")),
    MODELLED_LAMP_2(new NamespacedKey(TARDIS.plugin, "console_lamp_2")),
    MODELLED_LAMP_3(new NamespacedKey(TARDIS.plugin, "console_lamp_3")),
    MODELLED_LAMP_4(new NamespacedKey(TARDIS.plugin, "console_lamp_4")),
    MODELLED_LAMP_5(new NamespacedKey(TARDIS.plugin, "console_lamp_5")),
    MODELLED_LAMP_6(new NamespacedKey(TARDIS.plugin, "console_lamp_6")),
    MODELLED_LAMP_7(new NamespacedKey(TARDIS.plugin, "console_lamp_7")),
    MODELLED_LIGHT_0(new NamespacedKey(TARDIS.plugin, "console_light_0")),
    MODELLED_LIGHT_1(new NamespacedKey(TARDIS.plugin, "console_light_1")),
    MODELLED_LIGHT_2(new NamespacedKey(TARDIS.plugin, "console_light_2")),
    MODELLED_LIGHT_3(new NamespacedKey(TARDIS.plugin, "console_light_3")),
    MODELLED_LIGHT_4(new NamespacedKey(TARDIS.plugin, "console_light_4")),
    MODELLED_LIGHT_5(new NamespacedKey(TARDIS.plugin, "console_light_5")),
    MODELLED_LIGHT_6(new NamespacedKey(TARDIS.plugin, "console_light_6")),
    MODELLED_LIGHT_7(new NamespacedKey(TARDIS.plugin, "console_light_7")),
    THROTTLE_WARP(new NamespacedKey(TARDIS.plugin, "console_throttle_warp")),
    THROTTLE_RAPID(new NamespacedKey(TARDIS.plugin, "console_throttle_rapid")),
    THROTTLE_FASTER(new NamespacedKey(TARDIS.plugin, "console_throttle_faster")),
    THROTTLE_NORMAL(new NamespacedKey(TARDIS.plugin, "console_throttle_normal")),
    ASTROSEXTANT_RECTIFIER(new NamespacedKey(TARDIS.plugin, "console_astrosextant_rectifier")),
    GRAVITIC_ANOMOLISER(new NamespacedKey(TARDIS.plugin, "console_gravitic_anomoliser")),
    ABSOLUTE_TESSERACTULATOR(new NamespacedKey(TARDIS.plugin, "console_absolute_tesseractulator")),
    CONSOLE_LAMP(new NamespacedKey(TARDIS.plugin, "console_console_lamp")),
    HELMIC_REGULATOR_0(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_0")),
    HELMIC_REGULATOR_1(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_1")),
    HELMIC_REGULATOR_2(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_2")),
    HELMIC_REGULATOR_3(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_3")),
    HELMIC_REGULATOR_4(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_4")),
    HELMIC_REGULATOR_5(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_5")),
    HELMIC_REGULATOR_6(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_6")),
    HELMIC_REGULATOR_7(new NamespacedKey(TARDIS.plugin, "console_helmic_regulator_7")),
    MONITOR_FRAME_LEFT(new NamespacedKey(TARDIS.plugin, "monitor_frame_left")),
    MONITOR_FRAME_MIDDLE(new NamespacedKey(TARDIS.plugin, "monitor_frame_middle")),
    MONITOR_FRAME_RIGHT(new NamespacedKey(TARDIS.plugin, "monitor_frame_right")),
    MONITOR(new NamespacedKey(TARDIS.plugin, "monitor")),
    SCREEN(new NamespacedKey(TARDIS.plugin, "console_screen")),
    TELEPATHIC_CIRCUIT(new NamespacedKey(TARDIS.plugin, "console_telepathic_circuit"));

    private final NamespacedKey key;

    ModelledControl(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
