package me.eccentric_nz.TARDIS.custommodels.keys;

import me.eccentric_nz.TARDIS.TARDIS;
import org.bukkit.NamespacedKey;

public enum SwitchVariant {

    ABANDON_OFF(new NamespacedKey(TARDIS.plugin, "switch_abandon_off")),
    ABANDON_ON(new NamespacedKey(TARDIS.plugin, "switch_abandon_on")),
    ALLOW_OFF(new NamespacedKey(TARDIS.plugin, "switch_allow_off")),
    ALLOW_ON(new NamespacedKey(TARDIS.plugin, "switch_allow_on")),
    ANNOUNCE_REPEATERS_OFF(new NamespacedKey(TARDIS.plugin, "switch_announce_repeaters_off")),
    ANNOUNCE_REPEATERS_ON(new NamespacedKey(TARDIS.plugin, "switch_announce_repeaters_on")),
    ARCHIVE_OFF(new NamespacedKey(TARDIS.plugin, "switch_archive_off")),
    ARCHIVE_ON(new NamespacedKey(TARDIS.plugin, "switch_archive_on")),
    ARCH_OFF(new NamespacedKey(TARDIS.plugin, "switch_arch_off")),
    ARCH_ON(new NamespacedKey(TARDIS.plugin, "switch_arch_on")),
    AUTONOMOUS_OFF(new NamespacedKey(TARDIS.plugin, "switch_autonomous_off")),
    AUTONOMOUS_ON(new NamespacedKey(TARDIS.plugin, "switch_autonomous_on")),
    AUTONOMOUS_SIEGE_OFF(new NamespacedKey(TARDIS.plugin, "switch_autonomous_siege_off")),
    AUTONOMOUS_SIEGE_ON(new NamespacedKey(TARDIS.plugin, "switch_autonomous_siege_on")),
    AUTO_DEFAULT(new NamespacedKey(TARDIS.plugin, "switch_auto_default")),
    AUTO_POWER_UP_OFF(new NamespacedKey(TARDIS.plugin, "switch_auto_power_up_off")),
    AUTO_POWER_UP_ON(new NamespacedKey(TARDIS.plugin, "switch_auto_power_up_on")),
    AUTO_RESCUE_OFF(new NamespacedKey(TARDIS.plugin, "switch_auto_rescue_off")),
    AUTO_RESCUE_ON(new NamespacedKey(TARDIS.plugin, "switch_auto_rescue_on")),
    AUTO_TYPE(new NamespacedKey(TARDIS.plugin, "switch_auto_type")),
    BEACON_OFF(new NamespacedKey(TARDIS.plugin, "switch_beacon_off")),
    BEACON_ON(new NamespacedKey(TARDIS.plugin, "switch_beacon_on")),
    BLUEPRINTS_OFF(new NamespacedKey(TARDIS.plugin, "switch_blueprints_off")),
    BLUEPRINTS_ON(new NamespacedKey(TARDIS.plugin, "switch_blueprints_on")),
    BUTTON_LIGHTS_OFF(new NamespacedKey(TARDIS.plugin, "switch_button_lights_off")),
    BUTTON_LIGHTS_ON(new NamespacedKey(TARDIS.plugin, "switch_button_lights_on")),
    BUTTON_POWER_OFF(new NamespacedKey(TARDIS.plugin, "switch_button_power_off")),
    BUTTON_POWER_ON(new NamespacedKey(TARDIS.plugin, "switch_button_power_on")),
    BUTTON_SIEGE_OFF(new NamespacedKey(TARDIS.plugin, "switch_button_siege_off")),
    BUTTON_SIEGE_ON(new NamespacedKey(TARDIS.plugin, "switch_button_siege_on")),
    BUTTON_TOGGLE_OFF(new NamespacedKey(TARDIS.plugin, "switch_button_toggle_off")),
    BUTTON_TOGGLE_ON(new NamespacedKey(TARDIS.plugin, "switch_button_toggle_on")),
    CIRCUIT_OFF(new NamespacedKey(TARDIS.plugin, "switch_circuit_off")),
    CIRCUIT_ON(new NamespacedKey(TARDIS.plugin, "switch_circuit_on")),
    CLOSE_GUI_OFF(new NamespacedKey(TARDIS.plugin, "switch_close_gui_off")),
    CLOSE_GUI_ON(new NamespacedKey(TARDIS.plugin, "switch_close_gui_on")),
    COMPANION_BUILD_OFF(new NamespacedKey(TARDIS.plugin, "switch_companion_build_off")),
    COMPANION_BUILD_ON(new NamespacedKey(TARDIS.plugin, "switch_companion_build_on")),
    CONNECTED_TEXTURES_OFF(new NamespacedKey(TARDIS.plugin, "switch_connected_textures_off")),
    CONNECTED_TEXTURES_ON(new NamespacedKey(TARDIS.plugin, "switch_connected_textures_on")),
    CREATION_OFF(new NamespacedKey(TARDIS.plugin, "switch_creation_off")),
    CREATION_ON(new NamespacedKey(TARDIS.plugin, "switch_creation_on")),
    DEBUG_OFF(new NamespacedKey(TARDIS.plugin, "switch_debug_off")),
    DEBUG_ON(new NamespacedKey(TARDIS.plugin, "switch_debug_on")),
    DIFFICULTY_OFF(new NamespacedKey(TARDIS.plugin, "switch_difficulty_off")),
    DIFFICULTY_ON(new NamespacedKey(TARDIS.plugin, "switch_difficulty_on")),
    DOWNLOAD_OFF(new NamespacedKey(TARDIS.plugin, "switch_download_off")),
    DOWNLOAD_ON(new NamespacedKey(TARDIS.plugin, "switch_download_on")),
    DO_NOT_DISTURB_OFF(new NamespacedKey(TARDIS.plugin, "switch_do_not_disturb_off")),
    DO_NOT_DISTURB_ON(new NamespacedKey(TARDIS.plugin, "switch_do_not_disturb_on")),
    DYNAMIC_LAMPS_OFF(new NamespacedKey(TARDIS.plugin, "switch_dynamic_lamps_off")),
    DYNAMIC_LAMPS_ON(new NamespacedKey(TARDIS.plugin, "switch_dynamic_lamps_on")),
    EASY_DIFF_OFF(new NamespacedKey(TARDIS.plugin, "switch_easy_diff_off")),
    EASY_DIFF_ON(new NamespacedKey(TARDIS.plugin, "switch_easy_diff_on")),
    EMERGENCY_PROGRAM_ONE_OFF(new NamespacedKey(TARDIS.plugin, "switch_emergency_program_one_off")),
    EMERGENCY_PROGRAM_ONE_ON(new NamespacedKey(TARDIS.plugin, "switch_emergency_program_one_on")),
    EXTERIOR_RENDERING_ROOM_OFF(new NamespacedKey(TARDIS.plugin, "switch_exterior_rendering_room_off")),
    EXTERIOR_RENDERING_ROOM_ON(new NamespacedKey(TARDIS.plugin, "switch_exterior_rendering_room_on")),
    EYE_OFF(new NamespacedKey(TARDIS.plugin, "switch_eye_off")),
    EYE_ON(new NamespacedKey(TARDIS.plugin, "switch_eye_on")),
    FONT_OFF(new NamespacedKey(TARDIS.plugin, "switch_font_off")),
    FONT_ON(new NamespacedKey(TARDIS.plugin, "switch_font_on")),
    FORCE_FIELD_OFF(new NamespacedKey(TARDIS.plugin, "switch_force_field_off")),
    FORCE_FIELD_ON(new NamespacedKey(TARDIS.plugin, "switch_force_field_on")),
    GROWTH_OFF(new NamespacedKey(TARDIS.plugin, "switch_growth_off")),
    GROWTH_ON(new NamespacedKey(TARDIS.plugin, "switch_growth_on")),
    HADS_TYPE_DISPERSAL(new NamespacedKey(TARDIS.plugin, "switch_hads_type_dispersal")),
    HADS_TYPE_DISPLACEMENT(new NamespacedKey(TARDIS.plugin, "switch_hads_type_displacement")),
    HANDLES_OFF(new NamespacedKey(TARDIS.plugin, "switch_handles_off")),
    HANDLES_ON(new NamespacedKey(TARDIS.plugin, "switch_handles_on")),
    HOSTILE_ACTION_DISPLACEMENT_SYSTEM_OFF(new NamespacedKey(TARDIS.plugin, "switch_hostile_action_displacement_system_off")),
    HOSTILE_ACTION_DISPLACEMENT_SYSTEM_ON(new NamespacedKey(TARDIS.plugin, "switch_hostile_action_displacement_system_on")),
    INFO_OFF(new NamespacedKey(TARDIS.plugin, "switch_info_off")),
    INFO_ON(new NamespacedKey(TARDIS.plugin, "switch_info_on")),
    INTERIOR_SFX_OFF(new NamespacedKey(TARDIS.plugin, "switch_interior_sfx_off")),
    INTERIOR_SFX_ON(new NamespacedKey(TARDIS.plugin, "switch_interior_sfx_on")),
    JUNK_OFF(new NamespacedKey(TARDIS.plugin, "switch_junk_off")),
    JUNK_ON(new NamespacedKey(TARDIS.plugin, "switch_junk_on")),
    JUNK_TARDIS_OFF(new NamespacedKey(TARDIS.plugin, "switch_junk_tardis_off")),
    JUNK_TARDIS_ON(new NamespacedKey(TARDIS.plugin, "switch_junk_tardis_on")),
    LANTERNS_OFF(new NamespacedKey(TARDIS.plugin, "switch_lanterns_off")),
    LANTERNS_ON(new NamespacedKey(TARDIS.plugin, "switch_lanterns_on")),
    LOCK_CONTAINERS_OFF(new NamespacedKey(TARDIS.plugin, "switch_lock_containers_off")),
    LOCK_CONTAINERS_ON(new NamespacedKey(TARDIS.plugin, "switch_lock_containers_on")),
    MINECART_OFF(new NamespacedKey(TARDIS.plugin, "switch_minecart_off")),
    MINECART_ON(new NamespacedKey(TARDIS.plugin, "switch_minecart_on")),
    MOB_FARMING_OFF(new NamespacedKey(TARDIS.plugin, "switch_mob_farming_off")),
    MOB_FARMING_ON(new NamespacedKey(TARDIS.plugin, "switch_mob_farming_on")),
    POLICE_BOX_OFF(new NamespacedKey(TARDIS.plugin, "switch_police_box_off")),
    POLICE_BOX_ON(new NamespacedKey(TARDIS.plugin, "switch_police_box_on")),
    POLICE_BOX_TEXTURES_OFF(new NamespacedKey(TARDIS.plugin, "switch_police_box_textures_off")),
    POLICE_BOX_TEXTURES_ON(new NamespacedKey(TARDIS.plugin, "switch_police_box_textures_on")),
    PREFERENCES_OFF(new NamespacedKey(TARDIS.plugin, "switch_preferences_off")),
    PREFERENCES_ON(new NamespacedKey(TARDIS.plugin, "switch_preferences_on")),
    PRESET_SIGN_OFF(new NamespacedKey(TARDIS.plugin, "switch_preset_sign_off")),
    PRESET_SIGN_ON(new NamespacedKey(TARDIS.plugin, "switch_preset_sign_on")),
    RESOURCE_PACK_SWITCHING_OFF(new NamespacedKey(TARDIS.plugin, "switch_resource_pack_switching_off")),
    RESOURCE_PACK_SWITCHING_ON(new NamespacedKey(TARDIS.plugin, "switch_resource_pack_switching_on")),
    SIEGE_OFF(new NamespacedKey(TARDIS.plugin, "switch_siege_off")),
    SIEGE_ON(new NamespacedKey(TARDIS.plugin, "switch_siege_on")),
    SONIC_OFF(new NamespacedKey(TARDIS.plugin, "switch_sonic_off")),
    SONIC_ON(new NamespacedKey(TARDIS.plugin, "switch_sonic_on")),
    SUBMARINE_MODE_OFF(new NamespacedKey(TARDIS.plugin, "switch_submarine_mode_off")),
    SUBMARINE_MODE_ON(new NamespacedKey(TARDIS.plugin, "switch_submarine_mode_on")),
    TELEPATHIC_CIRCUIT_OFF(new NamespacedKey(TARDIS.plugin, "switch_telepathic_circuit_off")),
    TELEPATHIC_CIRCUIT_ON(new NamespacedKey(TARDIS.plugin, "switch_telepathic_circuit_on")),
    THEME_OFF(new NamespacedKey(TARDIS.plugin, "switch_theme_off")),
    THEME_ON(new NamespacedKey(TARDIS.plugin, "switch_theme_on")),
    TRAVEL_BAR_OFF(new NamespacedKey(TARDIS.plugin, "switch_travel_bar_off")),
    TRAVEL_BAR_ON(new NamespacedKey(TARDIS.plugin, "switch_travel_bar_on")),
    TRAVEL_OFF(new NamespacedKey(TARDIS.plugin, "switch_travel_off")),
    TRAVEL_ON(new NamespacedKey(TARDIS.plugin, "switch_travel_on")),
    WHO_QUOTES_OFF(new NamespacedKey(TARDIS.plugin, "switch_who_quotes_off")),
    WHO_QUOTES_ON(new NamespacedKey(TARDIS.plugin, "switch_who_quotes_on")),
    WOOL_FOR_LIGHTS_OFF(new NamespacedKey(TARDIS.plugin, "switch_wool_for_lights_off")),
    WOOL_FOR_LIGHTS_ON(new NamespacedKey(TARDIS.plugin, "switch_wool_for_lights_on"));

    private final NamespacedKey key;

    SwitchVariant(NamespacedKey key) {
        this.key = key;
    }

    public NamespacedKey getKey() {
        return key;
    }
}
