on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "2105893"
          username: "TARDIS GitHub"
          avatar_url: "https://cdn.discordapp.com/avatars/696058911916163142/6e478142a416b8490f39d08801eafb22.png"
          #content: "||@everyone||"
          #footer_title: "Changelog"
          #reduce_headings: true